import type {ReferenceDataProposalFamily} from "./types";

/**
 * Intake, materials and quality control: request batches, archetype requirements, question sets,
 * rounding, QC tolerances and red flags. Every value below is a draft prepared for the founder's
 * review; the professional text of each key lives in `knowledge/reference-data/intake-materials-qc.md`.
 *
 * Field names carry their unit (`...Days`, `...BusinessDays`, `...Months`, `...Pct`, `...Pp`,
 * `...Brl`). Decimal thresholds are strings, as the registry and the red-flag consumer read them.
 * Where a consumer already reads a shape (`red_flag_policies.thresholds`, `IntakePolicy`), the
 * field names here are the ones it reads.
 */

const VERSION = "2026.09.24-v1";
const AS_OF = "2026-09-24";
const OBSERVED_BY = "Offroad (Claude, executor), 24/09/2026, aguardando revisão do fundador";
const CARD = "knowledge/reference-data/intake-materials-qc.md";
const PLAYBOOK_URL = "https://github.com/carlosevg100/offroad/blob/main/packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";
const CONSTITUTION_URL = "https://github.com/carlosevg100/offroad/blob/main/docs/build/OFFROAD_DCM_OPERATING_CONSTITUTION.md";
const IBGE_TABULAR_URL = "https://biblioteca.ibge.gov.br/visualizacao/monografias/GEBIS%20-%20RJ/normastabular.pdf";

export const intakeMaterialsQcProposals: ReferenceDataProposalFamily = {
  "policy.intake.request_batch.max_items": {
    version: VERSION,
    value: {
      defaultActiveRequests: 4,
      maxActiveRequests: 5,
      fifthSlot: {
        opensOnlyForPriority: "case_blocker",
        condition: "o quinto item, na ordem de prioridade do estágio ativo, é bloqueador de entendimento (requisito do nível mínimo)",
      },
      priorityOrder: ["case_blocker", "structure_driver", "mandate_driver", "material_quality"],
      tieBreakers: ["purpose_order", "playbook_order"],
      purposeOrder: ["financials", "structure", "investor_case", "storytelling"],
      activeStageOrder: ["now", "structuring"],
      neverActiveStages: ["diligence", "closing"],
      batchMode: "closed_batch",
      nextBatchCondition: "todo item do lote atual resolvido (satisfeito; não se aplica com motivo; não disponível; após NDA) ou dispensado por decisão registrada do responsável pelo caso, e a evidência recebida lida pelo sistema",
      itemDefinition: "um requisito por item; artefatos alternativos aceitos para o mesmo requisito contam como um único item",
      ladderBeforeRequest: {
        degrees: [1, 2, 3],
        rule: "IN-13: busca na sala classificada, derivação declarada e fonte pública registrada, com o motivo da descida, antes de o item entrar no lote",
      },
      suppressAlreadySatisfied: true,
      responseWindowsKey: "policy.red-flags.response-sla",
      telemetry: {
        targetBatchesBeforeAnalysis: 3,
        unavailableShareReviewTrigger: "0.25",
        unavailableShareWindowClosedBatches: 20,
        reviewRuleOnTrigger: "IN-11: auditoria da lista do arquétipo",
      },
    },
    unit: "itens ativos por lote",
    source: {
      title: "Constituição de Produto e Operação da Offroad, versão 2.6, seção 6.2 (quatro solicitações por padrão e nunca mais de cinco); House Playbook v2.1, IN-13 e IN-14",
      url: CONSTITUTION_URL,
      observedBy: OBSERVED_BY,
    },
    asOf: AS_OF,
    documentation: `${CARD}#policy.intake.request_batch.max_items`,
  },

  "policy.intake.archetype-requirements": {
    version: VERSION,
    value: {
      tiers: {
        minimum: {gate: "etapa_05_conciliacao", test: "decisão que fica impossível sem o item (IN-11)", blocksAnalysisStart: true},
        target: {gate: "etapa_07_e_materiais", test: "conclusão de estrutura ou material que sairia com limitação declarada sem o item", missingItemRequires: "limitação registrada pelo responsável pelo caso e divulgada no memo (IN-16)"},
        ideal: {gate: "nenhum", test: "item que muda preço ou velocidade de execução", blocksAnalysisStart: false},
      },
      sufficiencyDisplay: "mínimo N de M; alvo X de Y; ideal Z de W",
      archetypeTierOverridesCommon: true,
      periods: {
        annualFiscalYears: 3,
        annualFiscalYearsWhenYounger: "todos os exercícios encerrados",
        interimMaxAgeDaysAtRequest: 90,
        interimMaxAgeDaysAtMaterialRelease: 135,
        interimPriorYearComparablePeriodTier: "target",
        monthlySeriesMonthsMinimumWorkingCapital: 12,
        monthlySeriesMonthsTarget: 24,
        monthlySeriesGovernedBy: "policy.seasonality.materiality (window.minimumMonths 24; quarterlyDataMinimumQuarters 8)",
        bankStatementsMonthsIdeal: 12,
        bankStatementsMonthsVentureTarget: 6,
        agingDatesCount: 3,
        agingWindowMonths: 12,
        agingDatesGovernedBy: "policy.receivables.aging (snapshots: último fechamento mensal, fechamento do exercício anterior, fechamento trimestral do pico sazonal de recebíveis)",
        covenantAndWaiverLookbackMonths: 36,
        rampHistoryMonths: 24,
        ventureMetricsMonths: 24,
        runwayBurnWindowMonths: 3,
        receivablesLossHistoryMonths: 24,
        lienCertificateMaxAgeDays: 30,
      },
      maxDirectQuestionsDayZero: 4,
      ladderFirstItems: {
        info_why_now: "quadro do pedido registrado no intake (IN-01: uso, urgência e consequência)",
        info_business_model: "pesquisa pública da companhia e material institucional já recebido",
        info_cash_cycle: "derivação de PMR, PME e PMP das demonstrações e balancetes",
        info_runway: "derivação do caixa sobre a queima líquida média de 3 meses",
        info_deal_terms: "extração dos documentos da transação (LOI, MOU ou SPA)",
        info_equipment_profile: "extração da proposta ou do orçamento do fornecedor",
        corporate_identity: "cadastro público do CNPJ e certidão da junta comercial; organograma só quando IN-02 indicar grupo",
        request: "quadro do pedido registrado no intake (IN-01)",
      },
      common: {
        minimum: ["financials_historical", "financials_interim", "debt_schedule", "corporate_identity", "request", "info_why_now", "info_business_model", "info_customer_concentration"],
        target: ["auditor_opinion", "monthly_financials_24m", "info_related_parties", "info_seasonality", "info_management"],
        ideal: ["reviewed_interim", "institutional_materials", "bank_statements", "tax_clearance"],
        noticeOnly: ["closing_corporate_approvals", "closing_certificates", "closing_security_registration", "closing_legal_opinion", "closing_disbursement_evidence"],
      },
      archetypes: {
        growth_expansion: {
          playbookRule: "IN-04",
          addMinimum: ["project_plan", "info_ramp_history", "info_capex_actual"],
          addTarget: ["project_schedule", "info_permits", "unit_economics", "project_contracts", "info_project_spent_to_date", "info_contractor", "info_minimum_viable_scope"],
          conditionalTarget: {
            appraisal: "pacote com alienação fiduciária de imóvel ou de equipamento",
            receivables_aging_for_collateral: "pacote com cessão fiduciária de recebíveis",
          },
          addIdeal: [],
          minimumCount: 11,
        },
        working_capital: {
          playbookRule: "IN-05",
          addMinimum: ["revenue_evidence", "info_assigned_receivables", "info_cash_cycle", "info_seasonality", "info_supplier_finance"],
          addTarget: ["receivables_aging", "payables_aging", "info_customer_terms_change"],
          conditionalTarget: {customer_contracts: "pacote com cessão fiduciária de recebíveis de contratos"},
          addIdeal: [],
          contentRules: {debt_schedule: "limites aprovados e utilizados de cada linha de curto prazo, com data de renovação (D-05)"},
          minimumCount: 13,
        },
        refinance: {
          playbookRule: "IN-06",
          addMinimum: ["debt_contracts", "info_prepayment", "info_waiver_in_progress"],
          addTarget: ["collateral_release", "waivers", "lien_certificates"],
          conditionalTarget: {},
          addIdeal: [],
          contentRules: {debt_schedule: "relação completa contrato a contrato com cronograma; reconstrução pelas notas explicativas não satisfaz o mínimo neste arquétipo"},
          minimumCount: 11,
        },
        acquisition: {
          playbookRule: "IN-07",
          addMinimum: ["target_financials", "transaction_documents", "info_synergies", "info_deal_terms"],
          addTarget: ["due_diligence", "post_structure"],
          conditionalTarget: {},
          addIdeal: [],
          perimeter: "compradora e adquirida; demonstrações e posição intermediária exigidas para as duas",
          minimumCount: 12,
        },
        equipment_finance: {
          playbookRule: "IN-08",
          addMinimum: ["equipment_quote", "info_asset_productivity", "info_equipment_profile"],
          addTarget: ["equipment_appraisal"],
          conditionalTarget: {},
          addIdeal: ["insurance"],
          minimumCount: 11,
        },
        venture_debt: {
          playbookRule: "IN-09",
          addMinimum: ["metrics_export", "cap_table_and_round", "info_runway", "info_next_round", "info_board_debt_approval"],
          addTarget: ["bank_statements", "info_warrant_appetite"],
          conditionalTarget: {},
          addIdeal: [],
          minimumCount: 13,
        },
        receivables: {
          playbookRule: "IN-10",
          route: "receivables_vertical",
          catalogue: "receivables-evidence 2026.08.28-v1 (packages/credit-playbook/src/receivables-evidence.ts)",
          minimumFacts: ["claim_existence_evidenced", "analytical_tape_available", "cedent_ownership_confirmed", "unresolved_prior_assignment_or_lien", "title_control_and_duplicate_check_available", "contractual_assignability_confirmed", "historical_performance_available", "performance_or_delivery_evidenced", "company_credit_package_available"],
          targetFacts: ["debtor_notice_or_acknowledgement_feasible", "controlled_collections_feasible", "servicing_capability_available"],
          idealFactsByStructure: ["recurring_origination_available", "buyer_confirmed_program_available", "economically_viable_scale_confirmed", "institutional_vehicle_governance_ready", "eligible_collateral_pool_identified", "security_perfection_feasible"],
        },
        other: {
          playbookRule: "IN-03",
          addMinimum: [],
          addTarget: [],
          conditionalTarget: {},
          addIdeal: [],
          contentRules: {request: "uso dos recursos com valor por destinação"},
          deskReviewBusinessDays: 1,
          minimumCount: 8,
        },
      },
      groupExpansion: {
        trigger: "IN-02 ou IN-24 indicam grupo econômico",
        materialEntityRule: "entidade que toma, garante ou gera o caixa da operação, ou com receita, ativo total ou dívida bruta igual ou superior a 10% do consolidado",
        materialEntityThresholdShare: "0.10",
        addPerMaterialEntity: ["financials_historical", "financials_interim"],
        addOnce: "organograma societário com participações e papéis das entidades",
      },
      substitutes: {
        financials_historical: {
          preferred: ["audited_financial_statements"],
          accepted: ["reviewed_interim_statements", "management_accounts"],
          verifiableEvidenceForUnaudited: "ECD transmitida ao Sped com recibo de entrega (IN RFB 2.003/2021, arts. 3º e 5º)",
          mandatoryAuditThresholds: {totalAssetsBrl: "240000000.00", grossRevenueBrl: "300000000.00", basis: "Lei 11.638/2007, art. 3º, parágrafo único; companhia ou grupo sob controle comum, no exercício anterior"},
          whenMandatoryAuditMissing: "substituto não aceito; ausência de auditoria obrigatória registrada como achado de conformidade",
          effectsOfSubstitute: ["buyer_universe_limited_unaudited", "disclosed_in_memo", "q09_reconciliation_required"],
        },
        financials_interim: {
          preferred: ["reviewed_interim_statements", "trial_balance"],
          accepted: ["erp_export", "management_accounts"],
          staleRule: "data-base acima de 90 dias no pedido exige atualização; acima de 135 dias na liberação de material bloqueia o material",
          effectsOfSubstitute: ["interim_unreviewed_label"],
        },
        debt_schedule: {
          preferred: ["debt_schedule"],
          accepted: ["loan_agreement", "debenture_indenture"],
          complementaryOnly: ["notas explicativas (reconstrução rotulada como estimativa)", "relatório SCR obtido pela companhia no Registrato (conciliação, D-23)"],
          effectsOfSubstitute: ["house_builds_schedule_from_contracts"],
        },
        corporate_identity: {
          preferred: ["corporate_docs", "company_registration"],
          accepted: ["cadastro público do CNPJ", "certidão simplificada da junta comercial"],
          effectsOfSubstitute: [],
        },
        monthly_financials_24m: {
          preferred: ["trial_balance", "erp_export"],
          accepted: ["management_accounts", "ECD com saldos mensais"],
          degradedSubstitute: "balancetes trimestrais de 8 trimestres, com ressalva registrada (Q-04; policy.seasonality.materiality)",
          effectsOfSubstitute: ["seasonality_single_cycle_label"],
        },
        auditor_opinion: {
          preferred: ["audited_financial_statements", "auditor_report_only"],
          accepted: [],
          whenCompanyUnaudited: "não se aplica, com motivo registrado",
          effectsOfSubstitute: [],
        },
        receivables_aging: {
          preferred: ["receivables_aging"],
          accepted: ["erp_export"],
          degradedSubstitute: "aging por faixa com os 10 maiores devedores e conciliação ao contas a receber",
          effectsOfSubstitute: ["disclosed_in_memo"],
        },
        bank_statements: {
          preferred: ["bank_statements"],
          accepted: ["open_finance_export"],
          degradedSubstitute: "declaração de saldos emitida pela instituição financeira",
          effectsOfSubstitute: [],
        },
      },
      newRequirements: {
        monthly_financials_24m: {source: "document", tier: "target", archetypes: "todos", acceptedKinds: ["trial_balance", "erp_export", "management_accounts"], period: "balancetes mensais dos últimos 24 meses", rules: ["Q-04", "Q-11"]},
        project_contracts: {source: "document", tier: "target", archetypes: ["growth_expansion"], acceptedKinds: ["supplier_contract", "project_memorandum", "technical_report"], period: "contratos relevantes assinados do projeto (obra, equipamentos, fornecimento)", rules: ["IN-04"]},
        lien_certificates: {source: "document", tier: "target", archetypes: ["refinance"], acceptedKinds: ["collateral_inventory", "regulatory_filing"], period: "certidões de ônus e gravames das garantias dadas, emitidas há no máximo 30 dias", rules: ["IN-06", "D-19"]},
        info_project_spent_to_date: {source: "information", tier: "target", archetypes: ["growth_expansion"], answerFormat: "currency", question: "Quanto do projeto já foi desembolsado, em quê e com que recursos?", rules: ["IN-04"]},
        info_contractor: {source: "information", tier: "target", archetypes: ["growth_expansion"], answerFormat: "text", question: "Quem executa a obra e em que regime de contratação (preço global, preço unitário ou administração)?", rules: ["IN-04"]},
        info_minimum_viable_scope: {source: "information", tier: "target", archetypes: ["growth_expansion"], answerFormat: "text", question: "O projeto funciona em escala menor ou em fases? Com qual valor mínimo?", rules: ["IN-04", "OP-07"]},
        info_supplier_finance: {source: "information", tier: "minimum", archetypes: ["working_capital"], answerFormat: "text", question: "A companhia usa antecipação a fornecedores (risco sacado, confirming ou forfait)? Com que saldo e com quais instituições?", rules: ["IN-05", "D-06"]},
        info_customer_terms_change: {source: "information", tier: "target", archetypes: ["working_capital"], answerFormat: "text", question: "O prazo de pagamento de algum cliente relevante mudou nos últimos 12 meses?", rules: ["IN-05", "RF-02"]},
        info_waiver_in_progress: {source: "information", tier: "minimum", archetypes: ["refinance"], answerFormat: "text", question: "Há waiver, repactuação ou negociação de covenant em curso com algum credor?", rules: ["IN-06", "D-21"]},
        info_deal_terms: {source: "information", tier: "minimum", archetypes: ["acquisition"], answerFormat: "text", question: "Qual o preço, a forma de pagamento, o earn-out e o tratamento da dívida da adquirida (assumida ou quitada)?", rules: ["IN-07"]},
        info_equipment_profile: {source: "information", tier: "minimum", archetypes: ["equipment_finance"], answerFormat: "text", question: "O bem é nacional ou importado, novo ou usado, de fornecedor credenciado? Qual o prazo de entrega?", rules: ["IN-08"]},
        info_board_debt_approval: {source: "information", tier: "minimum", archetypes: ["venture_debt"], answerFormat: "text", question: "O acordo de investimento exige aprovação dos investidores ou do conselho para contrair dívida e dar garantias? Em que termos?", rules: ["IN-09"]},
        info_warrant_appetite: {source: "information", tier: "target", archetypes: ["venture_debt"], answerFormat: "percentage", question: "Que diluição via warrant a companhia aceita em troca de preço menor?", rules: ["IN-09"]},
      },
      codeAlignment: {
        promotedFromIdeal: {working_capital: ["info_seasonality"], venture_debt: ["bank_statements"]},
        extendedPeriod: {revenue_evidence: "12 meses no mínimo; série mensal de 24 meses no alvo por monthly_financials_24m"},
      },
      listAudit: {
        cadence: "trimestral",
        demotionWindowCases: 10,
        demotionAbsentWithoutLimitationShare: "0.30",
        rule: "item do mínimo ausente em 30% ou mais dos 10 últimos casos do arquétipo sem limitar conclusão é rebaixado ao alvo (IN-11)",
      },
    },
    unit: "requisitos por arquétipo e nível; períodos em exercícios, meses e dias corridos",
    source: {
      title: "House Playbook v2.1, IN-03 a IN-12 (listas dia-zero, mínimo e ideal, régua de suficiência); auditoria obrigatória de grande porte pela Lei 11.638/2007, art. 3º",
      url: PLAYBOOK_URL,
      observedBy: OBSERVED_BY,
    },
    asOf: AS_OF,
    documentation: `${CARD}#policy.intake.archetype-requirements`,
  },

  "policy.material.question-sets": {
    version: VERSION,
    value: {
      setVersion: VERSION,
      baseCatalogue: "packages/case-materials/src/diligence.ts, perguntas q01 a q40",
      materialityLevels: {
        material: "a resposta pode mudar a decisão do comitê do financiador; avaliada por probabilidade e magnitude (Resolução CVM 160, art. 19, § 2º)",
        supporting: "a resposta melhora a compreensão sem mudar a decisão",
      },
      categoryOrder: ["derived_red_flags", "derived_absences", "business", "financials", "debt", "transaction", "projections", "governance_legal", "project_operations", "venture", "archetype_specific", "sector_lens"],
      categories: {
        business: ["q01", "q02", "q03", "q04", "q05"],
        financials: ["q06", "q07", "q08", "q09", "q10"],
        debt: ["q11", "q12", "q13", "q14", "q15", "q16"],
        transaction: ["q17", "q18", "q19", "q20"],
        projections: ["q21", "q22", "q23", "q24", "q25"],
        governance_legal: ["q26", "q27", "q28", "q29", "q30"],
        project_operations: ["q31", "q32", "q33", "q34", "q35"],
        venture: ["q36", "q37", "q38", "q39", "q40"],
      },
      defaultMateriality: {
        material: ["q02", "q03", "q04", "q06", "q07", "q08", "q10", "q11", "q12", "q13", "q14", "q15", "q16", "q17", "q18", "q19", "q21", "q22", "q23", "q25", "q26", "q27", "q28", "q30", "q31", "q32", "q33", "q36", "q37", "q38", "q39"],
        supporting: ["q01", "q05", "q09", "q20", "q24", "q29", "q34", "q35", "q40"],
      },
      archetypes: {
        growth_expansion: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal", "project_operations"], exclude: [], promoteToMaterial: ["q24"], specific: ["gx01", "gx02", "gx03", "gx04"]},
        working_capital: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q34", "q35"], promoteToMaterial: ["q05", "q09", "q24"], specific: ["wc01", "wc02", "wc03"]},
        refinance: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q34", "q35"], promoteToMaterial: [], specific: ["rf01", "rf02", "rf03", "rf04"]},
        acquisition: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q34", "q35"], promoteToMaterial: [], specific: ["aq01", "aq02", "aq03", "aq04", "aq05"]},
        equipment_finance: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q31", "q33", "q34", "q35"], promoteToMaterial: ["q35"], specific: ["eq01", "eq02", "eq03"]},
        venture_debt: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal", "venture"], exclude: ["q16", "q23", "q25"], extra: ["q34"], promoteToMaterial: [], specific: ["vd01"]},
        receivables: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q34", "q35"], promoteToMaterial: ["q09"], specific: ["rc01", "rc02", "rc03", "rc04"]},
        other: {include: ["business", "financials", "debt", "transaction", "projections", "governance_legal"], exclude: [], extra: ["q34", "q35"], promoteToMaterial: [], specific: ["ot01"]},
      },
      specificQuestions: {
        gx01: {materiality: "material", question: "Qual foi a receita mensal das últimas unidades abertas, do mês 1 ao mês 24?"},
        gx02: {materiality: "material", question: "Quanto custou de fato a última unidade frente ao orçado, e o que ficou fora do orçamento?"},
        gx03: {materiality: "material", question: "O projeto funciona em escala menor ou em fases, se parte do recurso não vier?"},
        gx04: {materiality: "material", question: "Quem executa a obra e em que regime de contratação?"},
        wc01: {materiality: "material", question: "Que parcela dos recebíveis já está cedida ou vinculada, e a quais credores?"},
        wc02: {materiality: "material", question: "Há programa de antecipação a fornecedores (risco sacado)? Qual o saldo e com quais instituições?"},
        wc03: {materiality: "material", question: "Quanto dos limites de curto prazo está utilizado e quando cada linha renova?"},
        rf01: {materiality: "material", question: "Quais multas de pré-pagamento e custos de liquidação incidem sobre a dívida substituída?"},
        rf02: {materiality: "material", question: "Em que condições e em que prazo cada credor atual libera as garantias?"},
        rf03: {materiality: "material", question: "Houve quebra de covenant, waiver ou repactuação nos últimos 36 meses? Como foi resolvida?"},
        rf04: {materiality: "material", question: "Quanto a vida média e o custo da dívida mudam depois da operação, na mesma base?"},
        aq01: {materiality: "material", question: "As demonstrações da adquirida são auditadas? Por quem e com que ressalvas?"},
        aq02: {materiality: "material", question: "Qual o preço, a forma de pagamento, o earn-out e o tratamento da dívida da adquirida?"},
        aq03: {materiality: "material", question: "Quais sinergias entram na base de EBITDA do covenant, com plano, prazo e responsável?"},
        aq04: {materiality: "material", question: "Há escrow ou retenção de preço para contingências da adquirida? De quanto e por quanto tempo?"},
        aq05: {materiality: "material", question: "Depois da operação, em que entidade fica a dívida e em qual fica o caixa que a paga?"},
        eq01: {materiality: "material", question: "O prazo da dívida termina antes do fim da vida útil do equipamento? Com que folga?"},
        eq02: {materiality: "material", question: "Há mercado secundário para o equipamento? Qual a referência de revenda?"},
        eq03: {materiality: "material", question: "Qual o prazo de entrega e instalação até o equipamento produzir?"},
        vd01: {materiality: "material", question: "Quais direitos de veto dos investidores alcançam a contratação de dívida e a outorga de garantias?"},
        rc01: {materiality: "material", question: "Qual a performance da carteira nos últimos 24 meses: atraso, perda e diluição?"},
        rc02: {materiality: "material", question: "Quais os critérios de elegibilidade e os limites de concentração por sacado?"},
        rc03: {materiality: "material", question: "Quem cobra e como o fluxo dos sacados chega à conta vinculada?"},
        rc04: {materiality: "material", question: "Há cessão anterior, ônus ou vinculação sobre a carteira oferecida?"},
        ot01: {materiality: "material", question: "Qual o uso dos recursos, com valor por destinação?"},
      },
      derivedQuestions: {
        redFlags: {from: "flags com estado confirmed, treated ou accepted_risk", materiality: "material", answer: "resultado da investigação e tratamento, com marcador de evidência"},
        absences: {from: "ausência material registrada (IN-16)", materiality: "material", answer: "não disponível, solicitado em data; ou após NDA; ou dependente de confirmação, com responsável e data"},
        sectorLens: {from: "métricas da lente setorial aplicável (EMP-21 a EMP-30)", materiality: "material quando a métrica entra no cálculo de capacidade; supporting nos demais casos"},
      },
      coverage: {
        materialApplicableIncludedShare: "1.00",
        memoSection11: "todas as perguntas materiais, respondidas e em aberto, na ordem de categoryOrder (MA-04, seção 11)",
        noUniversalCount: true,
      },
      answerRules: {
        markerRequired: true,
        memoryAnswerAllowed: false,
        openStatuses: ["nao_disponivel_solicitado", "apos_nda", "dependente_de_confirmacao"],
        openStatusRequires: ["responsável", "data"],
        companyValidationRecorded: true,
      },
      releaseRules: {
        minimumTierQuestionsAnswered: true,
        materialOpenQuestionsDisclosedInMemo: true,
        answersWithoutMarkerAllowed: 0,
        companyValidationBoundToVersion: true,
        claimAuditKey: "policy.qc.numeric_tolerance",
      },
      evolution: {
        recurrenceDistinctCases: 2,
        recurrenceWindowMonths: 12,
        diligenceSurpriseTriggersImmediately: true,
        proposalReviewCadence: "trimestral",
        rule: "pergunta material fora do conjunto que aparece em 2 casos distintos do mesmo arquétipo em 12 meses, ou em qualquer surpresa de diligência (LC-12), gera proposta de nova versão (MA-22)",
      },
    },
    unit: "perguntas por arquétipo e materialidade",
    source: {
      title: "House Playbook v2.1, MA-22 e MA-23; materialidade por probabilidade e magnitude e ordem decrescente segundo a Resolução CVM 160/2022, art. 19",
      url: PLAYBOOK_URL,
      observedBy: OBSERVED_BY,
    },
    asOf: AS_OF,
    documentation: `${CARD}#policy.material.question-sets`,
  },

  "policy.material.numeric_rounding": {
    version: VERSION,
    value: {
      calculation: {
        intermediateRounding: "prohibited",
        canonicalDecimalPlaces: 8,
        engineRoundingMode: "ROUND_HALF_UP",
      },
      display: {
        roundingMode: "ROUND_HALF_UP",
        tieRule: "primeiro algarismo abandonado de 5 a 9 aumenta em uma unidade o último conservado, em valor absoluto (IBGE, Normas de apresentação tabular, 7.2 e 7.3)",
        appliedOnce: true,
        fromCanonicalValue: true,
        doubleRounding: "prohibited",
        precisionNeverAboveSource: true,
        oneScalePerTable: true,
      },
      classes: {
        money_statement_table: {unit: "BRL thousand", decimals: 0, negative: "parentheses", appliesTo: "demonstrações, spread da casa (Q-18), tabelas do memo e modelo entregável"},
        money_material_text: {
          bands: [
            {fromBrl: "0.00", toBrl: "100000.00", unit: "BRL", decimals: 0},
            {fromBrl: "100000.00", toBrl: "1000000.00", unit: "BRL thousand", decimals: 0},
            {fromBrl: "1000000.00", toBrl: "10000000.00", unit: "BRL million", decimals: 2},
            {fromBrl: "10000000.00", toBrl: "1000000000.00", unit: "BRL million", decimals: 1},
            {fromBrl: "1000000000.00", toBrl: null, unit: "BRL billion", decimals: 2},
          ],
          bandRule: "faixa pelo valor absoluto canônico; limite inferior incluído, superior excluído",
          maxRelativeRoundingErrorFromBrl100Thousand: "0.005",
          appliesTo: "texto de teaser, memo, Q&A e seções narrativas",
        },
        money_chat: {significantDigits: 3, units: ["mil", "mi", "bi"], appliesTo: "conversa e tela de leitura"},
        money_contract_term: {unit: "BRL", decimals: 2, appliesTo: "montante, valor nominal e valores contratuais do term sheet"},
        percent_share: {decimals: 1, label: "%", appliesTo: "margens, crescimento, participações e concentrações"},
        percentage_point_change: {decimals: 1, label: "p.p.", appliesTo: "variação de percentual"},
        rate_per_year: {decimals: 2, label: "% a.a.", appliesTo: "taxas, custo médio, custo all-in"},
        spread_over_di: {decimals: 2, label: "% a.a.", technicalUnit: "bps", technicalDecimals: 0},
        percent_of_di: {decimals: 2, label: "% do DI"},
        contract_quoted_rate: {decimals: "as_written_in_contract"},
        multiple_material: {decimals: 2, label: "x", appliesTo: "alavancagem, cobertura e covenants em material"},
        multiple_chat: {decimals: 1, label: "x"},
        limit_boundary: {maxDecimals: 4, rule: "se o arredondamento esconder de que lado do limite o índice está, exibir casas adicionais até 4 e declarar o lado pela comparação exata"},
        days: {decimals: 0},
        months: {decimals: 0},
        average_life_years: {decimals: 1},
        duration_years: {decimals: 2},
        fx_rate: {decimals: 4},
        published_index: {decimals: "as_published"},
        basis_points: {decimals: 0},
        count: {decimals: 0},
      },
      totals: {
        rule: "total arredondado a partir da soma exata; parcelas arredondadas individualmente; nenhuma parcela ajustada para fechar",
        maxDisplayedDifference: "0,5 unidade do último algarismo exibido multiplicada pelo número de parcelas",
        note: "Totais podem não corresponder à soma das parcelas por arredondamento.",
        percentColumns: "mesma regra, com a nota quando a soma exibida diferir de 100",
        basis: "IBGE, Normas de apresentação tabular, 7.4(a)",
      },
      signs: {
        trueZero: "0",
        roundedToZeroPositive: "zero com as casas da classe (0,0)",
        roundedToZeroNegative: "zero negativo com as casas da classe (-0,0)",
        notAvailable: "n.d.",
        notApplicable: "n.a.",
        notMeaningful: "n.s.",
        omittedToAvoidIdentification: "x",
        dashAsSign: "prohibited",
        notMeaningfulWhen: ["múltiplo com denominador igual ou menor que zero", "crescimento sobre base igual ou menor que zero"],
      },
      negatives: {tables: "parênteses", text: "palavra (queda, déficit, redução) ou hífen", colorAsOnlySignal: "prohibited"},
      locale: {ptBR: {thousands: ".", decimal: ","}, enUS: {thousands: ",", decimal: "."}, currencySymbol: "R$", sameCanonicalValue: true},
      crossMaterial: {
        identity: "valor canônico, unidade, escala, período, entidade e definição idênticos em todos os materiais da versão",
        permittedClassDifferences: {term_sheet: "money_contract_term", memo_teaser_qa: "money_material_text", model_and_tables: "money_statement_table", chat: "money_chat"},
        renderingCheck: "cada exibição é o arredondamento correto do mesmo valor canônico pela sua classe",
      },
      precedence: ["convenção do contrato ou do instrumento (policy.capital.anbima-b3-conventions)", "esta política", "formatação de idioma"],
    },
    unit: "casas decimais por classe de métrica",
    source: {
      title: "IBGE, Normas de apresentação tabular, 3ª edição (1993), seções 4.8 e 7; CPC 26 (R1), itens 51(e) e 53",
      url: IBGE_TABULAR_URL,
      observedBy: OBSERVED_BY,
    },
    asOf: AS_OF,
    documentation: `${CARD}#policy.material.numeric_rounding`,
  },

  "policy.qc.numeric_tolerance": {
    version: VERSION,
    value: {
      identities: [
        {id: "sources_equal_uses", rules: ["OP-02"], toleranceBrl: "0.00"},
        {id: "requested_amount_equals_uses", rules: ["OP-02", "MA-11"], toleranceBrl: "0.00"},
        {id: "debt_ledger_views_reconcile", rules: ["D-24"], tolerance: "0"},
        {id: "model_assets_equal_liabilities_plus_equity", rules: ["Q-17", "MA-27"], tolerance: "0"},
        {id: "model_opening_cash_plus_flows_equal_closing", rules: ["Q-17", "MA-27"], tolerance: "0"},
        {id: "model_profit_reconciles_equity_roll", rules: ["Q-17", "MA-27"], tolerance: "0"},
        {id: "amortization_principal_sums_to_face", rules: ["ES-06", "MA-17"], toleranceBrl: "0.00", residual: "última parcela absorve o resíduo de arredondamento previsto no cronograma"},
        {id: "cross_material_canonical_value", rules: ["MA-28"], tolerance: "0"},
        {id: "pt_en_economic_identity", rules: ["MA-29", "LC-07"], tolerance: "0"},
        {id: "definitions_annex_equals_analysis", rules: ["MA-21"], tolerance: "0"},
        {id: "term_sheet_memo_model_terms", rules: ["MA-12", "MA-17", "MA-27"], tolerance: "0"},
        {id: "version_fingerprint_matches_release", rules: ["MA-31"], tolerance: "0"},
      ],
      rendering: {rule: "número exibido igual ao arredondamento do valor canônico pela classe de policy.material.numeric_rounding", tolerance: "0"},
      roundedAggregation: {
        maxDifference: "0,5 unidade do último algarismo exibido multiplicada pelo número de parcelas",
        disclosureRequired: true,
        appliesTo: ["totais de tabela", "colunas de participação"],
      },
      reperformance: {
        monetaryComparisonPrecisionBrl: "0.01",
        monetaryToleranceBrl: "0.00",
        ratioTolerance: "0",
        limitComparison: "produtos exatos (numerador contra limite multiplicado pelo denominador), nunca quociente arredondado",
        iterativeRateToleranceFractionPerYear: "0.00000001",
        iterativeRateDisplayedValueMustMatch: true,
        scenarioOutputTolerance: "0",
        independentOracle: "cálculo em centavos por implementação independente do motor",
      },
      claimAudit: {
        materialNumbersWithMarkerShare: "1.00",
        orphanMarkersAllowed: 0,
        sourceToDisplayTolerance: "0",
        scaleConversion: "exata, antes do arredondamento",
        unsupportedMaterialNumber: "block",
      },
      coverage: {externalMaterials: "todos os números", internalAnalysis: "todos os números materiais (policy.financial.materiality)"},
      independence: {preparerMayStampQc: false, oracleIndependentOfEngine: true},
      sourceToSourceKey: "policy.reconciliation.tolerance",
      onBreach: {
        externalMaterial: "bloqueia a liberação (MA-32, carimbos 1 e 2)",
        internalAnalysis: "exceção nomeada com dono; correção silenciosa proibida",
      },
    },
    unit: "diferença absoluta na unidade da métrica; zero nas identidades",
    source: {
      title: "House Playbook v2.1, MA-28, MA-31, MA-32 e LC-01; padrão de informação suficiente, verdadeira, precisa, consistente e atual da Resolução CVM 160/2022, art. 24, § 1º",
      url: PLAYBOOK_URL,
      observedBy: OBSERVED_BY,
    },
    asOf: AS_OF,
    documentation: `${CARD}#policy.qc.numeric_tolerance`,
  },
};
