// GENERATED by pnpm --filter @offroad/credit-playbook manifest:generate. Do not edit.
export const specialistMethodRuntimeManifest = [
  {
    "procedure": {
      "id": "underwrite-receivables-pool",
      "version": "2026.09.06-v1",
      "maturity": "production"
    },
    "taskIds": [
      "R01"
    ],
    "requiredPackIds": [
      "analysis.receivables-underwriting"
    ],
    "bindingPriority": 100,
    "executor": {
      "module": "@offroad/receivables-analysis",
      "exportName": "underwriteReceivablesPool"
    },
    "resultContract": "method.underwrite-receivables-pool.v1",
    "sourcePath": "receivables/underwrite-receivables-pool.md",
    "sourceHash": "9f5cf24e6751c708a7ff9825afebdd1878e2e07fc652c295df7493cb8e246264"
  }
] as const;

export const specialistTaskCapabilityRuntimeManifest = [
  {
    "taskId": "R01",
    "executorKey": "@offroad/receivables-analysis#underwriteReceivablesPool",
    "executorVersion": "2026.09.06-v1",
    "procedure": {
      "id": "underwrite-receivables-pool",
      "version": "2026.09.06-v1"
    },
    "availability": "live",
    "exposure": "universal",
    "allowedUses": [
      "internal_validation",
      "customer_work"
    ],
    "allowedEvidenceRegimes": [
      "project_private",
      "mixed_governed"
    ],
    "allowedDataClasses": [
      "project_confidential"
    ],
    "allowedSourceClasses": [
      "project_context",
      "provided_documents",
      "house_method"
    ],
    "allowedProviderIds": [],
    "allowedToolIds": [],
    "providerRequired": false,
    "maximumEffect": "none",
    "allowlistedTenantIds": [],
    "allowlistedProjectIds": []
  }
] as const;

export const specialistMethodApprovalManifest = [
  {
    "procedure": {
      "id": "underwrite-receivables-pool",
      "version": "2026.09.06-v1"
    },
    "approvedBy": "Carlos Eduardo Galves",
    "approvedAt": "2026-09-10",
    "approvalSource": "instrução do fundador na sessão de coordenação de 10/09/2026"
  }
] as const;

export const procedureBuildProvenance = [
  {
    "schemaVersion": "compiled-procedure-manifest.v1",
    "procedure": {
      "id": "prepare-capital-structure-decision",
      "version": "2026.09.18-v1",
      "maturity": "candidate"
    },
    "source": {
      "path": "capital/prepare-capital-structure-decision.md",
      "hash": "98358ad2a0febcc675089d89639f79aaad31445bbf4b7a64f17c6365cf6b5882"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "authoringStatus": "incomplete",
    "pendingContent": [
      "Autoria profissional de regras, fórmulas, convenções e casos de referência.",
      "Contratos dos cálculos e executores de financial-core.",
      "Revisão e aprovação humana antes da publicação."
    ],
    "grantsExecution": false,
    "budget": {
      "maxModelCalls": 0,
      "maxDurationMs": 1000,
      "maxCostMinorUnits": 0,
      "currency": "BRL"
    },
    "allowedTools": [],
    "maximumEffect": "none",
    "components": [
      {
        "component": {
          "id": "capital.decision-framing",
          "version": "2026.09.18-v1",
          "title": "Enquadramento editorial da decisão",
          "inputs": {
            "id": "capital.framing-input",
            "version": "2026.09.18-v1",
            "value": {
              "type": "object",
              "fields": {
                "question": {
                  "required": true,
                  "value": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "outputs": {
            "id": "capital.framing-output",
            "version": "2026.09.18-v1",
            "value": {
              "type": "object",
              "fields": {
                "scope": {
                  "required": true,
                  "value": {
                    "type": "string"
                  }
                },
                "gaps": {
                  "required": true,
                  "value": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "dependencies": [],
          "tools": [],
          "effect": "none",
          "budget": {
            "maxModelCalls": 0,
            "maxDurationMs": 1000,
            "maxCostMinorUnits": 0,
            "currency": "BRL"
          },
          "rights": {
            "inheritSourceRestrictions": true,
            "purposes": [
              "decision_support"
            ],
            "sourceClasses": [
              "authorized_context"
            ]
          },
          "competencies": [
            "capital_structure",
            "financial_analysis"
          ],
          "invariants": [
            "law",
            "contractual_definition",
            "traceability",
            "verification",
            "access_barriers",
            "deterministic_financial_math"
          ],
          "overridePoints": [],
          "evidence": [],
          "kind": "narrative",
          "text": "Enquadrar a pergunta e registrar lacunas materiais sem exigir companhia ou intake. Este componente editorial não calcula, não executa ferramentas e não autoriza publicação."
        },
        "componentHash": "a51e25a7a2eb5b894deee7bb122f3d9c3fb90d0e33361d1bad7def082da4c6a3",
        "executor": null,
        "evidence": []
      }
    ],
    "manifestHash": "47584b99c5446cf95428eab9b838cee55d3b77a1a8b025726ca67d6e531383a7"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "build-debt-ledger",
      "version": "2026.09.05-v15",
      "maturity": "implemented"
    },
    "source": {
      "path": "financial/build-debt-ledger.md",
      "hash": "4de8c03356c3441ff145d2bc7c99bf5d7f7f573411b39a5fcad0cf756cf22ead"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "79f3b7b8dc8c260b8fc57e5819f0348874f03e81d6cdf16d0ee226738c75a0d8",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/build-debt-ledger",
      "exportName": "buildDebtLedger",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/build-debt-ledger.test.ts",
        "hash": "9a9aa31f9e062e0ff603d25b96908b367e0ab96bf8dd0ba3c9357a1a3ad49533"
      }
    ],
    "manifestHash": "e1e518673b8a296f7a6076882f6d7387db7a32132276cffb8c7535f15efd0b82"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "build-interest-and-indexation-schedule",
      "version": "2026.09.05-v7",
      "maturity": "implemented"
    },
    "source": {
      "path": "financial/build-interest-and-indexation-schedule.md",
      "hash": "31ecf5116ffed5f8f3b462ca70b46a7afd99bbfd625acbe2975294642890d15d"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "6364b4ea243d5c168f8b8c54e0ca8cad9c272e9950cd5855a66a81989770330d",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/build-interest-and-indexation-schedule",
      "exportName": "buildInterestAndIndexationSchedule",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/build-interest-and-indexation-schedule.test.ts",
        "hash": "4d92040831baf6f3ce75fe498929de89aa850d3d497c9013aafc6e1f8ca02685"
      }
    ],
    "manifestHash": "05b0b14f35101260bfb8cf28f5e25e46b1cec82f4278e7f58cd8b6d7c02b269e"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "reconcile-covenant-definitions",
      "version": "2026.09.05-v14",
      "maturity": "implemented"
    },
    "source": {
      "path": "financial/reconcile-covenant-definitions.md",
      "hash": "e66ff3415c454bcfe1f83d876b75f5e2d4549743ebd8af7f9cc726ae5bbdabfd"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "6e661629c022155da1631be5ef572337cadd32cfc1d67b50ec3be749ae06df7c",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/reconcile-covenant-definitions",
      "exportName": "reconcileCovenantDefinitions",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/reconcile-covenant-definitions.test.ts",
        "hash": "03470380a643dad767a765ec0d06875bf48ce0da0b4bce57053caf83ebf8a6b4"
      }
    ],
    "manifestHash": "403e59219b85eb1075526fcedfa62f4b4f8b4582fb48395ebc2936307d791af1"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "reconcile-financial-statements",
      "version": "2026.09.05-v9",
      "maturity": "implemented"
    },
    "source": {
      "path": "financial/reconcile-financial-statements.md",
      "hash": "850274016f35d1273e56d1d672f51b6c81a38b7226a2eccf0a612c17a6999f87"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "59239ddb82f3ec8ef19b7d3efce99226f0cac024a9695ea13e9f3c54911691d6",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/reconcile-financial-statements",
      "exportName": "reconcileFinancialStatements",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/reconcile-financial-statements.test.ts",
        "hash": "a08f291c6583f230b7a3a88848f4ccab014f065de0ae1867b671070575c30e05"
      }
    ],
    "manifestHash": "e26dd1adb5134c76557917ceef62a4db15b5761c1f36849004f21a73bbf859c0"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "plan-meeting-brief",
      "version": "2026.09.05-v7",
      "maturity": "implemented"
    },
    "source": {
      "path": "materials/plan-meeting-brief.md",
      "hash": "5db9dbc658da621ffa2025906461740a184a265b3fb21e43930b74c65693e23b"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "b7d5d41121e051a3147a3ffc3858187b385d2edb5e0ef97d118a0b42db35fd6b",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/plan-meeting-brief",
      "exportName": "planMeetingBrief",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/plan-meeting-brief.test.ts",
        "hash": "19834e22ea2a03cc6d1273fdff2a3fc58da3fdd148bc0219f8e6f4d9ac042567"
      }
    ],
    "manifestHash": "9cfb5dabd6847d2faa7629e5e7f650087962f82f927baecc99b521daf7408fbe"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "write-meeting-synthesis",
      "version": "2026.09.05-v1",
      "maturity": "implemented"
    },
    "source": {
      "path": "materials/write-meeting-synthesis.md",
      "hash": "0ed232f44132ee34e18d4e6ada078d8304415c6b6f82e332032ec86fc3d9f7ca"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "495babe03478b0f2d1ebe7eed8091b9b78dd530eeb57e997d89fda025745a28d",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/preview/synthesis",
      "exportName": "synthesisSkeleton",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/preview/synthesis.test.ts",
        "hash": "7301ff06438a26a3b90964577b0292d71cfb456e313e91e2c2b6bfa5c5bdf06d"
      }
    ],
    "manifestHash": "8767281108b459c6801374adf65792bd7a1559612aebd80fe88023adf3c7107f"
  },
  {
    "manifestHash": "17ee80ac7cd3ac22b8c0d5d90893cf89ad67eb129ad1fe1b6f26aa3b73d6d090",
    "procedure": {
      "id": "underwrite-receivables-pool",
      "version": "2026.09.06-v1",
      "maturity": "production"
    },
    "source": {
      "path": "receivables/underwrite-receivables-pool.md",
      "hash": "9f5cf24e6751c708a7ff9825afebdd1878e2e07fc652c295df7493cb8e246264"
    },
    "compiler": {
      "hash": "757a3e46d1fc3fd4225e0f91e3302759bd59bb2aae5a3390a8a4db9b55c6bf2e",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "38dacf680a45fc8e55dc2a862fa8cf950e6b34d626b485a85bc088b997decaec"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "9c58538e770b8ae181c088a42ba33a5456fbbc112eda3188b9898c084464df5b"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "version": "2026.09.18-v1"
    },
    "executor": {
      "sourceClosureHash": "37ed5a9a2253f25e3c2b8d79d0e9cabf92c76e9bb3d06a74e52380d164c7e9e6",
      "module": "@offroad/receivables-analysis",
      "exportName": "underwriteReceivablesPool"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/knowledge/reviews/runs/underwrite-receivables-pool-2026-09-10-adversarial/run.json",
        "hash": "c28b9da4748cadeafaa1d3e66f6c4bec18f0bd3e4734c09e9d270347a058c99c"
      },
      {
        "path": "packages/credit-playbook/knowledge/reviews/runs/underwrite-receivables-pool-2026-09-10-consistency/run.json",
        "hash": "4b7a1f6ee4aa6bcfa2e2e57cce17389288645862f5527ed9ff2d0d98c15e8e2c"
      },
      {
        "path": "packages/credit-playbook/knowledge/reviews/runs/underwrite-receivables-pool-2026-09-10-gold/run.json",
        "hash": "47686335ebeedd9a0a651019d617963765162afd8119c3b1cbf2f2b81a330833"
      },
      {
        "path": "packages/credit-playbook/knowledge/reviews/underwrite-receivables-pool-2026-09-10-independent-review.json",
        "hash": "829490e6200a23a7b62736706e3c7655ff5d81cc36ff980b06541a8d36a09e01"
      },
      {
        "path": "packages/receivables-analysis/src/underwrite.test.ts",
        "hash": "511f0c30353dc6c0c2d038d7f7738e9f7cb566ab827b8a373d7ee5d773f7e2b7"
      }
    ],
    "schemaVersion": "legacy-procedure-adapter.v1",
    "adapterHash": "caf448f8e194522a4fed02a967098ae8da0b6a6cb0ea22995c4b15d3e5c5d288",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ]
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "compare-refinancing-before-after",
      "version": "2026.09.05-v7",
      "maturity": "implemented"
    },
    "source": {
      "path": "refinance/compare-refinancing-before-after.md",
      "hash": "12a93d3b1640e3d870e0144b80baa91ec83cf070d02af3977308794d62d89df5"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "18e19567239919fcf991c4462a77dc997d923ab0b72704f42ea35f01928dbf4a",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/compare-refinancing-before-after",
      "exportName": "compareRefinancingBeforeAfter",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/compare-refinancing-before-after.test.ts",
        "hash": "73d58853572afac424bd7323a662568c8e46ee09ea4e233ca4848c4310a10f52"
      }
    ],
    "manifestHash": "9e18b04d68d1af82fd2eb846649bc2220ec2e9949745bbd307ac263cd631f104"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "diagnose-maturity-wall",
      "version": "2026.09.05-v8",
      "maturity": "implemented"
    },
    "source": {
      "path": "refinance/diagnose-maturity-wall.md",
      "hash": "58ea948ced9e36c8f8fa0987bb1c1efe3ff5691984aa6ba54cf739d257e903da"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "0c32ca0c53b50e0f9cd811c43dbcb0ed3791b21039a662e123f0c9e530c0a225",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/diagnose-maturity-wall",
      "exportName": "diagnoseMaturityWall",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/diagnose-maturity-wall.test.ts",
        "hash": "15feca2fb00f7cadae3efffc27cc399b2e20b0e7bddd92f3a7a727ce8147b7fa"
      }
    ],
    "manifestHash": "ca724c7ba0587df86f8e3ec5e3070824eabd0a39d256d2bda5e6e0e3afd48b98"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "estimate-exit-cost-by-series",
      "version": "2026.09.05-v8",
      "maturity": "implemented"
    },
    "source": {
      "path": "refinance/estimate-exit-cost-by-series.md",
      "hash": "d68da65e036b6080dea53033eeec1f3f645d4fa6ea619515bdae158bc3970f0b"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "d5c086654076080458f702b19105765e1a5052b5945a38a94ac674bbe82fac07",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/estimate-exit-cost-by-series",
      "exportName": "estimateExitCostBySeries",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/estimate-exit-cost-by-series.test.ts",
        "hash": "801eea7f0fa061c88f76f0cdd7681746b2af3dc3d9c56ee6fc7bc662666c6a5b"
      }
    ],
    "manifestHash": "d44530e38df8116bd0b096bde769d6efc6b077f1ed9cdc575c9c2bf063d6b4f8"
  },
  {
    "schemaVersion": "legacy-procedure-adapter.v1",
    "procedure": {
      "id": "declare-scenarios",
      "version": "2026.09.05-v6",
      "maturity": "implemented"
    },
    "source": {
      "path": "scenarios/declare-scenarios.md",
      "hash": "547c04a7db74de7e66780431f164fdd0423007d5cc6361dd3a4a1cc11da73618"
    },
    "compiler": {
      "version": "2026.09.18-v1",
      "sources": [
        {
          "path": "packages/credit-playbook/src/build-method-manifest.ts",
          "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
        },
        {
          "path": "packages/credit-playbook/src/method-component.ts",
          "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
        },
        {
          "path": "packages/credit-playbook/src/procedure-compiler.ts",
          "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
        },
        {
          "path": "packages/credit-playbook/src/procedure-contract.ts",
          "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
        },
        {
          "path": "packages/credit-playbook/src/procedure-markdown.ts",
          "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
        },
        {
          "path": "packages/credit-playbook/src/released-method-lock.ts",
          "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
        },
        {
          "path": "packages/credit-playbook/src/review-record.ts",
          "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
        },
        {
          "path": "pnpm-lock.yaml",
          "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
        },
        {
          "path": "tsconfig.base.json",
          "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
        }
      ],
      "hash": "175dfe462204c0b1be17ef45d7259c9a7459e09ec45d1a3965f332b627e9388a"
    },
    "adapterHash": "188b796cf9665f6b08d8e5e81d6634b2ecd11bf37452a79f0bdf2904dd2ff66d",
    "compositionStatus": "legacy_contract",
    "grantsExecution": false,
    "pendingContent": [
      "typed component contracts require explicit authorship"
    ],
    "executor": {
      "module": "@offroad/credit-playbook/executors/declare-scenarios",
      "exportName": "declareScenarios",
      "sourceClosureHash": "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd"
    },
    "evidence": [
      {
        "path": "packages/credit-playbook/src/executors/declare-scenarios.test.ts",
        "hash": "ad57c9153addb67a306702ec35c7176c8e8328142a18603a6057b4db3b26e858"
      }
    ],
    "manifestHash": "05a4fc203ac0bbddb5f90d72c0b87c07e516c2b8c198f3cfa9d6e67d95c010f8"
  }
] as const;

export const procedureExecutorSourceClosures = {
  "83412cff2e25ad30fb9fdbd0f8670e8e82ebd6745144103edd277102ae3d17fd": [
    {
      "path": "packages/credit-ontology/package.json",
      "hash": "0f5f1ce7ae6f0ebb97b751c230cd6a3799abb49b5620c73454a78e90d09e7dc1"
    },
    {
      "path": "packages/credit-ontology/src/chart-of-accounts.ts",
      "hash": "ce12cce21839f11c15366987f1a2391931d0da75f51e09c570c930b65ab07e38"
    },
    {
      "path": "packages/credit-ontology/src/debt-mission.ts",
      "hash": "6341a764d6649ead201b2ce5a807211ac367a2514d7a81151e7f1728bdc76b2b"
    },
    {
      "path": "packages/credit-ontology/src/definitions.ts",
      "hash": "4f0c37c9842f56f72ce2ade3e59a119bbbdce59f3c685f5e9bb761d2b1e4bb02"
    },
    {
      "path": "packages/credit-ontology/src/documents.ts",
      "hash": "1e944f970aaffc91faa9857a32c7b49f52a6ce18abec3efcc24ed2954605dfd6"
    },
    {
      "path": "packages/credit-ontology/src/evidence.ts",
      "hash": "2cef11c2ea98880b9154feb11d9e3c17fed9576f12903786497b3ab0e495252f"
    },
    {
      "path": "packages/credit-ontology/src/fields.ts",
      "hash": "fd23911260194a8765f4efa8d1de41218315a8fd5185ed5f1d3876c606fe65d7"
    },
    {
      "path": "packages/credit-ontology/src/index.ts",
      "hash": "d196ba728826f9250825b132f47535acb1ed0cab762ac832891feab58c8f1956"
    },
    {
      "path": "packages/credit-ontology/src/jurisdiction-language.ts",
      "hash": "a636ce736aad9d5490a24192472b128603cb2dcb50abc897c43210643acb4c57"
    },
    {
      "path": "packages/credit-ontology/src/materiality.ts",
      "hash": "2ed3b46966c1a04c8c4e0b317a9c0fefb93efaf247fb23735f7e6c6fffe7afd9"
    },
    {
      "path": "packages/credit-ontology/src/origination-taxonomy.ts",
      "hash": "7c6dff3662ca1dbd9d41657785c5c9443c9351a3fb5fe506472e762d4cb6651d"
    },
    {
      "path": "packages/credit-ontology/src/periods.ts",
      "hash": "cd8ea27cf2fc83870c4961e522c80c178ae37caa8a4d8b8df08550e050e7d853"
    },
    {
      "path": "packages/credit-ontology/src/reconciliation-rules.ts",
      "hash": "61fc0d7db133ff2d1c309ce8750733b5bb4862a0aceda2efdce9ada8dfb4518f"
    },
    {
      "path": "packages/credit-playbook/package.json",
      "hash": "aa33ecd8fda97fb2d0f55d7a55ced1c154650727069ad441629dc6d7a572587d"
    },
    {
      "path": "packages/credit-playbook/src/archetypes.ts",
      "hash": "6ffdb4c0d217d22fc65488eb52a501d7555cba636780c5b03d5bc648225004e1"
    },
    {
      "path": "packages/credit-playbook/src/build-method-manifest.ts",
      "hash": "1396763fdbffba083c233e4cd7ad9df1b60d7457dd9785925e0bcddf9357cfea"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/build-debt-ledger.ts",
      "hash": "f27ba938e2eb8b91cae89f607d4fef24e1f3fc4731b45039fbbf1c638be0a70b"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/build-interest-and-indexation-schedule.ts",
      "hash": "7dc9579cfd320527dc5411afb472847adaa9d22048c7c249041f07ca85da4915"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/compare-refinancing-before-after.ts",
      "hash": "8f1b139160944b19511236a56194f2a3a618550562becf36f78ebc56607221fb"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/declare-scenarios.ts",
      "hash": "97a34345c3208a651048a3e4255ad980ad0995b2b7c9e40ed0b0eb721d8b57e6"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/diagnose-maturity-wall.ts",
      "hash": "877d9910beaafda5acd5250d3a1f13b65f7e026781360a01d62db0eddb6522ac"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/estimate-exit-cost-by-series.ts",
      "hash": "6c258de7b7f99edb0d2ae51224b662b79a3177c989782594fd54ae97f220cf53"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/index.ts",
      "hash": "5710c3b17ceef51e3b992009536963cb3feae2a0f34aa385d888409554f2076f"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/plan-meeting-brief.ts",
      "hash": "61cd0e513ef681039c3cd667361838d227d0b95fe13a934685ac3f87b3f61b30"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/reconcile-covenant-definitions.ts",
      "hash": "97e0aa2e8eea221c69ef88e13dab527bcd2a773769bd40ace521a45585475301"
    },
    {
      "path": "packages/credit-playbook/src/cases/gc01/reconcile-financial-statements.ts",
      "hash": "87bd8e654a502bf194ce287107cf86185766fc07c7b21193e229c08e0d18a412"
    },
    {
      "path": "packages/credit-playbook/src/client-requests.ts",
      "hash": "fff58fcfd52979c700fa0eff2b5550b9ce4e3a11bf2b0d0fb06c9b36e788e26f"
    },
    {
      "path": "packages/credit-playbook/src/closing.ts",
      "hash": "b0f5576ecd0be8971f71a5ccbb1e9d180eb3395d278a2abdfbec0bffef4923a2"
    },
    {
      "path": "packages/credit-playbook/src/compose-method.ts",
      "hash": "dae1bec7b1a5638e1a50664a16b4ff2d74a6594cf02a172116452ad7857799fb"
    },
    {
      "path": "packages/credit-playbook/src/conduct-policy.ts",
      "hash": "4f12b3ccdca883dae2f2401700c9c6a0e2dafccd6dc371388ac58457db76e77b"
    },
    {
      "path": "packages/credit-playbook/src/covenants.ts",
      "hash": "a0d37161dd387b84559facea1b1c4ef14f9707266a1910df184a498cf97fb160"
    },
    {
      "path": "packages/credit-playbook/src/dcm-blueprint.ts",
      "hash": "74e7cd95066a27ce9ba8a39573dc7f7d6c8077140117ebd253fd6dfda5a19295"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/economic-catalog.ts",
      "hash": "5c91d37dc29e2f1a78cee85649aa8274ea851bc114a8c0b6f375a26c689f4018"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/index.ts",
      "hash": "55e47aef3157aa60e6447607a7f576f941570f9424568164248223e988b63549"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/registry.ts",
      "hash": "1bf92f8e52fdea671353eef5fe90a7b3f5a46d09d332a1dc33a14cb2ff79164c"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/sector-context-catalog.ts",
      "hash": "5be72c3b2264c9af5bfdf47b5eefdec03c6639538915c9786b59f074da9a589f"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/sector-context-labels.ts",
      "hash": "ed5a35ef1d68f717a97b8ba60952a9bf96e4ccbb42aaf7b762e057ef715be1ce"
    },
    {
      "path": "packages/credit-playbook/src/depth-packs/types.ts",
      "hash": "bca473dcdbf328bf1805113acc800ed7fb2ad0f5552136005dd27107494389c4"
    },
    {
      "path": "packages/credit-playbook/src/executors/build-debt-ledger.ts",
      "hash": "09af05824f142286f48384e8eedae17f25c4725fc2e28a76adb6c7a3b4aaaa62"
    },
    {
      "path": "packages/credit-playbook/src/executors/build-interest-and-indexation-schedule.ts",
      "hash": "9dc6ffd4a247f515d09f4ee13c30efcf27bed202e0b43c04101049639067112d"
    },
    {
      "path": "packages/credit-playbook/src/executors/compare-refinancing-before-after.ts",
      "hash": "b49d517224611ecfecc8517752c52815dbadc7dd3cc96e2b2021c78780b65cfb"
    },
    {
      "path": "packages/credit-playbook/src/executors/contract.ts",
      "hash": "f852298c242f1dbd74b8042b305f5247e0768cb94ed9020d6b847ad4e65ec7ae"
    },
    {
      "path": "packages/credit-playbook/src/executors/declare-scenarios.ts",
      "hash": "9c0823b8da3e064a75cb859f1b9ac460fb550ea8facafbbb3a608185fdaf1701"
    },
    {
      "path": "packages/credit-playbook/src/executors/diagnose-maturity-wall.ts",
      "hash": "2381b482ab3e82045bddaf842b92c2d5a59a53f9e0686cf482a0e27d6f77f728"
    },
    {
      "path": "packages/credit-playbook/src/executors/estimate-exit-cost-by-series.ts",
      "hash": "13f4cdc667c987a63310e41dc3c313ee6faa4f6793c2e35434dec961f4e9bda7"
    },
    {
      "path": "packages/credit-playbook/src/executors/index.ts",
      "hash": "1ed462364258cd645f442c5d1c8bbcb6fb096e2cc04eaa9061a13829adb8879d"
    },
    {
      "path": "packages/credit-playbook/src/executors/plan-meeting-brief.ts",
      "hash": "23885dc15a89ae2869c3b52bb750c1c6a11ef9abcabcc358618ea8e100cc2c33"
    },
    {
      "path": "packages/credit-playbook/src/executors/reconcile-covenant-definitions.ts",
      "hash": "bed1f1aca83e3bdbfcb51d2180589258316f457fbc15b5ab539a3fc9cbd8299a"
    },
    {
      "path": "packages/credit-playbook/src/executors/reconcile-financial-statements.ts",
      "hash": "e3ae56a24ba2622c696ba6f270afc42116db15ced08097f88e0113d7ce131080"
    },
    {
      "path": "packages/credit-playbook/src/house-playbook/index.ts",
      "hash": "94c705a2a225059c072c765f7075666e840f0a9286a8fa32b886b90a58f68edd"
    },
    {
      "path": "packages/credit-playbook/src/house-playbook/source.ts",
      "hash": "6b048d706a3033e0d20f8385e03c3bd02292b3fc8cfb8e04159b17923fe5f8f1"
    },
    {
      "path": "packages/credit-playbook/src/index.ts",
      "hash": "bf74e04b3eed0be7e42d3ca8b603660c9abedbc86e9b241886c90677ca209b8a"
    },
    {
      "path": "packages/credit-playbook/src/instruments.ts",
      "hash": "10edd5cc2e6effb20755b2b1a2410c9a99091eaf179cc895f320f8c8d1fe5b2a"
    },
    {
      "path": "packages/credit-playbook/src/intake-state.ts",
      "hash": "5514fd8572ad4092c3ce33bc7571de9ce8f810d920057348cfea23a0d4334099"
    },
    {
      "path": "packages/credit-playbook/src/material-fields.ts",
      "hash": "42ad3e0475aefebfa12dc77847fd730a86ce5b2d24c0996c1aab8580e0eb5230"
    },
    {
      "path": "packages/credit-playbook/src/material-templates.ts",
      "hash": "62b6160ed664626ecc9545d4845cd9331c72e4c94bbbc93d81c60a04681e7cb7"
    },
    {
      "path": "packages/credit-playbook/src/method-component.ts",
      "hash": "50a0dc0769ce9bd9d6f909f2a7242d69ed63bcd00e62850772b007ee37dd74e0"
    },
    {
      "path": "packages/credit-playbook/src/method-run-record.ts",
      "hash": "7b1e70301b5d68a18b3d14f568eb86ed15e710ebcd4fce45e9dd416d74280953"
    },
    {
      "path": "packages/credit-playbook/src/method-runtime-manifest.ts",
      "hash": "790e132503ff43e9a393bea05765d3434841f00d527654423929dcf27516c9ad"
    },
    {
      "path": "packages/credit-playbook/src/methodology.ts",
      "hash": "571feb777827a99b1de86e69d4106081854a1922c4e3ae1b38358749e933cfa7"
    },
    {
      "path": "packages/credit-playbook/src/platform-method-publication.ts",
      "hash": "cb3d9426e344a2c18cf65e0a84137fe6a2e929691c54ad266820eda5fde6d57e"
    },
    {
      "path": "packages/credit-playbook/src/preview/corpora.ts",
      "hash": "7925be0c13b9837317f99acf34d96f6a0f59599defd306604f80cdcaf2dfffc7"
    },
    {
      "path": "packages/credit-playbook/src/preview/gaps.ts",
      "hash": "fe9000275c4312dc52c6cc98f0dbffd351db0f5c57cfade9ce871282ca1d4ddc"
    },
    {
      "path": "packages/credit-playbook/src/preview/index.ts",
      "hash": "10764eae9bacd623acd73c89e618884a74a72268051242ea6be99b2d991e8969"
    },
    {
      "path": "packages/credit-playbook/src/preview/run.ts",
      "hash": "8e38c203c8a0918af4772bed0f9abab91fb2fdb52c5ee8ddfbea3c0cbb7114ab"
    },
    {
      "path": "packages/credit-playbook/src/preview/synthesis.ts",
      "hash": "49d1fccfe92b5c3656649a0f22983addb2f2035215d9599596b62bc7849919d8"
    },
    {
      "path": "packages/credit-playbook/src/preview/workflow.ts",
      "hash": "f10f268a41bd9a7c3fcdebebdddbb2117bee5e59a50706496b8251c07e1972cd"
    },
    {
      "path": "packages/credit-playbook/src/procedure-compiler.ts",
      "hash": "f33177013196299df7c1345ed030b4af548fc815978b0c8ca639936620d8e93a"
    },
    {
      "path": "packages/credit-playbook/src/procedure-contract.ts",
      "hash": "a5d53552cb262804d32573ee5d954cf5b225dc605851cc1d76cea19be29f70c7"
    },
    {
      "path": "packages/credit-playbook/src/procedure-markdown.ts",
      "hash": "e4a0b52163edbdfe7d7ed3e8b0f4dd34ca9415628fd1e48b768cb1285b8ebf21"
    },
    {
      "path": "packages/credit-playbook/src/procedures/documentary-work.ts",
      "hash": "684c614b9d00738c2eb08b622ea53774ae4892ebd490548d9149959f9193dbaa"
    },
    {
      "path": "packages/credit-playbook/src/procedures/executive-synthesis.ts",
      "hash": "8a3defc67c1ae8f3fa0665e3e37d96505877b9ba3c88a65254a73f282e171d79"
    },
    {
      "path": "packages/credit-playbook/src/procedures/financial-debt-truth.ts",
      "hash": "e3c2a521d9ad376dca640b29bb658370325fc35008433e4a4f728d5828dbb00f"
    },
    {
      "path": "packages/credit-playbook/src/procedures/growth-capex.ts",
      "hash": "bdd03a96360e85c23c65043a0ba4aa01e36d7e33006f9302cdcf4fedd83ad799"
    },
    {
      "path": "packages/credit-playbook/src/procedures/index.ts",
      "hash": "d83b2c723602a7d2af1893611d1cb5715ec7c591857c65f1dfd82f1ad02d6cd2"
    },
    {
      "path": "packages/credit-playbook/src/procedures/institutional-input-requests.ts",
      "hash": "be602bbfa88f329ab4e91f0ae770a5775309a3445f4ef771f5c48c457688ea53"
    },
    {
      "path": "packages/credit-playbook/src/procedures/language-conduct.ts",
      "hash": "4e179f01051fcfc59499cdb9eae3887d482b74782e80d2510bda03c056956f23"
    },
    {
      "path": "packages/credit-playbook/src/procedures/market-distribution.ts",
      "hash": "8fa0adc04429ed343ee4fca65db8729ec66d48053cddda78a2a4f7f64f7d4e73"
    },
    {
      "path": "packages/credit-playbook/src/procedures/materials.ts",
      "hash": "2a33853f400f0c6236bbee2c80a9e506149427d867ffeee8094e15576d1f50e7"
    },
    {
      "path": "packages/credit-playbook/src/procedures/operation.ts",
      "hash": "e2b9bdfae6f3c236fd28b309d11ed196a7940b8c44a809eb4f2de9efe199d33c"
    },
    {
      "path": "packages/credit-playbook/src/procedures/pricing.ts",
      "hash": "aeec0ffb1a33a431f4381eb70c2a25b1a03d44e8f1e50a8d60f6990a33b8f56d"
    },
    {
      "path": "packages/credit-playbook/src/procedures/provider-research.ts",
      "hash": "6853de1106cb822cd2f6b013c96409025112d48c9eaa8ef5fc070bc7ecb83c28"
    },
    {
      "path": "packages/credit-playbook/src/procedures/red-flags.ts",
      "hash": "a2e477e26bf6bc27873d9b0dd6f74cb684e1f1b5699903ce09d6bd0abe7e3af7"
    },
    {
      "path": "packages/credit-playbook/src/procedures/registry.ts",
      "hash": "664e7359ebfe2c3e0c79d48d34fae67cc3e05a349e7992985e10d815016b8ea9"
    },
    {
      "path": "packages/credit-playbook/src/procedures/structure.ts",
      "hash": "9677ad020cc16e42e1e17eceb0d9932193f36856d42b3efaddfaffeafc376070"
    },
    {
      "path": "packages/credit-playbook/src/receivables-evidence.ts",
      "hash": "0cdae78b869f60dcd279d0e1e918e33be9bbda0103f93e3e35281da4acf5f10d"
    },
    {
      "path": "packages/credit-playbook/src/receivables-routes.ts",
      "hash": "891db9a5d001cbfd79039f9c672bede7c2d267a0ca1a8e4a34423b088cfe35a0"
    },
    {
      "path": "packages/credit-playbook/src/reference-data.ts",
      "hash": "446f22d7163f371ec027add910f411c95398be467a8cf72233bbc446190f55ae"
    },
    {
      "path": "packages/credit-playbook/src/released-method-lock.ts",
      "hash": "df4d078ef50c1a80324cb80e573833638b4c09e8f85de6da73f163b47a8adc2d"
    },
    {
      "path": "packages/credit-playbook/src/review-record.ts",
      "hash": "d44342d3d38509c2a616b737e4d9f79e151305a35b918ce2e0dc9d3de5cd013a"
    },
    {
      "path": "packages/credit-playbook/src/sufficiency.ts",
      "hash": "00837473003a0a3ea36e1d90c49b41a11ad8d6676e27aa0fa2eafea7e1e99d26"
    },
    {
      "path": "packages/credit-playbook/src/taxonomy.ts",
      "hash": "5a63b77662e9eb05d2e4200a4fc9d7d5affb16114eb3771141140368a20ab142"
    },
    {
      "path": "packages/credit-playbook/src/types.ts",
      "hash": "d3171c9b4d4f059132f21e406d5e8d49e65e1c7e9961d1ae4b41a73cff48d58e"
    },
    {
      "path": "packages/credit-playbook/src/workflow-recipe.ts",
      "hash": "4431580abc618c004d5dcfde6927e9e7056d6d682e26a55c2716831bab10ea02"
    },
    {
      "path": "packages/financial-core/package.json",
      "hash": "69f2268dfae2fe6e8f5e0c33a05f68dd8e509f68ff77c21348e5ba906a1ac008"
    },
    {
      "path": "packages/financial-core/src/assumption-unit.ts",
      "hash": "2fec9fdf4fa0e6d01431a07060cd0d588f81a4653d125db631acab622dfff35f"
    },
    {
      "path": "packages/financial-core/src/capital-period-cash.ts",
      "hash": "109415edd6d68e0e32a2642d06e75c71c47435081e88be9221bff40023f65e99"
    },
    {
      "path": "packages/financial-core/src/dated-debt.ts",
      "hash": "9179d053d832d254141e5f34f117003b36fb8b0d7ccf1fa8959a0ad9b7e7ddf7"
    },
    {
      "path": "packages/financial-core/src/defined-ratio.ts",
      "hash": "c3da7f27c21124bb12359ebe18066d6087d7f977583b40aa5562b910195490e5"
    },
    {
      "path": "packages/financial-core/src/depreciation.ts",
      "hash": "ea9bd8b4f1024d3472d85f35039b8ed72c8bcde9cc5c82b3f97f70fec0ae275a"
    },
    {
      "path": "packages/financial-core/src/financial-truth.ts",
      "hash": "a0c80b192ca540b8fbd301a621d8e5c82554e1055e3f3231dc0f0d2da659014c"
    },
    {
      "path": "packages/financial-core/src/financing-costs.ts",
      "hash": "486c36ec67fc959853576e5b5dce770daa60dfb880757773654dfbba4a51da60"
    },
    {
      "path": "packages/financial-core/src/index.ts",
      "hash": "bc0a6cf5d46a46539a3950a1336d31c4c5b5944140398c2386938b8257c51fce"
    },
    {
      "path": "packages/financial-core/src/indexed-debt.ts",
      "hash": "08da19742a8adeab327d5f4636887b2a32329f9b1b10df0f236967d74ae9c898"
    },
    {
      "path": "packages/financial-core/src/liquidity-calendar.ts",
      "hash": "739763b3720c7ceddbb3ba7050019be7daf68d5ae8ea670846368f0271d43672"
    },
    {
      "path": "packages/financial-core/src/numeric-representation.ts",
      "hash": "4db114f1ac6285ea7fa42257ac7f0ee6ea6ca1e589606de55ca901deae2a9cee"
    },
    {
      "path": "packages/financial-core/src/operating-cash-projection.ts",
      "hash": "45313d1aa916289ae59adafffdb8dd91b9f015ff13320d0d5ba400a77116aa4a"
    },
    {
      "path": "packages/financial-core/src/operation.ts",
      "hash": "24e18ea3471e7b26d60d5b2c323fcf001e5fcb2d86d5310996e2f4f1854b9d05"
    },
    {
      "path": "packages/financial-core/src/receivables/contracts.ts",
      "hash": "96c8f29dbc763ada38909538a25b67e849b4f19592459e712c77f215893036b7"
    },
    {
      "path": "packages/financial-core/src/receivables/dynamic-metrics.ts",
      "hash": "cd6fa83a9db894a4919ed645875f6fd61a5452ec336c9d531420d550c3d3ed51"
    },
    {
      "path": "packages/financial-core/src/receivables/eligibility-allocation.ts",
      "hash": "e6d668815a3602d96b565234b58fb3aefbaab72f5fb5d3867af44577ac47606b"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-borrowing-base.ts",
      "hash": "c11cd74e99bb375e56c058beaa48586a1a67b7beedf2630012efdd986825a2cb"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-concentration.ts",
      "hash": "ca17f9c2ee483dccc4c7dde3338b35a6200a20c6609edbc83cd5748457576167"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-eligibility.ts",
      "hash": "fd0b6f9fdade3372e0f3822119148d905a09a42bc14bd0301c6ebe9c078dc600"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-performance.ts",
      "hash": "219e4a1b8d1b0e3729ce2d1a8660ef85a23202e924bb19bd0bf7f5b03f7b9e63"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-reconciliation.ts",
      "hash": "887e8f1bb3cc8ad8460b08ddf1f826ba0cd0d5919b5d3ffed24d21bc8d59a6bc"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-shared.ts",
      "hash": "ec9689cf119841652ba0fff48f185df2e7cd7a3d8936a10bda76ab7f5caff7ed"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-triggers.ts",
      "hash": "cd44019e6800c7f67cade698e2238852d7746852c3f4b6e807fb17bf9886d16a"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-waterfall.ts",
      "hash": "27c877893caaf92ae4881dcfdc2919110d7845cdf29b9fc301a8a961015a13ae"
    },
    {
      "path": "packages/financial-core/src/receivables/provider-allocation.ts",
      "hash": "4c66699982526e2186d16e57a77290f2fd08ea1b7c4e334feb123dc7cfb1ff84"
    },
    {
      "path": "packages/financial-core/src/receivables/static-metrics.ts",
      "hash": "31af3414353b30419945ff45b8be234394feac5f0b30020420bbdc49bc84334e"
    },
    {
      "path": "packages/financial-core/src/receivables/structure-cost.ts",
      "hash": "0393ab7df072b6a71fb29a723ea3434c233cfd905456562b5f6f859eca31b3d6"
    },
    {
      "path": "packages/financial-core/src/structure.ts",
      "hash": "f2794ba314bcd6f3212502a2daebe5e28a171f5792e698299365fd9935b3ece6"
    },
    {
      "path": "packages/public-research/package.json",
      "hash": "4f3e8298f26d740d631659945c0ae8d817292d64e13fb36e2af6362cc0de963e"
    },
    {
      "path": "packages/public-research/src/cache.ts",
      "hash": "6c698a595b7eb764fe113545703561e765a02b3d0fa14ec44a43e678065c930e"
    },
    {
      "path": "packages/public-research/src/capital-catalog.ts",
      "hash": "1dc04471b40b8f586bbb905d6d9df4d8efed076602df0bf432c176bf7fa5f8b9"
    },
    {
      "path": "packages/public-research/src/company-memory.ts",
      "hash": "c546b55c2ea292534c8502e79b0f52cc691d8af1738f52069322e92b46321cb2"
    },
    {
      "path": "packages/public-research/src/content-acquisition.ts",
      "hash": "4a3e36f3f1d1f3f65ea5d5e2f8f594917cea4885351a90b8295bbcbc44ae6839"
    },
    {
      "path": "packages/public-research/src/contracts.ts",
      "hash": "813dd429c87678b02954f01cd6ce5c5f2c924961954fba679b1b965fda8e8a75"
    },
    {
      "path": "packages/public-research/src/entity-resolvers.ts",
      "hash": "cdf17427dfc7cfe6e30b2b33616a2832527dbfb2bbee358d21d45cf27c0c3b2a"
    },
    {
      "path": "packages/public-research/src/index.ts",
      "hash": "6e8db8241911bc1b9d6d51a1335c4629107e44bb2b7fe6b2ebfbe9ca52fbb3b7"
    },
    {
      "path": "packages/public-research/src/official-company-research.ts",
      "hash": "6026c393fc75d5230898763718158d6ff2f1b47dedab527f4a4a62157ca1f728"
    },
    {
      "path": "packages/public-research/src/source-pack-test-helper.ts",
      "hash": "a91623798f05216306c6085dbdfba296372420eb5d87d2c45e735be2696e88c9"
    },
    {
      "path": "packages/public-research/src/source-pack.ts",
      "hash": "63cfa9f7f3d994207fac2cd28f872b6f89b512524a6b197dbbe339641b858257"
    },
    {
      "path": "packages/public-research/src/source-registry.ts",
      "hash": "56f24bfadfad898f0c6477b191e259d83822fd7741dd1a3af217a6efeab777a4"
    },
    {
      "path": "packages/work-plan/package.json",
      "hash": "4ef8c848ab47e2e896c1f47555d494ea79bcad51d25961002f7f5f39e6c11ae4"
    },
    {
      "path": "packages/work-plan/src/advisor-starting-plan.ts",
      "hash": "64eb17000dea4ee1cd3445128bf1fca3cda3af361996c298832ce848c200ebfd"
    },
    {
      "path": "packages/work-plan/src/capital-jobs.ts",
      "hash": "2ec2cfd02fcf176009321805f192eecb7107621089b13a1db734fd9d92269901"
    },
    {
      "path": "packages/work-plan/src/document-work-plan.ts",
      "hash": "6f0955938e5ca40197d824261d5c1a4383c767c75ecad60f169afe54ca578116"
    },
    {
      "path": "packages/work-plan/src/document-work-request.ts",
      "hash": "4b783e7674922450eaf6e9609f1173bf8c4b92b1191f461195b0adc84d7fc6ed"
    },
    {
      "path": "packages/work-plan/src/execution-brief.ts",
      "hash": "93164c9c11458caa278c9e4e28391e61270232b831954d1988d22441cbd649b8"
    },
    {
      "path": "packages/work-plan/src/execution-readiness.ts",
      "hash": "d9e45abacead619f6683e82daecf064f235ae236181a4a5893468c63269cfc4f"
    },
    {
      "path": "packages/work-plan/src/index.ts",
      "hash": "00e1d716eef91298dfb61a8110d963b928fbdf8b3ac2a90c9ce14b9283edd387"
    },
    {
      "path": "packages/work-plan/src/job-inference.ts",
      "hash": "f32f1861954874226aff0d2eafa6405e7437a447739ded9d24dddb12f38818b3"
    },
    {
      "path": "packages/work-plan/src/objective-plan.ts",
      "hash": "9a70e886c7490d14ee471ce38a4a11a714a527202c152fd1ef32e278b8501251"
    },
    {
      "path": "packages/work-plan/src/output-terminal.ts",
      "hash": "e1934c7f132960c49bf639df95af4aeff606f6781520764f33f285e9993c7649"
    },
    {
      "path": "packages/work-plan/src/project-capability-registry.ts",
      "hash": "bff0726976c2ad9711aee87c3e89d32be3dc0c7d6b279df59c557696d1ad484e"
    },
    {
      "path": "packages/work-plan/src/provider-research-plan.ts",
      "hash": "b8ea34e0bfac8a9e493d1c8c90ad866f0b088e9d2585b357728bd391753fa777"
    },
    {
      "path": "packages/work-plan/src/provider-research.ts",
      "hash": "f01fe15f4c9f14ece99a4c0aba17102b991e6f781e0ed29d650210f2a8d80654"
    },
    {
      "path": "packages/work-plan/src/task-localization.ts",
      "hash": "ee12740c1dac8f5e4b7ec62832a8149d5a7b9e4998a95f16494687a2aed457f9"
    },
    {
      "path": "packages/work-plan/src/task-registry.ts",
      "hash": "9fbed0a6cb6fb6df84314978a23a1e3a811e6cf3532b856e1fe74fcfa81d3b3e"
    },
    {
      "path": "pnpm-lock.yaml",
      "hash": "cbfb344a330e076fcfca034a920677378d2b27fa947343751affd87eeb5a1c32"
    },
    {
      "path": "tsconfig.base.json",
      "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
    }
  ],
  "37ed5a9a2253f25e3c2b8d79d0e9cabf92c76e9bb3d06a74e52380d164c7e9e6": [
    {
      "path": "packages/domain-contracts/package.json",
      "hash": "d9455e3bfc96fc4a14ac45053466c46f46ab6044dbb42250794419b0e417c9d6"
    },
    {
      "path": "packages/domain-contracts/src/contextual-adoption.ts",
      "hash": "bbe50f847a84fdfce427e507836798df1ee0f8ccc7ec761d2d580ef3c58096b2"
    },
    {
      "path": "packages/domain-contracts/src/document-work-product.ts",
      "hash": "ec9c66b87b2e496cd3697c9f7a6ecb42b971cfb16007c08f3a2b8d99920df3b9"
    },
    {
      "path": "packages/domain-contracts/src/domain-event.ts",
      "hash": "971b71a86e609bb27afa355b2063e19800789552c6633d2728df7bb726e2fba6"
    },
    {
      "path": "packages/domain-contracts/src/dossier.ts",
      "hash": "7fb87fe96d44754c72fd593a4a3477434ee85d2c18df1fc1e8db8fe16679d1d9"
    },
    {
      "path": "packages/domain-contracts/src/entity.ts",
      "hash": "5c1e3c9c282f24048acd8f12f54d266f5fe629058d1fed3399b558a975f30da2"
    },
    {
      "path": "packages/domain-contracts/src/index.ts",
      "hash": "451d16e62c9b3801c2da017364a452bd99e500b08c263b3336d213b23e2d24d6"
    },
    {
      "path": "packages/domain-contracts/src/observation.ts",
      "hash": "8a9ecfd95fd9ac74d2f2824a2b708b377e8de3b03ec0968df8f0520e32e2e025"
    },
    {
      "path": "packages/domain-contracts/src/source-version.ts",
      "hash": "cfc11f7076ced8be453c7f3fb5751dc89e20e880bbfd2b31ec1c342c321c14c5"
    },
    {
      "path": "packages/financial-core/package.json",
      "hash": "69f2268dfae2fe6e8f5e0c33a05f68dd8e509f68ff77c21348e5ba906a1ac008"
    },
    {
      "path": "packages/financial-core/src/assumption-unit.ts",
      "hash": "2fec9fdf4fa0e6d01431a07060cd0d588f81a4653d125db631acab622dfff35f"
    },
    {
      "path": "packages/financial-core/src/depreciation.ts",
      "hash": "ea9bd8b4f1024d3472d85f35039b8ed72c8bcde9cc5c82b3f97f70fec0ae275a"
    },
    {
      "path": "packages/financial-core/src/financial-truth.ts",
      "hash": "a0c80b192ca540b8fbd301a621d8e5c82554e1055e3f3231dc0f0d2da659014c"
    },
    {
      "path": "packages/financial-core/src/index.ts",
      "hash": "de399601ef7e32191aee3f5c42faa6a3a57299787e8b1a3e0bb2d57337e26dd6"
    },
    {
      "path": "packages/financial-core/src/indexed-debt.ts",
      "hash": "cfb4acc3f86457ecaa858bb489d9e855dc0ff8c14ff4b906106f495159edb2eb"
    },
    {
      "path": "packages/financial-core/src/operation.ts",
      "hash": "24e18ea3471e7b26d60d5b2c323fcf001e5fcb2d86d5310996e2f4f1854b9d05"
    },
    {
      "path": "packages/financial-core/src/receivables/contracts.ts",
      "hash": "96c8f29dbc763ada38909538a25b67e849b4f19592459e712c77f215893036b7"
    },
    {
      "path": "packages/financial-core/src/receivables/dynamic-metrics.ts",
      "hash": "cd6fa83a9db894a4919ed645875f6fd61a5452ec336c9d531420d550c3d3ed51"
    },
    {
      "path": "packages/financial-core/src/receivables/eligibility-allocation.ts",
      "hash": "e6d668815a3602d96b565234b58fb3aefbaab72f5fb5d3867af44577ac47606b"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-borrowing-base.ts",
      "hash": "c11cd74e99bb375e56c058beaa48586a1a67b7beedf2630012efdd986825a2cb"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-concentration.ts",
      "hash": "ca17f9c2ee483dccc4c7dde3338b35a6200a20c6609edbc83cd5748457576167"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-eligibility.ts",
      "hash": "fd0b6f9fdade3372e0f3822119148d905a09a42bc14bd0301c6ebe9c078dc600"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-performance.ts",
      "hash": "219e4a1b8d1b0e3729ce2d1a8660ef85a23202e924bb19bd0bf7f5b03f7b9e63"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-reconciliation.ts",
      "hash": "887e8f1bb3cc8ad8460b08ddf1f826ba0cd0d5919b5d3ffed24d21bc8d59a6bc"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-shared.ts",
      "hash": "ec9689cf119841652ba0fff48f185df2e7cd7a3d8936a10bda76ab7f5caff7ed"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-triggers.ts",
      "hash": "cd44019e6800c7f67cade698e2238852d7746852c3f4b6e807fb17bf9886d16a"
    },
    {
      "path": "packages/financial-core/src/receivables/pool-waterfall.ts",
      "hash": "27c877893caaf92ae4881dcfdc2919110d7845cdf29b9fc301a8a961015a13ae"
    },
    {
      "path": "packages/financial-core/src/receivables/provider-allocation.ts",
      "hash": "4c66699982526e2186d16e57a77290f2fd08ea1b7c4e334feb123dc7cfb1ff84"
    },
    {
      "path": "packages/financial-core/src/receivables/static-metrics.ts",
      "hash": "31af3414353b30419945ff45b8be234394feac5f0b30020420bbdc49bc84334e"
    },
    {
      "path": "packages/financial-core/src/receivables/structure-cost.ts",
      "hash": "0393ab7df072b6a71fb29a723ea3434c233cfd905456562b5f6f859eca31b3d6"
    },
    {
      "path": "packages/financial-core/src/structure.ts",
      "hash": "f2794ba314bcd6f3212502a2daebe5e28a171f5792e698299365fd9935b3ece6"
    },
    {
      "path": "packages/fund-mandate/package.json",
      "hash": "475daa3dc64507e41c1a800581b598a6b2371f42bb38e2ddb96b0641b68a0301"
    },
    {
      "path": "packages/fund-mandate/src/fit.ts",
      "hash": "cf1490ae300b044b26f8dc0484494187ba8d6c6e5e4248ccbeda1006605de676"
    },
    {
      "path": "packages/fund-mandate/src/index.ts",
      "hash": "e9a75f32ae99ce8b9d5de72feeaba26b77cfbbf2a4fb65ea658b15cbfbf01102"
    },
    {
      "path": "packages/fund-mandate/src/mandate.ts",
      "hash": "c28763afed509ae19ba370d26cecb4515e58dc72c912f0fb4ff1cb233ba64707"
    },
    {
      "path": "packages/fund-mandate/src/market-truth.ts",
      "hash": "240e87559fdd1cd1a38813d66b9ebb87db23b8968928da137e9295d2e4453b83"
    },
    {
      "path": "packages/fund-mandate/src/provenance.ts",
      "hash": "f52e85abc9bb34b0339c88ed41ca1f3a9cf2f829f6c5a4fcffdd622d7ecb0291"
    },
    {
      "path": "packages/fund-mandate/src/provider-case-fit.ts",
      "hash": "a6a0839e96a68b80db9493997d0d67f99e962c05ce6c4146aa07627d1e4c644e"
    },
    {
      "path": "packages/fund-mandate/src/receivables-provider.ts",
      "hash": "fe21762fe2a030475bc7581f23a3bf026e78442c62e252497e9e519b36f1ac40"
    },
    {
      "path": "packages/fund-mandate/src/verified-mandate.ts",
      "hash": "64be14fbe35be030971f8f44fa4586a9b15a25a8fdbf36995fe084fc3c74753c"
    },
    {
      "path": "packages/matching-core/package.json",
      "hash": "65c2d30d07c7caa688e6ff4891fd754870920afc7d6020241d6bfd4304586a2b"
    },
    {
      "path": "packages/matching-core/src/candidate-fit.ts",
      "hash": "3f53e963e67ad4bd9b6553f577573b27ec3afcb26b59f4c7a22725652bf10605"
    },
    {
      "path": "packages/matching-core/src/index.ts",
      "hash": "c0b0725196155b434068d1b8d26d1a54cdd6927c68f2c4c96627c07e7de1df4e"
    },
    {
      "path": "packages/receivables-analysis/package.json",
      "hash": "c39e488811ecff294de3c93116b3993d0e7e32ed38e412a120744c2fc4c8e5ad"
    },
    {
      "path": "packages/receivables-analysis/src/analyze.ts",
      "hash": "0fe23ee07a15ce70e434411eab0d72bede9faf816896e7fd0672ac560098521d"
    },
    {
      "path": "packages/receivables-analysis/src/anchors.ts",
      "hash": "8c1c8b9a3e9153a3c8b647ce663d5e229497f215f50c2a1a1c134901c9442fbf"
    },
    {
      "path": "packages/receivables-analysis/src/balance-source-proposals.ts",
      "hash": "fef54f1b8455c21825a4a5a86797cf2895c947f8948fb4fc9d7c97de1af32ac5"
    },
    {
      "path": "packages/receivables-analysis/src/canonical.ts",
      "hash": "56ceb7a877bc3ea06d0eddb5a74efd752e5bc3dab555e56c547bc60d3d8cd48a"
    },
    {
      "path": "packages/receivables-analysis/src/contract-facts.ts",
      "hash": "4f97d42811fc62b00d311398066cf468f814252ad76c4ec7cefb652c42361cbf"
    },
    {
      "path": "packages/receivables-analysis/src/document-supplement-contract.ts",
      "hash": "9c5d713f4a6584fe609a0de5d427a5a7905e0a9b2f2a656c48dead229271901d"
    },
    {
      "path": "packages/receivables-analysis/src/evidence-scope.ts",
      "hash": "b2210a97230ba48af509430a3f8f3ebcf79093590327d7b70a4f535eaab9b834"
    },
    {
      "path": "packages/receivables-analysis/src/history-coverage.ts",
      "hash": "1419dea0b68616b376a655d611a553e2b2227e149a7b99eb3cf8252d3a82614e"
    },
    {
      "path": "packages/receivables-analysis/src/index.ts",
      "hash": "95ca1959b9ec3cc55481e53bc80062cfd747b3ecd67481a9c413aa6abb1d077e"
    },
    {
      "path": "packages/receivables-analysis/src/method-assembly.ts",
      "hash": "b574fb856c7b9eac298df844b91f70d38a1e50f6513ab2e873e40882602e0012"
    },
    {
      "path": "packages/receivables-analysis/src/method-readiness.ts",
      "hash": "a95fde47c095fc764a665f6af4d15824ea89da55a23a92d3c1d691056c17c4f7"
    },
    {
      "path": "packages/receivables-analysis/src/method-supplement-draft.ts",
      "hash": "90c7f0c57b4f18f73759daf5af2c020061cf4272dcb43c27e0c366838cbee1b5"
    },
    {
      "path": "packages/receivables-analysis/src/phase-one.ts",
      "hash": "5f0b2e42b4065bbbe7f7dfb2af09540e0ff4a8a04863088123e23eb38b1cef66"
    },
    {
      "path": "packages/receivables-analysis/src/phase-two-b.ts",
      "hash": "e09f60574f9800a3762ed8e7e5cefde1cdc689fbf4470d6d422bcead6661dcd6"
    },
    {
      "path": "packages/receivables-analysis/src/phase-two.ts",
      "hash": "162747113711efa56460bbf1542d46a3f0e922b1df88f5bb6856ea87f50191c2"
    },
    {
      "path": "packages/receivables-analysis/src/playbook.ts",
      "hash": "37950b5b6ab1a4edd143d0cffc5ab97a8a9160737e54ae6f21394233f407dd03"
    },
    {
      "path": "packages/receivables-analysis/src/raw-detection.ts",
      "hash": "25894699ca70de2567cede5a18c3b6c537808873d93836b229883f223a936d21"
    },
    {
      "path": "packages/receivables-analysis/src/scenarios.ts",
      "hash": "9bd14c77cfca2c9a596fb069220088cb970d1a13e702d11a67c784cc39916c0b"
    },
    {
      "path": "packages/receivables-analysis/src/schema.ts",
      "hash": "79a186c8680d8b8a0de8a089677782af4a645657feadf6c36e37e416778e90d7"
    },
    {
      "path": "packages/receivables-analysis/src/support-periods.ts",
      "hash": "9678809057e3ab51bcb01f9359baad7ebd29dae3aaa10c491a8f932517bca98c"
    },
    {
      "path": "packages/receivables-analysis/src/underwrite.ts",
      "hash": "f823ce797bf959c6fe6dd7d30065b9fecd90f4c99dfc52419f4e3d1c4bb60bf5"
    },
    {
      "path": "pnpm-lock.yaml",
      "hash": "9c58538e770b8ae181c088a42ba33a5456fbbc112eda3188b9898c084464df5b"
    },
    {
      "path": "tsconfig.base.json",
      "hash": "0b80c49c86ed761d3e51788378c8e43cbcabebf8ccfbdd520c147223e9d543da"
    }
  ]
} as const;
