import {beforeEach,describe,expect,it,vi}from"vitest";
const m=vi.hoisted(()=>({workspace:vi.fn(),rpc:vi.fn(),project:vi.fn(),refresh:vi.fn()}));
vi.mock("@/lib/auth/workspace",()=>({requireWorkspace:m.workspace}));vi.mock("next/cache",()=>({revalidatePath:m.refresh}));
import{readAssessmentReview,reviewAssessment}from"./assessment-review-actions";
const id="10000000-0000-4000-8000-000000000001",assessment="10000000-0000-4000-8000-000000000002",commandId="10000000-0000-4000-8000-000000000003";
const basis={workId:id,assessmentId:assessment,decisionKey:"case.structure_direction",revision:1,decisionFingerprint:"a".repeat(64),proposalFingerprint:"b".repeat(64),preparedBy:id,viewerId:id,workAccess:true,policy:{assignmentRequired:false,selfApprovalAllowed:true,roles:[]},totalSourceCount:1,documentSourceCount:1,houseSourceCount:0,publicSourceCount:0,status:"open",nativeOutcome:null,frozen:false,nativeDecisionId:null};
const input={locale:"pt-BR",projectId:id,assessmentId:assessment,commandId,revision:1,decisionFingerprint:basis.decisionFingerprint,proposalFingerprint:basis.proposalFingerprint,outcome:"approved",freeze:true,selfApprovalDeclared:true};
beforeEach(()=>{vi.clearAllMocks();const eq=vi.fn();eq.mockReturnValue({eq,maybeSingle:m.project});m.project.mockResolvedValue({data:{id},error:null});m.workspace.mockResolvedValue({organization:{id},supabase:{rpc:m.rpc,from:()=>({select:()=>({eq})})}});m.rpc.mockImplementation(async(n:string)=>({data:n==="read_assessment_review_basis_v2"?basis:{decisionId:commandId,assessmentId:assessment,outcome:"approved",frozen:true,replayed:false},error:null}));});
describe("native assessment human action",()=>{
 it("reads authorized proposal and fixes the exact reviewed economic identity",async()=>{expect((await readAssessmentReview({locale:"pt-BR",projectId:id,assessmentId:assessment})).ok).toBe(true);expect(await reviewAssessment(input)).toEqual({ok:true});expect(m.rpc.mock.calls.at(-1)?.[1]).toMatchObject({p_expected_proposal_fingerprint:basis.proposalFingerprint,p_freeze:true,p_self_approval_declared:true});expect(m.rpc.mock.calls.some(c=>c[0]==="enqueue_processing_job")).toBe(false);});
 it("denies tenant and arbitrary effect before the review",async()=>{expect(await reviewAssessment({...input,effect:"queue_execution"})).toEqual({ok:false,error:"invalid"});m.project.mockResolvedValue({data:null,error:null});expect(await reviewAssessment(input)).toEqual({ok:false,error:"denied"});expect(m.rpc).not.toHaveBeenCalled();});
 it("rejects proposal change without refreshing away the person's pin",async()=>{expect(await reviewAssessment({...input,proposalFingerprint:"c".repeat(64)})).toEqual({ok:false,error:"stale"});expect(m.rpc).toHaveBeenCalledOnce();});
 it("requires explicit self declaration and preserves DB denial with no fallback",async()=>{expect(await reviewAssessment({...input,selfApprovalDeclared:false})).toEqual({ok:false,error:"denied"});m.rpc.mockResolvedValue({data:null,error:{code:"42501",message:"assessment_review_source_denied"}});expect(await reviewAssessment(input)).toEqual({ok:false,error:"denied"});expect(m.rpc.mock.calls.every(c=>c[0]==="read_assessment_review_basis_v2")).toBe(true);});
 it("rejection binds frozen false without asking execution",async()=>{m.rpc.mockImplementation(async(n:string)=>({data:n==="read_assessment_review_basis_v2"?basis:{decisionId:commandId,assessmentId:assessment,outcome:"rejected",frozen:false,replayed:false},error:null}));expect(await reviewAssessment({...input,outcome:"rejected",freeze:false,selfApprovalDeclared:false})).toEqual({ok:true});expect(m.rpc.mock.calls.at(-1)?.[1]).toMatchObject({p_outcome:"rejected",p_freeze:false});});
});
