import type {ProfessionalContextCopy} from "./professional-context-form";

type Translator = (key: string) => string;

export function professionalContextCopy(t: Translator): ProfessionalContextCopy {
  return {
    title: t("title"),
    body: t("body"),
    useFormsQuestion: t("useFormsQuestion"),
    useFormsHelp: t("useFormsHelp"),
    useForms: {
      institutional_work: t("useForms.institutionalWork"),
      independent_practice: t("useForms.independentPractice"),
      personal_projects: t("useForms.personalProjects"),
      exploring: t("useForms.exploring"),
    },
    institutionQuestion: t("institutionQuestion"),
    institutionHelp: t("institutionHelp"),
    institutionPlaceholder: t("institutionPlaceholder"),
    rolesQuestion: t("rolesQuestion"),
    rolesHelp: t("rolesHelp"),
    roles: {
      ceo_founder: t("roles.ceoFounder"), board_shareholder: t("roles.boardShareholder"),
      cfo: t("roles.cfo"), treasury: t("roles.treasury"), corporate_finance: t("roles.corporateFinance"),
      banker: t("roles.banker"), financial_advisor: t("roles.financialAdvisor"), originator: t("roles.originator"),
      credit_analyst: t("roles.creditAnalyst"), risk_underwriting: t("roles.riskUnderwriting"),
      investor_portfolio_manager: t("roles.investorPortfolioManager"), legal_operations: t("roles.legalOperations"),
      independent_consultant: t("roles.independentConsultant"), student_researcher: t("roles.studentResearcher"),
      other: t("roles.other"),
    },
    areasQuestion: t("areasQuestion"),
    areasHelp: t("areasHelp"),
    areas: {
      treasury: t("areas.treasury"), corporate_finance: t("areas.corporateFinance"), fp_and_a: t("areas.fpAndA"),
      strategy: t("areas.strategy"), corporate_development: t("areas.corporateDevelopment"),
      investor_relations: t("areas.investorRelations"), dcm: t("areas.dcm"),
      investment_banking: t("areas.investmentBanking"), corporate_banking: t("areas.corporateBanking"),
      structured_finance: t("areas.structuredFinance"), project_finance: t("areas.projectFinance"),
      origination: t("areas.origination"), syndicate_distribution: t("areas.syndicateDistribution"),
      credit: t("areas.credit"), underwriting: t("areas.underwriting"), risk: t("areas.risk"),
      private_credit: t("areas.privateCredit"), investments: t("areas.investments"),
      portfolio_management: t("areas.portfolioManagement"), special_situations: t("areas.specialSituations"),
      legal: t("areas.legal"), operations: t("areas.operations"), other: t("areas.other"),
    },
    objectivesQuestion: t("objectivesQuestion"),
    objectivesHelp: t("objectivesHelp"),
    objectives: {
      understand_company: t("objectives.understandCompany"),
      understand_capital_structure: t("objectives.understandCapitalStructure"),
      evaluate_capital_options: t("objectives.evaluateCapitalOptions"),
      prepare_meetings: t("objectives.prepareMeetings"),
      originate_ideas: t("objectives.originateIdeas"),
      organize_documents: t("objectives.organizeDocuments"),
      analyze_investments: t("objectives.analyzeInvestments"),
      structure_transactions: t("objectives.structureTransactions"),
      prepare_materials: t("objectives.prepareMaterials"),
      connect_capital: t("objectives.connectCapital"),
      monitor_positions: t("objectives.monitorPositions"),
      explore_platform: t("objectives.explorePlatform"),
      other: t("objectives.other"),
    },
    save: t("save"),
    saveSettings: t("saveSettings"),
    skip: t("skip"),
    assurance: t("assurance"),
  };
}
