import {randomBytes} from "node:crypto";
import {expect, test} from "@playwright/test";
import {waitForOneTimeCode} from "./support/mail";

// Runs with the normal local worker, without provider credentials, seeded results or model calls.
test("approved provider research persists public sources while private mandates remain empty", async ({page}) => {
  const base = new URL(process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000");
  if (!["127.0.0.1", "localhost", "[::1]"].includes(base.hostname)) throw new Error("Provider research E2E requires a local synthetic workspace.");
  const id = `${Date.now().toString(36)}${randomBytes(4).toString("hex")}`;
  const email = `e2e-providers-${id}@example.com`;
  const password = `Offroad-E2E-${id}!`;
  await page.goto("/pt-BR/signup");
  await page.locator('input[name="full_name"]').fill("QA pesquisa de financiadores");
  await page.locator('input[name="email"]').fill(email);
  await page.locator('input[name="password"]').fill(password);
  await page.locator('input[name="confirm_password"]').fill(password);
  await page.locator("form.auth-form--registration button[type=submit]").click();
  await expect(page).toHaveURL(/\/pt-BR\/signup\/verify/);
  await page.locator('input[name="token"]').fill(await waitForOneTimeCode(email));
  await page.locator("form.auth-form--verification button[type=submit]").click();
  await expect(page).toHaveURL(/\/pt-BR\/onboarding/);
  await page.locator('input[name="use_forms"][value="institutional_work"]').check();
  await page.locator('input[name="institution_name"]').fill("Instituição sintética de teste");
  await page.locator('input[name="professional_roles"][value="banker"]').check();
  await page.locator('input[name="practice_areas"][value="dcm"]').check();
  await page.locator('input[name="primary_objectives"][value="prepare_meetings"]').check();
  await page.locator(".professional-context__actions .button:not(.button--ghost)").click();
  await expect(page.locator(".intake-start")).toBeVisible();
  await page.goto("/pt-BR/onboarding?setup=terms&job=capital_planning");
  await page.locator('input[name="signatory_title"]').fill("Analista");
  await page.locator('input[name="terms_agreed"]').check();
  await page.locator('input[name="information_rights_declared"]').check();
  await page.locator('.private-project-gate__form button[type="submit"]').click();
  await expect(page.locator(".private-project-gate--project")).toBeVisible();
  // Account onboarding becomes workspace-ready only when its first project is created.
  // Creating the shell does not start document analysis or seed the research result.
  await page.locator('input[name="project_name"]').fill(`Onboarding sintético ${id}`);
  await page.locator('.private-project-gate__form button[type="submit"]').click();
  await expect(page.locator(".intake-collect")).toBeVisible();
  await page.goto("/pt-BR/app");
  const composer = page.locator(".advisor-composer--start");
  const request = "Pesquise os financiadores e mandatos disponíveis para minha organização.";
  await composer.locator("textarea").fill(request);
  await composer.locator(".advisor-composer__send").click();
  await expect(page).toHaveURL(/\/pt-BR\/app\/projects\/[0-9a-f-]+$/);
  const brief = page.getByTestId("execution-brief");
  await expect(brief.locator('[data-approval-status="awaiting"]')).toBeVisible({timeout: 120_000});
  await expect(brief).toContainText(request);
  await expect(brief.locator(".execution-brief-card__workstreams > li")).toHaveCount(3);
  const research = page.getByTestId("provider-research-work");
  await expect(research).toHaveCount(0);
  await brief.locator('[data-approval-status="awaiting"]').getByRole("button", {name: /aprovar|approve/i}).click();
  await expect(research).toBeVisible({timeout: 120_000});
  await expect(research.locator("article")).toHaveCount(28);
  await expect(research.getByRole("link", {name: /Itaú/}).first()).toHaveAttribute("href", "https://www.itau.com.br/empresas/emprestimos-financiamentos");
  await expect(research).toContainText("Estratégias não equivalem a mandatos atuais");
  await expect(research.getByRole("checkbox")).toHaveCount(0);
  const text = await research.textContent();
  await page.reload();
  await expect(research).toHaveText(text!);
  await expect(brief.locator('.execution-brief-card__workstreams > li[data-progress="completed"]')).toHaveCount(3);
  // Continue inside the same project, with a separate approved case-specific mandate screen.
  const projectPath = new URL(page.url()).pathname;
  await page.locator('.advisor-work-surface__navigation a[href="#work-provider-case-criteria"]').click();
  const fitForm = page.getByTestId("provider-case-fit-form");
  await fitForm.locator("summary").click();
  await fitForm.locator('input[name="asOf"]').fill(new Date(Date.now() - 60_000).toISOString().slice(0, 16));
  await fitForm.locator('select[name="currency"]').selectOption("BRL");
  await fitForm.locator('input[name="amount"]').fill("10000000");
  await fitForm.locator('input[name="sector"]').fill("Serviços");
  await fitForm.locator('input[name="geography"]').fill("BR");
  await fitForm.locator('input[type="checkbox"][required]').check();
  await fitForm.getByRole("button", {name: "Preparar plano de seleção"}).click();
  await expect(brief.locator('[data-approval-status="awaiting"]')).toBeVisible({timeout: 120_000});
  expect(new URL(page.url()).pathname).toBe(projectPath);
  await expect(brief).toContainText("Identificar financiadores aderentes ao caso");
  await expect(brief.locator(".execution-brief-card__workstreams > li")).toHaveCount(3);
  await expect(page.getByTestId("provider-case-fit-work")).toHaveCount(0);
  await brief.locator('[data-approval-status="awaiting"]').getByRole("button", {name: /aprovar|approve/i}).click();
  const fitLink = page.locator('.advisor-work-surface__navigation a[href="#work-provider-case-fit"]');
  await expect(fitLink).toBeVisible({timeout: 120_000});
  await fitLink.click();
  const fit = page.getByTestId("provider-case-fit-work");
  await expect(fit).toBeVisible();
  await expect(fit).toContainText("Não há mandatos autorizados disponíveis para comparar");
  await expect(fit).toContainText("Não autoriza divulgação, contato ou introdução");
  await expect(fit.getByRole("button")).toHaveCount(0);
  const fitText = await fit.textContent();
  await page.reload();
  expect(new URL(page.url()).pathname).toBe(projectPath);
  await expect(fit).toHaveText(fitText!);
  await page.locator('.advisor-work-surface__navigation a[href="#work-provider-history"]').click();
  const history = page.getByTestId("provider-work-history");
  await expect(history).toContainText("Não representam a seleção ou o mandato atual");
  await history.locator("summary").first().click();
  await expect(history.getByTestId("provider-research-work")).toHaveText(text!);
  // The initial request remains in the conversation; no workspace restart occurred.
  await expect(page.getByText(request, {exact: true}).first()).toBeVisible();
  // Actual authenticated market navigation exercises client messages, hydration and separation
  // from the already persisted private research artifact. No external links are followed.
  await page.locator('.app-rail__nav a[href="/pt-BR/app/market"]').click();
  await expect(page).toHaveURL(/\/pt-BR\/app\/market$/);
  await expect(page.getByRole("heading", {name: "Encontre o caminho para o capital."})).toBeVisible();
  await page.getByLabel("Buscar", {exact: true}).fill("Pátria");
  await expect(page.locator("main article")).toHaveCount(1);
  await page.getByLabel("Estrutura a pesquisar").selectOption("receivables");
  await expect(page.locator("main article")).toContainText("Estratégia pública compatível");
  await page.getByRole("button", {name: "Cadastros oficiais", exact: true}).click();
  await page.getByLabel("Base de origem").selectOption("bcb_root");
  await page.getByLabel("Buscar nome ou CNPJ").fill("61190658");
  await expect(page.locator("main article")).toHaveCount(1);
  await expect(page.locator("main article")).toContainText("8 dígitos; não é CNPJ completo");
  await expect(page.locator("main article")).toContainText("Sem mandato, ticket, taxa, capacidade ou apetite verificados.");
  await expect(page.locator('main article a[href^="https://olinda.bcb.gov.br/"]')).toHaveCount(1);
  await page.getByRole("button", {name: "Operações e taxas históricas", exact: true}).click();
  await expect(page.locator("main article")).toHaveCount(5);
  await expect(page.locator("main article").filter({hasText: "MOVIB2"})).toContainText("Investidores / financiadores não identificados na fonte.");
  await expect(page.locator("main article").filter({hasText: "MOVIB2"}).getByRole("link")).toHaveAttribute("href", /^https:\/\//);
  await page.goto(projectPath);
  await expect(page.getByTestId("provider-case-fit-work")).toHaveText(fitText!);


});
