import {randomBytes} from "node:crypto";
import {expect, test} from "@playwright/test";
import {waitForOneTimeCode} from "./support/mail";

// Runs with the normal local worker, without provider credentials, seeded results or model calls.
test("approved provider research persists an honest empty authorized universe", async ({page}) => {
  const base = new URL(process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000");
  if (!["127.0.0.1", "localhost", "[::1]"].includes(base.hostname)) throw new Error("Provider research E2E requires a local synthetic workspace.");
  const id = `${Date.now().toString(36)}${randomBytes(4).toString("hex")}`;
  const email = `e2e-providers-${id}@example.com`;
  const password = `Offroad-E2E-${id}!`;
  await page.goto("/pt-BR/signup");
  await page.locator('input[name="full_name"]').fill("QA pesquisa de financiadores");
  await page.locator('input[name="email"]').fill(email);
  await page.locator('input[name="password"]').fill(password);
  await page.locator('input[name="confirm_password"]').fill(password);
  await page.locator("form.auth-form--registration button[type=submit]").click();
  await expect(page).toHaveURL(/\/pt-BR\/signup\/verify/);
  await page.locator('input[name="token"]').fill(await waitForOneTimeCode(email));
  await page.locator("form.auth-form--verification button[type=submit]").click();
  await expect(page).toHaveURL(/\/pt-BR\/onboarding/);
  await page.locator('input[name="use_forms"][value="institutional_work"]').check();
  await page.locator('input[name="institution_name"]').fill("Instituição sintética de teste");
  await page.locator('input[name="professional_roles"][value="banker"]').check();
  await page.locator('input[name="practice_areas"][value="dcm"]').check();
  await page.locator('input[name="primary_objectives"][value="prepare_meetings"]').check();
  await page.locator(".professional-context__actions .button:not(.button--ghost)").click();
  await expect(page.locator(".intake-start")).toBeVisible();
  await page.goto("/pt-BR/onboarding?setup=terms&job=capital_planning");
  await page.locator('input[name="signatory_title"]').fill("Analista");
  await page.locator('input[name="terms_agreed"]').check();
  await page.locator('input[name="information_rights_declared"]').check();
  await page.locator('.private-project-gate__form button[type="submit"]').click();
  await expect(page.locator(".private-project-gate--project")).toBeVisible();
  await page.goto("/pt-BR/app");
  const composer = page.locator(".advisor-composer--start");
  const request = "Pesquise os financiadores e mandatos disponíveis para minha organização.";
  await composer.locator("textarea").fill(request);
  await composer.locator(".advisor-composer__send").click();
  await expect(page).toHaveURL(/\/pt-BR\/app\/projects\/[0-9a-f-]+$/);
  const brief = page.getByTestId("execution-brief");
  await expect(brief.locator('[data-approval-status="awaiting"]')).toBeVisible({timeout: 120_000});
  await expect(brief).toContainText(request);
  await expect(brief.locator(".execution-brief-card__workstreams > li")).toHaveCount(3);
  const research = page.getByTestId("provider-research-work");
  await expect(research).toHaveCount(0);
  await brief.locator('[data-approval-status="awaiting"]').getByRole("button", {name: /aprovar|approve/i}).click();
  await expect(research).toBeVisible({timeout: 120_000});
  await expect(research.locator('[role="status"]')).toBeVisible();
  await expect(research.getByRole("checkbox")).toHaveCount(0);
  const text = await research.textContent();
  await page.reload();
  await expect(research).toHaveText(text!);
  await expect(brief.locator('.execution-brief-card__workstreams > li[data-progress="completed"]')).toHaveCount(3);
});
