import {z} from "zod";
const uuid = z.uuid(), hash = z.string().regex(/^[a-f0-9]{64}$/), text = z.string().max(100000);
const classification = z.enum(["unchanged", "edited", "conflict", "missing", "unmatched", "formula_changed", "recorded_edited"]);
const entry = z.strictObject({key: z.string().min(1).max(600), blockKey: z.string().max(160).nullable(), role: z.enum(["input", "text", "formula", "recorded"]), value: text.nullable(), formula: text.nullable(), locator: z.string().max(1000), claimIds: z.array(z.string().max(300)).max(500)});
const comparison = z.object({status: z.enum(["candidate", "unmatched"]), baseRevisionId: uuid.nullable(), headRevisionId: uuid, differences: z.array(z.strictObject({key: z.string().min(1).max(600), classification, base: entry.nullable(), received: entry.nullable(), current: entry.nullable(), alreadyPresent: z.boolean()})).max(20000)});
const contributions = z.object({assumptionChanges: z.array(z.strictObject({configurationId: uuid.optional(), assumptionId: z.string().max(300), period: z.string().max(300), approved: text, proposed: text})).max(500), blockProposals: z.array(z.strictObject({blockKey: z.string().max(160), content: z.strictObject({text}), claims: z.array(z.never()), supportIds: z.array(z.never()), detachedClaimIds: z.array(z.string().max(300)).max(500)})).max(1000), observations: z.array(z.strictObject({key: z.string().max(600), kind: z.enum(["formula_changed", "recorded_edited", "invalid_input"]), beforeSha256: hash, afterSha256: hash})).max(20000), conflicts: z.array(z.string().max(600)).max(20000)});
export const artifactImportCandidateSchema = z.union([
  z.strictObject({candidateId: uuid, workId: uuid, artifactId: uuid, status: z.literal("queued"), reason: z.literal("verification_pending"), withheld: z.literal(true)}),
  z.strictObject({candidateId: uuid, workId: uuid, artifactId: uuid, status: z.literal("stale"), reason: z.literal("source_revoked"), withheld: z.literal(true)}),
  z.object({candidateId: uuid, workId: uuid, artifactId: uuid, status: z.enum(["queued", "candidate", "unmatched", "stale", "applied", "discarded"]), reason: z.string().nullable(), withheld: z.literal(false), baseRevisionId: uuid.nullable(), baseManifestFingerprint: hash.nullable(), headRevisionIdAtSubmit: uuid, currentHeadRevisionId: uuid, comparedHeadRevisionId: uuid.nullable(), sourceVersionId: uuid, format: z.enum(["xlsx", "docx", "pptx"]), comparison: comparison.nullable(), contributions: contributions.nullable(), comparisonFingerprint: hash.nullable(), submittedBy: uuid, viewerId: uuid, preparedBy: uuid, policy: z.strictObject({assignmentRequired: z.boolean(), selfApprovalAllowed: z.boolean(), roles: z.array(z.enum(["preparer", "reviewer", "approver"]))}), canApply: z.boolean(), canDiscard: z.boolean(), groups: z.array(z.object({configurationId: uuid, label: z.string(), requiresRebase: z.boolean()})).default([]), pendingConfigurationIds: z.array(uuid).default([]), pendingContributions: z.array(z.unknown()).nullable().transform(value => value ?? []).default([]), decisionId: uuid.nullable(), appliedRevisionId: uuid.nullable(), continuationRequestId: uuid.nullable(), events: z.array(z.object({kind: z.string(), createdAt: z.string(), actorId: uuid, payload: z.record(z.string(), z.unknown())})).max(1000)}),
]);
export type ArtifactImportCandidate = z.infer<typeof artifactImportCandidateSchema>;
