import {describe,expect,it} from "vitest";
import {buildProviderCaseFit,readProviderCaseFitArtifact} from "./provider-case-fit";
const org="00000000-0000-4000-8000-000000000001",project="00000000-0000-4000-8000-000000000002",plan="00000000-0000-4000-8000-000000000003";
const observation=<T>(value:T)=>[{value,provenance:"declared",observedAt:"2026-09-01T00:00:00Z",note:"Mandate version 17; confirmed by provider"}];
const provider=(id:string)=>({providerId:id,name:id,ownerOrganizationId:org,sourceClass:"registered",mandate:{active:observation(true),ticket:observation({min:"100",max:"1000"}),termMonths:observation({min:1,max:60}),sectors:observation(["ports"]),geographies:observation(["BR"]),instruments:observation(["ccb"]),collateral:observation(["imovel"]),leverageCeiling:observation("4"),minimumDscr:observation("1.2"),currencies:observation(["BRL"])}});
const input=()=>({organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64),criteria:{schemaVersion:"provider-case-criteria.v1",asOf:"2026-09-10T00:00:00Z",currency:"BRL",amount:"500",termMonths:24,sector:"ports",geography:"BR",instruments:["ccb"],collateral:["imovel"],leverage:"3",dscr:"1.5",source:{kind:"user_confirmed",referenceId:project}},providers:[provider("A"),provider("B")],mandateMaxAgeMonths:6});
describe("provider case fit",()=>{
 it("explains every fit with case values and dated mandate evidence without contact authorization",()=>{const result=buildProviderCaseFit(input());expect(result.candidates[0]).toMatchObject({verdict:"fits",reviewReadiness:"ready_for_review"});expect(result.candidates[0]!.criteria).toHaveLength(10);expect(result.candidates[0]!.criteria.every(c=>c.evidence.length>0)).toBe(true);expect(result.externalEffectAllowed).toBe(false);expect(result.shortlistAuthorized).toBe(false);expect(readProviderCaseFitArtifact(result,{organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64)})).toEqual(result);});
 it("is stable across loader ordering and dates only against the approved asOf",()=>{const a=input(),b=input();b.providers.reverse();expect(buildProviderCaseFit(a)).toEqual(buildProviderCaseFit(b));});
 it("separates company unknowns from missing mandate and ranks governed candidates first",()=>{const value=input();value.providers[0]!.mandate.ticket=[];const result=buildProviderCaseFit(value);expect(result.candidates.map(c=>c.providerId)).toEqual(["B","A"]);expect(result.candidates[1]!.mandateGaps).toContain("ticket");expect(result.candidates[1]!.companyGaps).not.toContain("ticket");});
 it("excludes actual incompatibility rather than averaging it into a score",()=>{const value=input();value.providers[0]!.mandate.currencies=observation(["USD"]);const result=buildProviderCaseFit(value);expect(result.candidates[1]).toMatchObject({providerId:"A",verdict:"excluded",reviewReadiness:"excluded"});});
 it("does not treat future or directory observations as present mandate",()=>{const value=input();value.providers[0]!.sourceClass="directory";value.providers[1]!.mandate.ticket[0]!.observedAt="2027-01-01T00:00:00Z";const result=buildProviderCaseFit(value);expect(result.candidates.every(c=>c.reviewReadiness==="requires_confirmation")).toBe(true);expect(result.candidates.find(c=>c.providerId==="A")!.criteria.every(c=>c.evidence.length===0)).toBe(true);});
 it("blocks conflicting same-priority evidence and stale mandates",()=>{const value=input();value.providers[0]!.mandate.ticket.push(...observation({min:"200",max:"300"}));value.providers[1]!.mandate.active[0]!.observedAt="2020-01-01T00:00:00Z";const result=buildProviderCaseFit(value);expect(result.candidates.find(c=>c.providerId==="A")!.blockers).toContain("mandate_conflicting:ticket");expect(result.candidates.find(c=>c.providerId==="B")!.blockers).toContain("mandate_stale:active");});
 it("rejects tenant substitution, ambiguous decimals and high precision inverted ranges",()=>{const value=input();value.providers[0]!.ownerOrganizationId=project;expect(()=>buildProviderCaseFit(value)).toThrow("scope");const inverted=input();inverted.providers[0]!.mandate.ticket=observation({min:"100000000000000000000.000000000000000002",max:"100000000000000000000.000000000000000001"});expect(()=>buildProviderCaseFit(inverted)).toThrow("range");expect(()=>buildProviderCaseFit({...input(),criteria:{...input().criteria,amount:"500,00"}})).toThrow();});
 it("invalidates persisted results after case change or tampering",()=>{const result=buildProviderCaseFit(input());result.caseCriteria.amount="900";expect(readProviderCaseFitArtifact(result,{organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64)})).toBeNull();});
});
