import {describe,expect,it} from "vitest";
import {buildProviderCaseFit,readProviderCaseFitArtifact} from "./provider-case-fit";
const org="00000000-0000-4000-8000-000000000001",project="00000000-0000-4000-8000-000000000002",plan="00000000-0000-4000-8000-000000000003";
const observation=<T>(value:T)=>[{value,provenance:"declared",observedAt:"2026-09-01T00:00:00Z",note:"Mandate version 17; confirmed by provider"}];
const provider=(id:string)=>({providerId:id,name:id,ownerOrganizationId:org,sourceClass:"registered",mandate:{active:observation(true),ticket:observation({min:"100",max:"1000"}),termMonths:observation({min:1,max:60}),sectors:observation(["ports"]),geographies:observation(["BR"]),instruments:observation(["ccb"]),collateral:observation(["imovel"]),leverageCeiling:observation("4"),minimumDscr:observation("1.2"),currencies:observation(["BRL"])}});
const input=()=>({organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64),criteria:{schemaVersion:"provider-case-criteria.v1",asOf:"2026-09-10T00:00:00Z",currency:"BRL",amount:"500",termMonths:24,sector:"ports",geography:"BR",instruments:["ccb"],collateral:["imovel"],leverage:"3",dscr:"1.5",source:{kind:"user_confirmed",referenceId:project}},providers:[provider("A"),provider("B")],mandateMaxAgeMonths:6});
const confirmedRecord=(overrides:Record<string,unknown>={})=>({versionNumber:4,status:"confirmed",effectiveStatus:"confirmed",validFrom:"2026-03-01",validUntil:"2027-03-01",confirmedAt:"2026-09-01T00:00:00Z",channel:"official_document",confirmationCount:2,...overrides});
describe("provider case fit",()=>{
 it("explains every fit with case values and dated mandate evidence without contact authorization",()=>{const result=buildProviderCaseFit(input());expect(result.candidates[0]).toMatchObject({verdict:"fits",reviewReadiness:"ready_for_review"});expect(result.candidates[0]!.criteria).toHaveLength(10);expect(result.candidates[0]!.criteria.every(c=>c.evidence.length>0)).toBe(true);expect(result.externalEffectAllowed).toBe(false);expect(result.shortlistAuthorized).toBe(false);expect(readProviderCaseFitArtifact(result,{organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64)})).toEqual(result);});
 it("is stable across loader ordering and dates only against the approved asOf",()=>{const a=input(),b=input();b.providers.reverse();expect(buildProviderCaseFit(a)).toEqual(buildProviderCaseFit(b));});
 it("separates company unknowns from missing mandate and ranks governed candidates first",()=>{const value=input();value.providers[0]!.mandate.ticket=[];const result=buildProviderCaseFit(value);expect(result.candidates.map(c=>c.providerId)).toEqual(["B","A"]);expect(result.candidates[1]!.mandateGaps).toContain("ticket");expect(result.candidates[1]!.companyGaps).not.toContain("ticket");});
 it("excludes actual incompatibility rather than averaging it into a score",()=>{const value=input();value.providers[0]!.mandate.currencies=observation(["USD"]);const result=buildProviderCaseFit(value);expect(result.candidates[1]).toMatchObject({providerId:"A",verdict:"excluded",reviewReadiness:"excluded"});});
 it("does not treat future or directory observations as present mandate",()=>{const value=input();value.providers[0]!.sourceClass="directory";value.providers[1]!.mandate.ticket[0]!.observedAt="2027-01-01T00:00:00Z";const result=buildProviderCaseFit(value);expect(result.candidates.every(c=>c.reviewReadiness==="requires_confirmation")).toBe(true);expect(result.candidates.find(c=>c.providerId==="A")!.criteria.every(c=>c.evidence.length===0)).toBe(true);});
 it("blocks conflicting same-priority evidence and stale mandates",()=>{const value=input();value.providers[0]!.mandate.ticket.push(...observation({min:"200",max:"300"}));value.providers[1]!.mandate.active[0]!.observedAt="2020-01-01T00:00:00Z";const result=buildProviderCaseFit(value);expect(result.candidates.find(c=>c.providerId==="A")!.blockers).toContain("mandate_conflicting:ticket");expect(result.candidates.find(c=>c.providerId==="B")!.blockers).toContain("mandate_stale:active");});
 it("rejects tenant substitution, ambiguous decimals and high precision inverted ranges",()=>{const value=input();value.providers[0]!.ownerOrganizationId=project;expect(()=>buildProviderCaseFit(value)).toThrow("scope");const inverted=input();inverted.providers[0]!.mandate.ticket=observation({min:"100000000000000000000.000000000000000002",max:"100000000000000000000.000000000000000001"});expect(()=>buildProviderCaseFit(inverted)).toThrow("range");expect(()=>buildProviderCaseFit({...input(),criteria:{...input().criteria,amount:"500,00"}})).toThrow();});
 it("keeps a fund with no confirmed mandate as a research hypothesis and still explains it item by item",()=>{const result=buildProviderCaseFit(input());const candidate=result.candidates[0]!;expect(candidate.fit).toMatchObject({classification:"hypothesis",evidenceSource:"public_record",mandateVersion:null,confirmedAt:null,incompatibilities:[]});expect(candidate.mandateRecord).toBeNull();expect(candidate.fit!.adherence.map(a=>a.subject)).toEqual(["instrument","ticket","sector","geography","credit_profile","tenor","collateral"]);expect(candidate.fit!.adherence.every(a=>a.outcome==="fits"&&a.origin==="declared"&&a.observedAt==="2026-09-01T00:00:00Z")).toBe(true);});
 it("promotes a candidate to eligible only on a confirmed mandate inside its window, and names the version and date",()=>{const value=input();value.providers[0]!.mandateRecord=confirmedRecord();const result=buildProviderCaseFit(value);const candidate=result.candidates.find(c=>c.providerId==="A")!;expect(candidate.fit).toMatchObject({classification:"eligible",evidenceSource:"confirmed_mandate",mandateVersion:4,mandateStatus:"confirmed",confirmedAt:"2026-09-01T00:00:00Z",unverified:[]});expect(candidate.mandateRecord).toMatchObject({channel:"official_document",confirmationCount:2});expect(result.candidates.find(c=>c.providerId==="B")!.fit!.classification).toBe("hypothesis");expect(readProviderCaseFitArtifact(result,{organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64)})).toEqual(result);});
 it("never calls an incompatible instrument eligible, however confirmed the mandate is",()=>{const value=input();value.providers[0]!.mandateRecord=confirmedRecord();value.providers[0]!.mandate.instruments=observation(["cri"]);const result=buildProviderCaseFit(value);const candidate=result.candidates.find(c=>c.providerId==="A")!;expect(candidate.fit).toMatchObject({classification:"excluded",incompatibilities:["instrument"]});expect(candidate.fit!.adherence.find(a=>a.subject==="instrument")).toMatchObject({outcome:"excluded",mandate:"cri",request:"ccb"});});
 it("refuses an expired, withdrawn or future confirmation as current interest",()=>{for(const effectiveStatus of ["expired","withdrawn","draft"] as const){const value=input();value.providers[0]!.mandateRecord=confirmedRecord({effectiveStatus});const candidate=buildProviderCaseFit(value).candidates.find(c=>c.providerId==="A")!;expect(candidate.fit).toMatchObject({classification:"hypothesis",evidenceSource:"public_record",mandateStatus:effectiveStatus});}
  const later=input();later.providers[0]!.mandateRecord=confirmedRecord({confirmedAt:"2027-01-01T00:00:00Z"});const candidate=buildProviderCaseFit(later).candidates.find(c=>c.providerId==="A")!;expect(candidate.mandateRecord).toBeNull();expect(candidate.fit!.classification).toBe("hypothesis");});
 it("holds a confirmed mandate at hypothesis while a hard criterion cannot be read from it",()=>{const value=input();value.providers[0]!.mandateRecord=confirmedRecord();value.providers[0]!.mandate.ticket=[];const candidate=buildProviderCaseFit(value).candidates.find(c=>c.providerId==="A")!;expect(candidate.fit).toMatchObject({classification:"hypothesis",evidenceSource:"confirmed_mandate",unverified:["ticket"]});});
 it("invalidates persisted results after case change or tampering",()=>{const result=buildProviderCaseFit(input());result.caseCriteria.amount="900";expect(readProviderCaseFitArtifact(result,{organizationId:org,projectId:project,planId:plan,planFingerprint:"a".repeat(64)})).toBeNull();});
});
