#!/usr/bin/env python3
"""Two genuine human commands on an existing disposable native S11 fixture.
No direct receipt, TaskRun, grant or processing-job insertion is allowed here.
"""
import json,os,subprocess,uuid
from concurrent.futures import ThreadPoolExecutor
from urllib.parse import urlparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
url=os.environ['DATABASE_URL'];target=urlparse(url)
assert target.hostname in ('127.0.0.1','localhost','::1'),'S11 concurrency is local only'
assert target.path.lstrip('/').startswith('offroad_s11_revision_race_'),'Dedicated disposable database required'
PSQL=os.environ.get('PSQL','psql')
def run(sql):
 p=subprocess.run([PSQL,url,'-X','-At','-v','ON_ERROR_STOP=1'],input=sql,text=True,capture_output=True,cwd=ROOT,timeout=60)
 assert p.returncode==0,p.stderr
 return [json.loads(x)for x in p.stdout.splitlines()if x.startswith('{')]
basis=run("""select jsonb_build_object('projectId',b.work_id,'artifactId',b.capital_artifact_id,'revisionId',b.revision_id,'manifestFingerprint',r.manifest_fingerprint,'artifactFingerprint',c.artifact_fingerprint)from private.capital_s11_native_bindings b join public.artifact_revisions r on(r.organization_id,r.id)=(b.organization_id,b.revision_id)join public.capital_project_artifacts c on(c.organization_id,c.id)=(b.organization_id,b.capital_artifact_id)where b.organization_id='a8800000-0000-4000-8000-000000000002'and c.status not in('stale','superseded')order by c.artifact_version desc limit 1;""")
assert len(basis)==1,'A genuine unreturned revised artifact is required'
b=basis[0];command=str(uuid.uuid4())
# IDs and hex fingerprints are generated by PostgreSQL; validate before interpolation.
for key in ('projectId','artifactId','revisionId'):uuid.UUID(b[key])
for key in ('manifestFingerprint','artifactFingerprint'):assert len(b[key])==64 and all(c in '0123456789abcdef'for c in b[key])
sql="""begin;
select set_config('request.jwt.claims','{"sub":"a8800000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select set_config('request.headers','{"x-offroad-workspace":"a8800000-0000-4000-8000-000000000002"}',true);
set local role authenticated;
select public.decide_capital_project_artifact_v2('%s','%s','%s','%s','%s','request_changes','Revisar com as mesmas fontes licenciadas e sem nova pesquisa externa.',false,'%s');
commit;
"""%(b['projectId'],b['artifactId'],b['revisionId'],b['manifestFingerprint'],b['artifactFingerprint'],command)
with ThreadPoolExecutor(max_workers=2)as pool:results=list(pool.map(lambda _:run(sql),range(2)))
# Claims-setting outputs also are JSON; only the actual command receipts count.
receipts=[[x for x in xs if x.get('schemaVersion')=='capital-artifact-decision.v2']for xs in results]
if not all(len(xs)==1 for xs in receipts):
 receipts=[[x for x in xs if 'jobId'in x and 'reviewId'in x]for xs in results]
assert all(len(xs)==1 for xs in receipts),'Both actual human commands must return receipts'
a,c=receipts[0][0],receipts[1][0]
assert a['jobId']==c['jobId'] and a['reviewId']==c['reviewId'],'Concurrent human replay created divergent jobs/reviews'
assert sorted([a['replayed'],c['replayed']])==[False,True],'Exactly one act must commit and one replay'
job=str(uuid.UUID(a['jobId']));review=str(uuid.UUID(a['reviewId']))
oracle=run("""select jsonb_build_object('jobs',count(*),'taskRuns',(select count(*)from public.capital_project_task_runs where processing_job_id='%s'),'eligible',bool_and(private.capital_s11_revision_dispatch_allowed_v1(id)),'fixedScope',bool_and(payload->'capital_task_ids'='["M04","S11"]'::jsonb and payload->'model_budget'='{"max_cost_usd":0.8,"max_calls":1}'::jsonb))from public.processing_jobs where id='%s'and payload->>'revision_review_id'='%s';"""%(job,job,review))[0]
assert oracle=={'jobs':1,'taskRuns':0,'eligible':True,'fixedScope':True},'The single real human act must authorize only the closed prospective job'
print(json.dumps({'eval':'capital_s11_human_return_two_sessions','result':'PASS','humanActs':1,'jobs':1,'clonedTaskRuns':0}))
