#!/usr/bin/env python3
"""Finite native preview through an isolated real Supabase stack, never remote."""
import os,subprocess,sys,json,base64,tempfile,time,uuid,signal,stat
from contextlib import contextmanager
from pathlib import Path
from native_canonical_install_state import canonical_group_installed, canonical_groups_installed
from urllib.parse import urlparse
ROOT=Path(__file__).resolve().parents[2]
def validate(env):
 for key,scheme in [('DATABASE_URL','postgresql'),('OFFROAD_E2E_API_URL','http')]:
  p=urlparse(env.get(key,''));assert p.scheme==scheme and p.hostname in ('localhost','127.0.0.1','::1'),'Loopback disposable stack required'
  assert not p.query and not p.fragment,'Closed target required'
  if scheme=='http':assert not p.username and not p.password and p.path in ('','/'),'Closed API root required'
 key=env.get('OFFROAD_E2E_PUBLISHABLE_KEY','');assert key and not key.startswith('sb_secret_'),'Publishable key required'
 if not key.startswith('sb_publishable_'):
  try:role=json.loads(base64.urlsafe_b64decode(key.split('.')[1]+'==='))['role']
  except Exception:raise AssertionError('Anonymous key required')from None
  assert role=='anon','Anonymous key required'
 assert not any(env.get(k)for k in ['S11_HTTP_FIXTURE','S11_FIXTURE_CONTINUATION','S11_FIXTURE_RENDERER','BRIEF_UI_FIXTURE','BRIEF_DRAFT_IN_TRANSACTION']),'Independent native bootstrap required'
def material_other_family_identity(value):
 assert value.get('schemaVersion')=='material-native-ui-fixture.v1' and value.get('approved') is False, 'Real unapproved native producer fixture required'
 return tuple(str(uuid.UUID(value[key])) for key in ('organizationId','recipeId','revisionId'))
def read_owned_material_fixture(path):
 # Validate and read the same descriptor. Never check a path and reopen it later.
 fd=os.open(path,os.O_RDONLY|os.O_NOFOLLOW|os.O_NONBLOCK)
 try:
  info=os.fstat(fd)
  assert stat.S_ISREG(info.st_mode) and info.st_uid==os.getuid() and stat.S_IMODE(info.st_mode)==0o600, 'Owned private regular fixture required'
  assert info.st_size<=16384, 'Bounded native fixture required'
  chunks=[];total=0
  while True:
   chunk=os.read(fd,16385-total)
   if not chunk:break
   chunks.append(chunk);total+=len(chunk)
   assert total<=16384, 'Bounded native fixture required'
  value=json.loads(b''.join(chunks).decode('utf8'))
  assert isinstance(value,dict), 'Native fixture object required'
  material_other_family_identity(value)
  return value
 finally:os.close(fd)
@contextmanager
def owned_other_family_allocation(env):
 # The separate family is generated by the existing real Auth/Storage/SDK producer. Its
 # physical committed receipt is our identity source; unrelated historical rows are never used.
 namespace=str(uuid.uuid4())
 directory=Path(tempfile.mkdtemp(prefix='offroad-material-ui-',dir='/private/tmp' if sys.platform=='darwin' else '/tmp'))
 target=directory.parent/f'offroad-material-ui-{namespace}'
 directory.rename(target)
 output=target/'fixture.json'
 child=None
 try:
  child=subprocess.Popen(['node',str(ROOT/'scripts/ci/test-material-production-native-sdk.mjs')],cwd=ROOT,env={**env,'MATERIAL_UI_FIXTURE':'1','MATERIAL_UI_NAMESPACE':namespace,'MATERIAL_UI_FIXTURE_OUTPUT':str(output)},stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  deadline=time.monotonic()+180
  while True:
   try:proof=read_owned_material_fixture(output);break
   except (FileNotFoundError,json.JSONDecodeError):
    # The SDK writes once with exclusive create; only missing/partial JSON may wait.
    assert child.poll() is None, 'Owned native other-family producer failed'
    assert time.monotonic()<deadline, 'Owned native other-family producer timed out'
    time.sleep(.1)
  organization,recipe,revision=material_other_family_identity(proof)
  query=f"select a.id from private.material_production_bindings b join private.capital_public_retained_payloads r on(r.organization_id,r.id)=(b.organization_id,b.package_retained_payload_id) join private.capital_public_payload_allocations a on(a.organization_id,a.id)=(r.organization_id,r.allocation_id) where b.organization_id='{organization}' and b.recipe_id='{recipe}' and b.revision_id='{revision}' and a.content_kind='material_body' and private.capital_body_physical_receipt_v1(b.organization_id,r.id);"
  result=subprocess.run(['psql',env['DATABASE_URL'],'-XAtq','-v','ON_ERROR_STOP=1'],input=query,text=True,capture_output=True,cwd=ROOT,check=True)
  allocation=str(uuid.UUID(result.stdout.strip()))
  yield {**env,'PREVIEW_OTHER_FAMILY_ALLOCATION_ID':allocation,'PREVIEW_OTHER_FAMILY_ORGANIZATION_ID':organization}
 finally:
  if child and child.poll() is None:
   child.send_signal(signal.SIGTERM)
   try:child.wait(timeout=15)
   except subprocess.TimeoutExpired:child.kill();child.wait(timeout=5)
  output.unlink(missing_ok=True)
  target.rmdir()
def main():
 if sys.argv[1:]==['--self-test']:
  for db,api in [('postgresql://example.org/db','http://127.0.0.1:54321'),('postgresql://127.0.0.1:54322/postgres','https://example.supabase.co')]:
   try:validate({'DATABASE_URL':db,'OFFROAD_E2E_API_URL':api,'OFFROAD_E2E_PUBLISHABLE_KEY':'sb_publishable_fixture'})
   except AssertionError:pass
   else:raise AssertionError('Remote fixture admitted')
  real={'schemaVersion':'material-native-ui-fixture.v1','approved':False,**{key:str(uuid.uuid4())for key in ('organizationId','recipeId','revisionId')}}
  assert len(material_other_family_identity(real))==3
  for changed in ({**real,'schemaVersion':'fake'}, {**real,'organizationId':'forged'}):
   try:material_other_family_identity(changed)
   except (AssertionError,ValueError):pass
   else:raise AssertionError('Unproved other-family identity admitted')
  with tempfile.TemporaryDirectory() as directory:
   fixture=Path(directory)/'fixture.json'
   try:read_owned_material_fixture(fixture)
   except FileNotFoundError:pass
   else:raise AssertionError('Missing fixture admitted')
   fd=os.open(fixture,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
   with os.fdopen(fd,'w') as out:json.dump(real,out)
   assert read_owned_material_fixture(fixture)==real
   linked=Path(directory)/'linked.json';linked.symlink_to(fixture)
   try:read_owned_material_fixture(linked)
   except OSError:pass
   else:raise AssertionError('Symlink fixture admitted')
   fixture.chmod(0o644)
   try:read_owned_material_fixture(fixture)
   except AssertionError:pass
   else:raise AssertionError('Public fixture admitted')
   fixture.chmod(0o600);fixture.write_text('x'*16385)
   try:read_owned_material_fixture(fixture)
   except AssertionError:pass
   else:raise AssertionError('Oversize fixture admitted')
   fixture.write_text('{')
   try:read_owned_material_fixture(fixture)
   except json.JSONDecodeError:pass
   else:raise AssertionError('Partial fixture admitted')
   fixture.write_text(json.dumps({**real,'schemaVersion':'fake'}))
   try:read_owned_material_fixture(fixture)
   except AssertionError:pass
   else:raise AssertionError('Invalid complete fixture admitted')
  print('capital_preview_portable_target_guard_and_atomic_private_fixture: PASS (no SQL/HTTP)');return
 assert len(sys.argv)==1;env=os.environ.copy();validate(env)
 if env.get('PREVIEW_DRAFTS_IN_LOCAL_STACK')=='1' and not canonical_groups_installed(ROOT,env['DATABASE_URL'],('preview5','preview_storage_job_authority','preview_native_artifact_publication','preview_physical_input_grammar','preview_boundary_validation','preview_review_projection','preview_finalize_bounded_closure')):
  files=['capital_preview_consumed_sources','capital_preview_dispatch_policy','capital_preview_native_consumption','capital_preview_execution_ledger','capital_preview_native_commit','capital_preview_storage_job_authority','capital_preview_native_artifact_publication','capital_preview_physical_input_grammar','capital_preview_boundary_validation','capital_preview_review_projection','capital_preview_finalize_bounded_closure']
  sql='begin;\n'+'\n'.join((ROOT/'supabase/pending'/f'{name}.sql').read_text()for name in files)+'\ncommit;'
  subprocess.run(['psql',env['DATABASE_URL'],'-Xq','-v','ON_ERROR_STOP=1'],input=sql,text=True,env=env,cwd=ROOT,check=True)
 if env.get('PREVIEW_INTEGRATED_REVIEW_EVAL')=='1' and env.get('PREVIEW_REVIEW_DRAFT_IN_LOCAL_STACK')=='1' and not canonical_group_installed(ROOT,env['DATABASE_URL'],'review1'):
  draft=ROOT/'supabase/pending/work_review_dashboard.sql'
  assert draft.is_file(),'Frozen 3W review wrappers required'
  subprocess.run(['psql',env['DATABASE_URL'],'-Xq','-v','ON_ERROR_STOP=1'],input='begin;\n'+draft.read_text()+'\ncommit;',text=True,env=env,cwd=ROOT,check=True)
 # Source16 requires the current complete preview closure, installed above.
 # Canonical stacks skip DDL through the same two-group journal guard; eval never skips.
 metadata_env={**env,'OFFROAD_WORK_REVIEW_DRAFT_INSTALL':'isolated-loopback-ci'}
 subprocess.run([sys.executable,str(ROOT/'scripts/ci/install-work-review-dashboard-metadata-ci-draft.py')],env=metadata_env,cwd=ROOT,check=True)
 subprocess.run(['psql',env['DATABASE_URL'],'-Xq','-v','ON_ERROR_STOP=1','-f',str(ROOT/'supabase/tests/support/work_review_dashboard_metadata.sql')],env=env,cwd=ROOT,check=True)
 for name in ('capital_preview_storage_job_authority','capital_preview_native_artifact_publication','capital_preview_dispatch_policy','capital_preview_boundary_validation','capital_preview_review_projection','capital_preview_finalize_bounded_closure'):
  subprocess.run(['psql',env['DATABASE_URL'],'-Xq','-v','ON_ERROR_STOP=1','-f',str(ROOT/'supabase/tests/support'/f'{name}.sql')],env=env,cwd=ROOT,check=True)
 env['PREVIEW_HTTP_FIXTURE']='1';env.setdefault('PREVIEW_HTTP_NAMESPACE','a8830001')
 loader=next((ROOT/'node_modules/.pnpm').glob('tsx@*/node_modules/tsx/dist/loader.mjs'))
 sdk=['node','--import',str(loader),str(ROOT/'apps/document-worker/scripts/capital-preview-native-sdk-eval.ts')]
 subprocess.run(['pnpm','exec','tsc','-p','apps/document-worker/scripts/tsconfig-capital-preview-sdk-eval.json'],env=env,cwd=ROOT,check=True)
 subprocess.run(sdk+['--self-test'],env=env,cwd=ROOT,check=True)
 with owned_other_family_allocation(env) as owned_env:
  subprocess.run([sys.executable,str(ROOT/'scripts/ci/test-execution-brief-native-agent.py')],env=owned_env,cwd=ROOT,check=True)
  subprocess.run(sdk,env=owned_env,cwd=ROOT,check=True)
if __name__=='__main__':main()
