import {describe,it,expect} from "vitest";
import {institutionalInputFixture} from "./institutional-input.fixture";
import {buildInitialInstitutionalConfigurationCandidate} from "./institutional-configuration";
import {calculateApprovedInstitutionalScenarios,institutionalModelRuntimeContextSchema} from "./institutional-runtime";
function fixture(){const f=institutionalInputFixture();const actor="11111111-1111-4111-8111-111111111111";const sources=f.sources.map(s=>({...s,metadataEvidence:{locator:"Page 1",rationale:"Reviewed units"},reviewedBy:actor,reviewedAt:"2026-09-10T04:00:00Z"}));const currentSources=f.sources.map(s=>({...s,hashVerified:true}));const proposal=buildInitialInstitutionalConfigurationCandidate({...f,currentSources,reviewedSources:sources,actorId:actor,submissionId:actor,submittedAt:"2026-09-10T04:01:00Z"});if(proposal.status!=="review_required")throw new Error("Invalid fixture");return {facts:f.facts,context:institutionalModelRuntimeContextSchema.parse({projectId:actor,sourceManifestFingerprint:"a".repeat(64),currentSources,candidates:[],approvedConfigurations:[{id:actor,revision:1,fingerprint:proposal.configurationFingerprint,configuration:proposal.configuration,reviewedBy:actor,reviewedAt:"2026-09-10T04:02:00Z",sourceBindings:sources}],reviewedSources:sources,pendingSetup:null})};}
describe("institutional runtime source and approval boundary",()=>{
 it("selects only the current approved configuration; history is not a requested comparison",()=>{const f=fixture();f.context.approvedConfigurations.push({...f.context.approvedConfigurations[0]!,id:"22222222-2222-4222-8222-222222222222",revision:2});f.context.approvedConfigurations[0]!.configuration={...f.context.approvedConfigurations[0]!.configuration,currency:"USD"};const result=calculateApprovedInstitutionalScenarios(f);expect(result.status).toBe("ready");if(result.status!=="ready")return;expect(result.scenarios.map(s=>s.revision)).toEqual([2]);});
 it("blocks altered reviewed configuration economics and unverified sources",()=>{const f=fixture();f.context.approvedConfigurations[0]!.configuration.currency="USD";expect(calculateApprovedInstitutionalScenarios(f)).toMatchObject({status:"blocked",blockers:["institutional_configuration_fingerprint_mismatch"]});const other=fixture();other.context.currentSources[0]!.hashVerified=false;expect(calculateApprovedInstitutionalScenarios(other)).toMatchObject({status:"blocked",blockers:["institutional_approved_source_stale"]});});
});
