import {describe,it,expect} from "vitest";
import {institutionalInputFixture} from "./institutional-input.fixture";
import {buildInitialInstitutionalConfigurationCandidate as build,institutionalModelConfigurationSchema} from "./institutional-configuration";
const actor="11111111-1111-4111-8111-111111111111";
function fixture(){const f=institutionalInputFixture();return {...f,reviewedSources:f.sources.map(s=>({...s,metadataEvidence:{locator:"Financial statements page1",rationale:"Reviewed denomination of extracted amounts"},reviewedBy:actor,reviewedAt:"2026-09-10T03:00:00Z"})),currentSources:f.sources.map(s=>({sourceDocument:s.sourceDocument,version:s.version,hash:s.hash,hashVerified:true})),actorId:actor,submittedAt:"2026-09-10T03:01:00Z",submissionId:actor};}
describe("initial institutional configuration producer",()=>{
 it("binds real selections and explicitly proposed premises without auto-approval",()=>{const input=fixture();const result=build(input);expect(result.status).toBe("review_required");if(result.status!=="review_required")return;expect(result.configuration.assumptionBook.assumptions.every(a=>a.sourceType==="offroad_scenario"&&a.evidence.length===0)).toBe(true);expect(result.configuration.assumptionBook.overrides?.every(o=>o.requestedBy===actor)).toBe(true);expect(result.willExecute).toBe(false);expect(result.lineage.length).toBeGreaterThan(0);expect(input.configuration.assumptionBook.assumptions[0]!.sourceType).toBe("company_budget");});
 it("rejects arbitrary keys and malformed financial strings",()=>{const input=fixture();expect(()=>institutionalModelConfigurationSchema.parse({...input.configuration,automaticApproval:true})).toThrow();input.configuration.assumptionBook.assumptions[0]!.values={"2027":"NaN"};expect(()=>build(input)).toThrow();});
 it("rejects stale or unverified source manifests",()=>{const input=fixture();input.currentSources[0]!.hashVerified=false;expect(()=>build(input)).toThrow("source_review_stale");});
 it("returns missing historical mappings without synthetic balances",()=>{const input=fixture();input.facts=input.facts.filter(f=>!f.key.fieldPath.endsWith("restricted_cash"));const result=build(input);expect(result.status).toBe("missing_inputs");if(result.status!=="missing_inputs")throw new Error("Expected missing inputs");expect(result.prepared.input).toBeNull();});
 it("blocks an instrument ledger that disagrees with the opening historical debt",()=>{const input=fixture();input.configuration.debtInstruments[0]!.openingPrincipal="999";expect(build(input)).toMatchObject({status:"calculation_blocked",willExecute:false});});
});
