import type {CapabilityLedger, CapabilityLedgerEntry} from "./capability-ledger";

const verifiedAt = "2026-09-07T02:16:11.000-03:00";

function entry(input: Omit<CapabilityLedgerEntry, "verifiedAt">): CapabilityLedgerEntry {
  return {...input, verifiedAt};
}

const entries: CapabilityLedgerEntry[] = [
  entry({capabilityId: "workspace.project-memory", category: "workspace", name: "Project workspace and persistent case objects", availability: "live", exposure: "universal", qualityMaturity: "tested", exactScope: "Authenticated project, conversation, file and artifact persistence in the current product", specRefs: ["docs/product/PRODUCT_WORKFLOW.md"], runtimeRefs: ["apps/web/src/app/[locale]/app/projects/[projectId]"], evidenceRefs: ["apps/web/e2e/document-first-intake.spec.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Longitudinal cross-stage economic continuity is not yet proven across G1-G8"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "documents.known-format-intake", category: "documents", name: "Known-format upload and document processing", availability: "live", exposure: "universal", qualityMaturity: "implemented", exactScope: "Current supported upload formats and existing intake routes", specRefs: ["docs/product/PRODUCT_WORKFLOW.md"], runtimeRefs: ["apps/document-worker/src"], evidenceRefs: ["apps/document-worker/src/case-analysis.test.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Arbitrary data-room recall, hostile corpus coverage and all-format fidelity remain unproved"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "documents.arbitrary-dataroom", category: "documents", name: "Arbitrary data-room understanding", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Multi-format arbitrary client data room with completeness and citation coverage", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["No end-to-end proof over a representative arbitrary corpus"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "intent.semantic-envelope-shadow", category: "intent", name: "Semantic intent envelope in shadow", availability: "shadow", exposure: "internal", qualityMaturity: "implemented", exactScope: "Intent envelope recorded beside production routing without deciding execution", specRefs: ["docs/product/CANONICAL_INTENT_WORKFLOW_ATLAS.md"], runtimeRefs: ["apps/document-worker/src/intent-shadow.ts"], evidenceRefs: ["supabase/tests/intent_envelopes_shadow.sql"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Shadow classifier does not govern the universal production route"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "intent.semantic-router-preview", category: "intent", name: "Semantic turn router", availability: "live", exposure: "allowlisted", qualityMaturity: "tested", exactScope: "Allowlisted live_intelligence_preview projects and supported compositions", specRefs: ["docs/build/LIVE_INTELLIGENCE_PREVIEW.md"], runtimeRefs: ["apps/document-worker/src/preview"], evidenceRefs: ["docs/build/LIVE_INTELLIGENCE_PREVIEW.md"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Five supported compositions; not the universal production router"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.taskspec-library", category: "workflow", name: "Canonical TaskSpec allowlist", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Eighty target TaskSpecs and dependency contracts", specRefs: ["packages/work-plan/src/task-registry.ts"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Registry presence does not mean executor, interface or production capability"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "workflow.case01-compiler", category: "workflow", name: "Case 01 preview compiler", availability: "live", exposure: "allowlisted", qualityMaturity: "tested", exactScope: "Supported Camil Case 01 preview composition and its bounded branches", specRefs: ["docs/build/INTEGRATION_PREVIEW.md"], runtimeRefs: ["apps/document-worker/src/preview/workflow.ts"], evidenceRefs: [".github/workflows/live-preview-gate.yml"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Chain is case-bound and cannot represent the complete Atlas"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.objective-plan-core", category: "workflow", name: "Deterministic objective-to-plan core", availability: "live", exposure: "internal", qualityMaturity: "tested", exactScope: "Ten normalized objective classes compile to allowlisted output terminals, source and analysis plans, and minimal dependency-closed TaskSpec graphs; supported new-project entry classification consumes the same contract", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md", "docs/adr/0021-intent-driven-workflow-atlas.md"], runtimeRefs: ["packages/work-plan/src/objective-plan.ts", "packages/work-plan/src/job-inference.ts"], evidenceRefs: ["packages/work-plan/src/objective-plan.test.ts", "packages/work-plan/src/job-inference.test.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Semantic Intent Envelope remains shadow; objective-specific graphs are persisted only as shadow observations and are not dispatched by the general specialist runtime"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.preflight-capability-gate", category: "workflow", name: "Fail-closed task execution preflight", availability: "live", exposure: "internal", qualityMaturity: "tested", exactScope: "Pure preflight contract that evaluates every compiled TaskSpec against an exact live executor and procedure binding, exposure, intended use, authority, evidence regime, data and source classes, provider and tool allowlists, dependency reachability and kill switches", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["packages/work-plan/src/execution-readiness.ts"], evidenceRefs: ["packages/work-plan/src/execution-readiness.test.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["The gate is not yet connected to persisted plan activation; the current TaskSpec registry remains unbound and therefore correctly fails closed"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.objective-preflight-shadow", category: "workflow", name: "Persisted objective-plan preflight observation", availability: "shadow", exposure: "internal", qualityMaturity: "implemented", exactScope: "Every standard activation with a project compiles an objective-specific graph, evaluates it against the truthful universal capability inventory and records the immutable plan and readiness decision through the exact leased job capability", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["apps/document-worker/src/agent-operation-brief.ts", "supabase/migrations/20260907044240_objective_plan_preflight.sql"], evidenceRefs: ["apps/document-worker/src/agent-operation-brief.test.ts", "apps/document-worker/src/queue.test.ts", "supabase/tests/objective_plan_preflight.sql"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Observation is fail-closed but does not authorize or block the released fixed rail; no general TaskSpec dispatcher is promoted"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.composable-specialization-shadow", category: "workflow", name: "Composable objective specialization", availability: "shadow", exposure: "internal", qualityMaturity: "implemented", exactScope: "Objective text and governed semantic activation keys compose reusable DCM core, economic objective, analysis, instrument and jurisdiction packs with dependency closure, requirement lineage, procedures, calculations, disconfirmers, quality gates, maturity and explicit unmatched needs persisted beside the objective preflight", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["packages/dcm-specialization/src/index.ts", "apps/document-worker/src/agent-operation-brief.ts", "supabase/migrations/20260907044243_objective_specialization_shadow.sql"], evidenceRefs: ["packages/dcm-specialization/src/index.test.ts", "apps/document-worker/src/agent-operation-brief.test.ts", "apps/document-worker/src/queue.test.ts", "supabase/tests/objective_plan_preflight.sql"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Compatibility activation remains lexical until the semantic envelope is promoted", "All current DCM packs are implemented but unreviewed and therefore cannot claim tested or production maturity", "Composition records required expertise but does not authorize a general executor"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.specialist-method-binding-shadow", category: "workflow", name: "Objective-specific specialist method binding", availability: "shadow", exposure: "internal", qualityMaturity: "implemented", exactScope: "Selected depth packs add specialist TaskSpecs to the objective graph and bind them to exact method, executor and result-contract versions from a runtime manifest verified against the canonical Markdown library; ambiguity remains a named conflict", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["packages/dcm-specialization/src/method-binding.ts", "packages/credit-playbook/src/method-runtime-manifest.ts", "apps/document-worker/src/agent-operation-brief.ts", "supabase/migrations/20260907044246_objective_method_binding_shadow.sql"], evidenceRefs: ["packages/dcm-specialization/src/method-binding.test.ts", "packages/credit-playbook/src/method-runtime-manifest.test.ts", "apps/document-worker/src/agent-operation-brief.test.ts", "apps/document-worker/src/queue.test.ts", "supabase/tests/objective_plan_preflight.sql"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Only the receivables-underwriting specialist task has a runtime binding", "The method is implemented but not independently reviewed or promoted", "A method binding does not create a live TaskExecutionCapability or authorize dispatch"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "workflow.universal-compiler", category: "workflow", name: "Objective-to-plan universal workflow compiler", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Dynamic graph from objective, objects, evidence, packs, tools, checkpoints and work products", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Current compiler cannot create structurally different graphs for the full Atlas"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "execution.case01-specialists", category: "execution", name: "Bounded specialist execution for Case 01", availability: "live", exposure: "allowlisted", qualityMaturity: "tested", exactScope: "Nine implemented methods and preview synthesis used by the Case 01 gate", specRefs: ["docs/build/WORKFLOW_SYSTEM_PLAN.md"], runtimeRefs: ["packages/credit-playbook/src/executors", "apps/document-worker/src/preview"], evidenceRefs: [".github/workflows/live-preview-gate.yml"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Does not prove a general specialist runtime or other economic packs"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "execution.general-specialist-runtime", category: "execution", name: "General bounded specialist runtime", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Procedure-bound specialists for all promoted workflow compositions", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["No universal dispatch from compiled TaskSpecs to promoted methods"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "finance.deterministic-kernels", category: "finance", name: "Deterministic finance kernels", availability: "live", exposure: "internal", qualityMaturity: "implemented", exactScope: "Implemented formulas for debt, liquidity, covenant, cost and selected scenario calculations", specRefs: ["docs/build/WORKFLOW_SYSTEM_PLAN.md"], runtimeRefs: ["packages/financial-core/src"], evidenceRefs: ["packages/financial-core/src/index.test.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["A collection of kernels is not an integrated institutional model"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "finance.integrated-institutional-model", category: "finance", name: "Integrated institutional credit model", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Driver-based statements, cash flow, debt service, tax, scenarios and editable assumptions", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["No promoted end-to-end model with sector drivers and balance-sheet closure"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "artifacts.basic-docx-xlsx-preview", category: "artifacts", name: "Basic Word and Excel generation", availability: "live", exposure: "allowlisted", qualityMaturity: "tested", exactScope: "Preview Word and spreadsheet generated from signed Case 01 objects", specRefs: ["docs/build/LIVE_INTELLIGENCE_PREVIEW.md"], runtimeRefs: ["packages/case-export/src", "packages/case-render/src"], evidenceRefs: [".github/workflows/live-preview-gate.yml"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Basic generation does not meet top-tier work-product or client-template fidelity gates"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "artifacts.template-faithful-suite", category: "artifacts", name: "Template-faithful work-product suite", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Native editable XLSX, PPTX and DOCX using client templates with financial and visual QA", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Reference model, board deck, meeting pack and review artifacts are not yet approved"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "review.universal-verifier", category: "review", name: "Universal financial, evidence and artifact verifier", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Responsibility-aware review of source, math, completeness, narrative and visual consistency", specRefs: ["docs/product/CANONICAL_INTENT_WORKFLOW_ATLAS.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Current gates are narrower and do not cover every intent and work product"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "capital.synthetic-matching", category: "capital", name: "Matching logic over synthetic mandates", availability: "mocked", exposure: "internal", qualityMaturity: "implemented", exactScope: "Schema and initial fit/exclusion logic exercised with controlled mandates", specRefs: ["docs/product/PRODUCT_WORKFLOW.md"], runtimeRefs: ["packages/fund-mandate/src", "packages/matching-core/src"], evidenceRefs: ["packages/fund-mandate/src/market-truth.test.ts"], fixtureRefs: ["packages/testing-fixtures/src"], allowedUses: ["internal_validation"], limitations: ["No sufficient live mandate population, freshness proof or market feedback density"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "capital.live-mandate-network", category: "capital", name: "Live governed mandate and lender network", availability: "absent", exposure: "none", qualityMaturity: "unsupported", exactScope: "Current differentiated investor and lender mandates with feedback-driven fit", specRefs: [], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Real mandate acquisition, update, consent and coverage are not in place"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "continuity.case01-incremental", category: "continuity", name: "Case 01 incremental update", availability: "live", exposure: "allowlisted", qualityMaturity: "tested", exactScope: "Answer, premise change, selective recomputation and artifact versioning in the preview journey", specRefs: ["docs/build/LIVE_INTELLIGENCE_PREVIEW.md"], runtimeRefs: ["apps/document-worker/src/preview"], evidenceRefs: [".github/workflows/live-preview-gate.yml"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Continuity is proven inside one bounded preview journey only"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "continuity.longitudinal-project", category: "continuity", name: "Longitudinal project from question to capital connection", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Persistent economic state across analysis, decision, structure, materials, market and feedback", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Cross-stage G1-G8 continuity is not implemented"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "trust.release-and-assurance-gates", category: "trust", name: "Trust release and assurance gates", availability: "live", exposure: "internal", qualityMaturity: "tested", exactScope: "Deterministic release, control-register and assurance-claim validation", specRefs: ["docs/security/ENTERPRISE_SECURITY_COMPLIANCE_READINESS_PLAN.md"], runtimeRefs: ["packages/release-governance/src/trust-controls.ts", "packages/release-governance/src/control-register.ts"], evidenceRefs: ["packages/release-governance/src/trust-controls.test.ts", "packages/release-governance/src/control-register.test.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Control current state and evidence population remain incomplete"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "trust.worker-schema-boot-gate", category: "trust", name: "Fail-closed worker and database compatibility gate", availability: "live", exposure: "internal", qualityMaturity: "implemented", exactScope: "An authenticated document-worker task verifies the exact database runtime contract before constructing the queue or claiming customer work", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["apps/document-worker/src/runtime-schema.ts", "apps/document-worker/src/main.ts", "supabase/migrations/20260907051611_worker_runtime_schema_contract.sql"], evidenceRefs: ["apps/document-worker/src/runtime-schema.test.ts", "supabase/tests/worker_runtime_schema_contract.sql", "docs/build/ACCEPTANCE_EVIDENCE.md"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Every future schema-dependent worker change must bump the database and image contract together; operational maturity requires the first guarded ECS rollout to stabilise"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "trust.enterprise-assurance", category: "trust", name: "Enterprise assurance and independent assessment", availability: "absent", exposure: "none", qualityMaturity: "unsupported", exactScope: "Operating controls, independent pentest, SOC 2 Type II examination and ISO/IEC 27001 certification", specRefs: [], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["External assessment and operating-period evidence do not exist yet"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "experience.execution-brief", category: "experience", name: "Intent-specific Execution Brief", availability: "live", exposure: "universal", qualityMaturity: "implemented", exactScope: "Deterministic compiler, immutable history, governed adjustment and safe visible projection for sources, analyses, dependencies, checkpoints and delivery before substantive work", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md", "docs/product/EXECUTION_BRIEF_CONTRACT.md"], runtimeRefs: ["apps/document-worker/src/execution-brief.ts", "apps/web/src/components/advisor/execution-brief-card.tsx", "supabase/migrations/20260907044208_execution_brief_foundation.sql", "supabase/migrations/20260907044216_governed_execution_brief_edits.sql"], evidenceRefs: ["packages/work-plan/src/execution-brief.test.ts", "supabase/tests/execution_brief_foundation.sql", "apps/web/e2e/integration-preview-case01.spec.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Only G1 currently has an end-to-end journey gate; objective-specific dynamic graphs are not yet persisted and dispatched across G2-G8"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "experience.live-work", category: "experience", name: "Live Work execution stream", availability: "live", exposure: "universal", qualityMaturity: "implemented", exactScope: "Customer-safe workstream progress derived from real task runs, with no internal TaskSpec identifiers", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: ["supabase/migrations/20260907044208_execution_brief_foundation.sql", "apps/web/src/components/advisor/execution-brief-card.tsx"], evidenceRefs: ["supabase/tests/execution_brief_foundation.sql", "apps/web/e2e/integration-preview-case01.spec.ts"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["Narrative workstream events and safe pause/resume controls remain incomplete"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "experience.premium-workbench", category: "experience", name: "Premium decision and artifact workbench", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Integrated chat, Vault, model, traces, findings, scenarios and work products", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Current project UI is not the target experience and no prototype is authoritative"], verificationMethod: "repository_inspection"}),
  entry({capabilityId: "gold.g1-case01-regression", category: "gold", name: "G1 Case 01 bounded regression", availability: "live", exposure: "internal", qualityMaturity: "tested", exactScope: "Current recorded Case 01 paraphrase and incremental preview gate", specRefs: ["docs/product/gold-cases/"], runtimeRefs: [".github/workflows/live-preview-gate.yml"], evidenceRefs: ["docs/build/LIVE_INTELLIGENCE_PREVIEW.md"], fixtureRefs: [], allowedUses: ["internal_validation"], limitations: ["A passing bounded regression is not a complete founder acceptance journey"], verificationMethod: "controlled_execution"}),
  entry({capabilityId: "gold.g2-g8-reference-journeys", category: "gold", name: "G2-G8 longitudinal reference journeys", availability: "specified", exposure: "none", qualityMaturity: "specified", exactScope: "Seven additional gold journeys with work products, adversarials and benchmark", specRefs: ["docs/build/OFFROAD_ENDGAME_EXECUTION_BLUEPRINT.md", "packages/evals/src/longitudinal-journeys.ts"], runtimeRefs: [], evidenceRefs: [], fixtureRefs: [], allowedUses: [], limitations: ["Contracts are complete; reference work products and runtime execution remain to be completed"], verificationMethod: "repository_inspection"}),
];

export const currentCapabilityLedger: CapabilityLedger = {
  ledgerVersion: "2026.09.07-v9",
  baselineCommit: "744bbfcaf76c",
  generatedAt: verifiedAt,
  entries,
};
