import {describe,expect,it,vi} from "vitest";
import type {SupabaseClient} from "@supabase/supabase-js";
import type {Database} from "@/types/database";
import {loadReceivablesTemporalReport} from "./temporal-report";
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const source={sourceDocumentId:id(1),documentVersion:1,contentKind:"document_layer",sourceSha256:"a".repeat(64),contentSha256:"b".repeat(64),schemaVersion:"2026.08.28-v1",fileName:"Pool.xlsx"};
const context={state:"current",sourceManifest:{schemaVersion:"receivables-evidence-manifest.v1",fingerprint:"c".repeat(64),sources:[source]},candidates:[{documentId:id(1),fileName:"Pool.xlsx",sheet:"A",headerRow:1}],scope:{schemaVersion:"receivables-evidence-scope.v1",id:id(2),fingerprint:"d".repeat(64),sourceManifestFingerprint:"c".repeat(64),primaryTape:{documentId:id(1),sheet:"A",headerRow:1},complementDocumentIds:[],reportingDate:"2026-08-31",sourceRevisions:[source],confirmedBy:id(3),confirmedAt:"2026-09-08T12:00:00Z"}};
const state={fingerprint:"f".repeat(64),manifestFingerprint:"e".repeat(64),receivablesVertical:{evidenceScope:{id:id(2),fingerprint:"d".repeat(64)},sourceManifest:context.sourceManifest,supportPeriodAssessment:{schemaVersion:"receivables-support-periods.v1",reportingDate:"2026-08-31",entries:[{id:"retained-entry"}]}}};
function db(change:Record<string,unknown>={}){const data:Record<string,unknown>={document_intake_sessions:{updated_at:"2026-09-08T12:05:00Z",current_run_id:id(4),result_summary:{case_state:state,case_manifest:{id:id(5),fingerprint:"e".repeat(64),input_fingerprint:"f".repeat(64)}}},case_artifact_manifests:{processing_run_id:id(4),created_at:"2026-09-08T12:05:00Z",manifest_fingerprint:"e".repeat(64),input_fingerprint:"f".repeat(64)},processing_jobs:[{status:"succeeded",created_at:"2026-09-08T12:03:00Z"}],...change};const calls:string[]=[];return {calls,client:{rpc:vi.fn().mockResolvedValue({data:change.freshScope??context,error:null}),from:(table:string)=>{calls.push(table);const value=table==="document_intake_sessions"&&calls.filter(name=>name===table).length>1?(change.freshSession??data[table]):data[table];const query={select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),order:vi.fn().mockReturnThis(),limit:()=>Promise.resolve({data:value,error:null}),maybeSingle:()=>Promise.resolve({data:value,error:null})};return query;}} as unknown as SupabaseClient<Database>};}
describe("current project temporal result",()=>{
 it("loads current result without requiring or reopening preliminary/understanding approval",async()=>{const {client,calls}=db();expect(await loadReceivablesTemporalReport(client,id(6),id(7),context)).toEqual(state);expect(calls).toEqual(["document_intake_sessions","case_artifact_manifests","processing_jobs","document_intake_sessions"]);});
 it("rejects a prior snapshot when a newer job in the same run succeeded",async()=>{expect(await loadReceivablesTemporalReport(db({processing_jobs:[{status:"succeeded",created_at:"2026-09-08T12:06:00Z"}]}).client,id(6),id(7),context)).toBeNull();});
 it("rejects sources replaced while reading the published result",async()=>{expect(await loadReceivablesTemporalReport(db({freshScope:{...context,state:"stale"}}).client,id(6),id(7),context)).toBeNull();});
 it("rejects a session changed during result lookup",async()=>{expect(await loadReceivablesTemporalReport(db({freshSession:{current_run_id:id(9),updated_at:"2026-09-08T12:06:00Z"}}).client,id(6),id(7),context)).toBeNull();});
 it("rejects unfinished runs",async()=>{expect(await loadReceivablesTemporalReport(db({processing_jobs:[{status:"leased"}]}).client,id(6),id(7),context)).toBeNull();});
 it("rejects a newer confirmed scope over an old report",async()=>{expect(await loadReceivablesTemporalReport(db().client,id(6),id(7),{...context,scope:{...context.scope,id:id(8)}})).toBeNull();});
 it("rejects an old manifest run despite completed jobs",async()=>{expect(await loadReceivablesTemporalReport(db({case_artifact_manifests:{processing_run_id:id(8),created_at:"2026-09-08T12:05:00Z",manifest_fingerprint:"e".repeat(64),input_fingerprint:"f".repeat(64)}}).client,id(6),id(7),context)).toBeNull();});
 it("fails closed when scope sources are stale",async()=>{const {client,calls}=db();expect(await loadReceivablesTemporalReport(client,id(6),id(7),{...context,state:"stale"})).toBeNull();expect(calls).toEqual([]);});
});
