import {canonicalProcedureSchema, compileProcedureRegistry, type CanonicalProcedure} from "../procedure-contract";
import {referenceDataKeys} from "../reference-data";

const VERSION = "2026.08.26-v1";
const SOURCE = "packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";

type Spec = {
  id: `MK-${string}`;
  slug: string;
  title: string;
  product: string;
  method: string[];
  verification: string[];
  referenceKeys: string[];
};

const specs: Spec[] = [
  {id:"MK-01",slug:"high-grade",title:"Fundos de crédito high grade",product:"Enquadramento high grade com condições de entrada verificadas",referenceKeys:["market.mandates"],method:["Classificar o veículo somente quando auditoria, governança, instrumento, liquidez e perfil de risco observados forem compatíveis com o mandato high grade.","Excluir caso condicional ou com ressalva material antes de ordenar qualquer nome."],verification:["Conferir cada condição contra registro de mandato datado.","Bloquear inclusão por reputação genérica do gestor ou por rótulo comercial do fundo."]},
  {id:"MK-02",slug:"high-yield-special-situations",title:"High yield e special situations",product:"Enquadramento de complexidade, colateral e saída",referenceKeys:["market.mandates"],method:["Identificar problema nomeado, mecanismo de solução, valor de execução do colateral e caminho de saída.","Usar este universo para casos condicionais compatíveis, sem empurrar preço de special situations para caso limpo."],verification:["Exigir suporte para colateral e saída, não somente laudo ou narrativa.","Bloquear quando a complexidade não tiver tratamento estrutural explícito."]},
  {id:"MK-03",slug:"dedicated-mandates",title:"Assets com mandato dedicado",product:"Elegibilidade por tese e regulamento",referenceKeys:["market.mandates"],method:["Ler regulamento e material público vigente antes de classificar tese, instrumento, ativo e restrições.","Registrar limite e fonte no mandato governado e citar a regra no racional."],verification:["Rejeitar qualquer item fora do regulamento.","Bloquear filtro derivado de resumo comercial sem documento verificável."]},
  {id:"MK-04",slug:"fidc-managers-vehicles",title:"Gestores e veículos FIDC",product:"Enquadramento separado de gestora, veículo, carteira e estrutura",referenceKeys:["market.mandates"],method:["Separar gestora, veículo, regulamento, direitos creditórios, cedente, originador, sacados, prestadores e subordinação.","Avaliar loan tape, elegibilidade, perdas, concentração, retenção e servicing conforme a tese específica."],verification:["Nunca tratar FIDC como instrumento genérico ou sinônimo de carteira.","Bloquear rota quando o direito creditório, o veículo ou o mandato não estiver identificado."]},
  {id:"MK-05",slug:"family-offices",title:"Family offices",product:"Apetite idiossincrático datado e contato adequado",referenceKeys:["market.mandates","policy.market.mandate_max_age"],method:["Registrar setores, sponsor, ticket, forma de decisão e apetite declarado com data e autor.","Usar apresentação curta somente após confirmar que o apetite continua vigente."],verification:["Remover de hard filters todo apetite vencido.","Não inferir mandato institucional a partir de uma operação isolada do principal."]},
  {id:"MK-06",slug:"mid-sized-banks",title:"Bancos médios",product:"Rota bancária comparável e requisitos acessórios explícitos",referenceKeys:["market.mandates"],method:["Mapear garantia, relacionamento acessório, possibilidade de CCB cedível e requisitos de crédito do banco.","Comparar esta rota com a alternativa privada usando mesma base econômica e operacional."],verification:["Expor folha, câmbio, cobrança ou reciprocidade quando fizerem parte da economia.","Não apresentar banco como fundo nem omitir a alternativa quando ela for melhor para a companhia."]},
  {id:"MK-07",slug:"securitizers",title:"Securitizadoras",product:"Rota de emissão com lastro, custo e prazo",referenceKeys:["market.mandates"],method:["Tratar securitizadora como veículo e prestador da rota CRI ou CRA, nunca como investidor final.","Comparar prazo de emissão, custo total, padronização e capacidade de distribuição somente após confirmar o lastro."],verification:["Bloquear rota sem lastro elegível.","Separar claramente securitizadora, coordenador e comprador final no registro."]},
  {id:"MK-08",slug:"factors-forfait",title:"Factors e forfait",product:"Enquadramento de liquidez de recebíveis e seus gatilhos",referenceKeys:["market.mandates"],method:["Mapear documentação, recurso, elegibilidade, concentração, recompra, controles e preço do produto específico.","Usar como destino somente quando o ativo e a urgência forem compatíveis; caso contrário, manter como benchmark."],verification:["Não generalizar factor como credor corporativo irrestrito.","Abrir custo, controle e recurso antes de afirmar comparabilidade."]},
  {id:"MK-09",slug:"infrastructure-real-estate",title:"Fundos de infra e imobiliários",product:"Aderência do fluxo segregado e do contrato de projeto",referenceKeys:["market.mandates"],method:["Ler contrato, contraparte, término, cascata, conta vinculada, construção, operação, garantias e suporte do sponsor.","Exigir estrutura segregada desenhada antes de classificar o caso como aderente."],verification:["Bloquear intenção de SPE sem mecânica ou contratos.","Confirmar que prazo, indexador e riscos cabem no veículo específico."]},
  {id:"MK-10",slug:"venture-debt",title:"Fundos de venture debt",product:"Enquadramento de runway, recorrência, sponsor e instrumento",referenceKeys:["market.mandates"],method:["Avaliar runway, recorrência econômica, cap table, última rodada, sponsor e termos próprios como warrant ou desembolso escalonado.","Separar este universo do crédito corporativo tradicional antes do screening."],verification:["Bloquear venture debt em fundo tradicional e o inverso.","Não usar crescimento de receita como substituto automático de recorrência ou runway."]},
  {id:"MK-11",slug:"mandate-registry",title:"O registro de mandato",product:"Mandato governado por veículo, critério, fonte, data e histórico",referenceKeys:["market.mandates","policy.market.mandate_max_age"],method:["Manter cada critério como observação append-only com veículo, valor, fonte, data, autor, validade e confiança.","Preservar divergências entre declaração e comportamento sem sobrescrever a história."],verification:["Tratar campo sem data como vazio e campo vencido como não elegível a hard filter.","Não permitir que companhia ou assessor visualize o mapa proprietário de fundos."]},
  {id:"MK-12",slug:"hard-filters",title:"Filtros duros primeiro",product:"Eliminados por critério e passantes sem exceção informal",referenceKeys:["market.mandates","policy.market.mandate_max_age"],method:["Aplicar atividade, instrumento, ticket, setor, prazo, garantia obrigatória e jurisdição antes de qualquer ordenação qualitativa.","Encerrar a avaliação do destinatário na primeira incompatibilidade dura confirmada e registrar o valor de ambos os lados."],verification:["Nunca incluir para testar um destinatário que falhou em filtro duro.","Se houver indício de mudança, reconfirmar o mandato antes de reexecutar o filtro."]},
  {id:"MK-13",slug:"explainable-fit",title:"Aderência explicável",product:"Shortlist qualitativa com tese, passantes e pontos a confirmar",referenceKeys:["market.mandates","policy.market.mandate_max_age"],method:["Para cada passante, listar os valores que cabem, os pontos ainda desconhecidos e uma frase de tese específica ao mandato.","Ordenar por veredito, quantidade de lacunas, atualidade, divergências e qualidade do contato, sem score numérico."],verification:["Bloquear percentual mágico ou média que compense filtro duro.","O racional deve permitir que o gestor reconheça seu próprio mandato."]},
  {id:"MK-14",slug:"mandate-provenance",title:"De onde vem a informação de mandato",product:"Hierarquia de fonte por campo de mandato",referenceKeys:["market.mandates","policy.market.mandate_max_age"],method:["Resolver cada campo por confirmação direta, material público, observação governada ou inferência, preservando todos os perdedores.","Usar em hard filter somente confirmação direta, material regulatório ou observação recente autorizada pela política."],verification:["Reconfirmação parcial atualiza apenas os campos cobertos.","Boato, inferência e observação vencida nunca incluem nem eliminam destinatário."]},
  {id:"MK-15",slug:"anchors-first",title:"Âncoras primeiro",product:"Primeira onda pequena, autorizada e orientada a aprendizado",referenceKeys:["policy.market.distribution-waves"],method:["Selecionar grupo inicial dentro do limite de onda por aderência, contato e capacidade de retorno útil.","Registrar retorno e objeções e bloquear expansão quando duas âncoras repetirem objeção estrutural."],verification:["Exigir autorização e pacote compatível antes de cada introdução.","Não abrir nova onda antes da decisão registrada sobre o aprendizado da anterior."]},
  {id:"MK-16",slug:"distribution-control",title:"Controle de distribuição",product:"Ondas limitadas com tese e escopo por destinatário",referenceKeys:["policy.market.distribution-waves"],method:["Criar ondas pequenas com destinatários nomeados, tese individual, material permitido e condição de expansão.","Bloquear envio simultâneo acima do limite ou qualquer mensagem genérica sem racional de mandato."],verification:["Comparar destinatário, mandato, autorização e fingerprint no momento da introdução.","Toda expansão excepcional exige racional e consentimento da companhia."]},
  {id:"MK-17",slug:"sequence-rhythm",title:"Sequência e ritmo",product:"Plano ordenado de introduções qualificadas autorizado pela companhia",referenceKeys:["policy.market.distribution-waves"],method:["Ordenar destinatários por aderência, utilidade como âncora e calendário proposto, preservando os gates mesmo sob urgência.","Vincular cada linha a mandato vigente, racional, contato, materiais e autorização da companhia."],verification:["Bloquear plano sem aprovação da companhia ou com destinatário não identificado.","Urgência pode comprimir datas, nunca remover controles."]},
  {id:"MK-18",slug:"qualified-introduction",title:"O que vai em cada estágio",product:"Registro imutável da introdução qualificada",referenceKeys:["policy.market.distribution-waves"],method:["Montar por destinatário somente teaser e os materiais adicionais expressamente autorizados para seus fingerprints correntes.","Registrar destinatário, contato, racional, pacote, versões, autorização, ator e data e encerrar ali a execução do produto."],verification:["Exigir MA-31 e MA-32 verdes para o mesmo fingerprint e destinatário.","Bloquear NDA, diligência, negociação, book, alocação, documentação e funding no runtime atual."]},
];

function canonical(spec: Spec): CanonicalProcedure {
  return canonicalProcedureSchema.parse({
    id:`${spec.id.toLowerCase()}-${spec.slug}`,version:VERSION,maturity:"candidate",title:{pt:spec.title,en:`${spec.id} governed market-distribution procedure`},role:"market_distribution",blueprintStage:spec.id<"MK-15"?11:12,
    owner:{role:"Head de Mercado e Distribuição"},objective:`Executar ${spec.id} sobre mandato e materiais governados, sem score opaco ou expansão informal.`,product:spec.product,
    procedure:[
      {id:"load",title:"Carregar base governada",instructions:["Fixar caso, estrutura, data de referência, fingerprints de materiais e versão do registro de mandatos.","Consumir somente mandato resolvido, fit explicável, autorização persistida e políticas vigentes."],mode:"deterministic",tools:["fund_mandate","market_truth"],evidenceInputs:["mandatos datados","estrutura governada","material truth set"]},
      {id:"execute",title:"Executar método específico",instructions:spec.method,mode:"deterministic",tools:["fund_mandate","market_truth"],evidenceInputs:["critérios e fontes de mandato","dados governados da operação"]},
      {id:"verify",title:"Verificar gate específico",instructions:spec.verification,mode:"deterministic",tools:["market_truth","release_gate"],evidenceInputs:["resultado exato","autorização e fingerprints quando aplicáveis"]},
      {id:"record",title:"Registrar sem ampliar escopo",instructions:["Emitir estado, resultados, lacunas, exceções e evidências com fingerprint reproduzível.","Terminar em introdução qualificada; não executar atividade pós-introdução."],mode:"deterministic",tools:["market_truth"],evidenceInputs:["resultado verificado","trilha imutável"]},
    ],
    output:{schemaId:`offroad.${spec.id.toLowerCase().replace("-","_")}.v1`,fields:[
      {id:"status",type:"enum",required:true,description:"Estado do procedimento.",evidenceRequired:false,allowedValues:["completed","partial","blocked","not_computable","not_applicable"]},
      {id:"result",type:"object",required:false,description:spec.product,evidenceRequired:true},
      {id:"exceptions",type:"array",required:true,description:"Exceções e incompatibilidades localizadas.",evidenceRequired:true},
      {id:"missing_inputs",type:"array",required:true,description:"Dado, confirmação ou autorização faltante.",evidenceRequired:false},
      {id:"evidence_links",type:"array",required:true,description:"Mandatos, materiais, políticas e autorizações utilizadas.",evidenceRequired:true},
    ]},
    evidence:{hierarchy:["Confirmação direta datada do gestor","Regulamento ou material público vigente","Observação de mercado governada e recente","Inferência identificada como tal"],rules:["Campo sem data não participa de hard filter.","Material ou introdução sempre se liga ao fingerprint e ao destinatário."],materialClaimsRequireSupport:true},
    tests:{unit:[`Executar ${spec.id} com caso válido e entrada ausente.`],gold:[`Atravessar ${spec.id} no caso gold de expansão e no arquétipo específico aplicável.`],adversarial:["Tentar incluir destinatário fora de filtro duro, com mandato vencido ou material não autorizado."],acceptance:spec.verification},
    source:{path:SOURCE,effectiveDate:"2026-08-25"},knowledge:{houseProcedureIds:[spec.id],authorities:["CASA","MERCADO"],referenceDataKeys:spec.referenceKeys,legalReviewRequired:false},
    prerequisites:["Case Truth Sets vigentes","Registro de mandato governado","M7 disponível para qualquer circulação"],dependencies:[],decisionRules:spec.method,redFlags:["Mandato sem data ou divergente","Racional genérico","Score opaco","Envio amplo ou material sem autorização"],stopConditions:["Filtro duro incompatível","Mandato insuficiente ou vencido","Fingerprint divergente","Atividade posterior à introdução qualificada"],exceptions:["Reconfirmação de mandato exige nova observação append-only e nova execução."],templates:[],examples:{positive:[spec.product],negative:["Incluir para testar ou avançar sem evidência e autorização."]},runtime:{orchestration:"deterministic_pipeline",peerHandoffs:false,maxModelCalls:0,modelPurpose:[],allowedTools:["fund_mandate","market_truth","release_gate"]},
  });
}

export const marketDistributionProcedures=specs.map(canonical);
export const marketDistributionProcedureRegistry=compileProcedureRegistry(marketDistributionProcedures,[],referenceDataKeys);

