import {canonicalProcedureSchema, compileProcedureRegistry, type CanonicalProcedure} from "../procedure-contract";
import {materialTemplates} from "../material-templates";
import {referenceDataKeys} from "../reference-data";

const VERSION = "2026.08.26-v1";
const SOURCE = "packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";

type Spec = {
  id: `MA-${string}`;
  slug: string;
  title: string;
  product: string;
  method: string[];
  verification: string[];
  inputs?: string[];
  templates?: string[];
  legal?: boolean;
};
const specs: Spec[] = [
  {id:"MA-01",slug:"teaser-elements",title:"Os 14 elementos do teaser",product:"Teaser completo, ordenado e versionado",templates:["institutional-teaser"],method:["Compilar os 14 elementos canônicos na ordem travada, da identificação anônima do setor até o contato da mesa.","Comprimir métricas em faixas ou índices quando necessário para preservar anonimização e usar a mesma base do memo."],verification:["Rejeitar elemento vazio, número fora da base ou ordem divergente.","Confirmar que operação, fonte de pagamento, estrutura e próximo passo são compreensíveis sem contexto externo."]},
  {id:"MA-02",slug:"true-anonymisation",title:"Anonimização real",product:"Veredito de identificação por eliminação e generalizações aplicadas",templates:["institutional-teaser"],method:["Testar se setor, região, porte e destaque identificam a companhia por eliminação.","Generalizar primeiro o eixo menos informativo e registrar cada transformação aplicada."],verification:["Executar teste de reidentificação sobre o artefato compilado.","Bloquear circulação pré-autorização se qualquer combinação permitir identificação razoável."]},
  {id:"MA-03",slug:"ninety-second-test",title:"O teste dos 90 segundos",product:"Checklist de leitura e decisão de triagem",templates:["institutional-teaser"],method:["Aplicar regras mecânicas de uma ideia por frase, números em tabela e adjetivos sempre quantificados.","Registrar revisão em que um leitor decide aderência de mandato e interesse em NDA em até 90 segundos."],verification:["Exigir checklist mecânico verde e revisão de mesa datada.","Não converter ausência de revisão humana registrada em aprovação automática."]},
  {id:"MA-04",slug:"memo-sections",title:"As 12 seções na ordem de leitura",product:"Memorando compilado na ordem canônica",templates:["institutional-credit-memo"],method:["Compilar as 12 seções canônicas com riscos antes da narrativa da companhia.","Incluir apêndices obrigatórios de spread, ponte da dívida e evidências."],verification:["Comparar ids e ordem de seção ao contrato versionado.","Bloquear memo sem seção obrigatória ou com seção material vazia."]},
  {id:"MA-05",slug:"transaction-summary",title:"Sumário da operação",product:"Resumo autossuficiente da transação",templates:["institutional-credit-memo"],method:["Compilar perfil, volume, instrumento, prazo, amortização, garantias, uso, banda, fonte de pagamento e por que agora em até meia página.","Separar pedido da companhia, configuração suportável e estado do processo."],verification:["Todos os termos devem apontar para base governada.","O sumário isolado deve permitir triagem sem sugerir aprovação de crédito."]},
  {id:"MA-06",slug:"credit-highlights",title:"Destaques de crédito",product:"Quatro a seis destaques quantificados e suportados",templates:["institutional-credit-memo"],method:["Selecionar de quatro a seis fatores que sustentam a capacidade ou a resiliência da operação.","Escrever cada destaque com número, período, perímetro e fonte, sem superlativos."],verification:["Rejeitar destaque sem número ou que a diligência não confirmaria integralmente.","Impedir que risco ou lacuna seja reembalado como destaque."]},
  {id:"MA-07",slug:"risks-and-mitigants",title:"Riscos e mitigantes",product:"Tabela ordenada de risco, impacto, suporte e tratamento",templates:["institutional-credit-memo"],method:["Compilar toda flag material e ausência relevante em risco nomeado, severidade, probabilidade, impacto e suporte.","Classificar tratamento como mecanismo estrutural, fato verificável, preço, condição ou ausência de mitigante."],verification:["Ordenar por severidade e bloquear mitigante genérico como monitoramento constante.","Nenhum risco conhecido pode aparecer somente em nota ou ficar escondido na seção da companhia."]},
  {id:"MA-08",slug:"company-section",title:"A empresa",product:"Seção institucional da companhia",templates:["institutional-credit-memo"],method:["Compilar modelo de negócio, histórico, clientes, fornecedores, societário, governança, gestão e sucessão a partir do Company Truth Set.","Aplicar a lente setorial sem copiar materiais promocionais da companhia."],verification:["Cada afirmação material precisa de evidência.","Mover achados de risco para a seção de riscos e manter aqui somente contexto factual."]},
  {id:"MA-09",slug:"sector-section",title:"Setor",product:"Seção setorial datada e específica",templates:["institutional-credit-memo"],method:["Compilar tamanho, crescimento, concorrentes, posição, ciclo, regulação e métricas da lente setorial aplicável.","Datar toda referência externa e distinguir fonte pública de leitura da mesa."],verification:["Bloquear parágrafos genéricos sem dado ou aplicação ao caso.","Expirar referências fora da janela vigente da casa."]},
  {id:"MA-10",slug:"historical-financials",title:"Financeira histórica",product:"Spread comentado, ajustes, ponte da dívida e vencimentos",templates:["institutional-credit-memo"],method:["Compilar histórico, conversão de caixa, giro, ajustes de EBITDA abertos, ponte da dívida e perfil de vencimentos pró-forma.","Explicar variações por causa econômica ou marcar causa como não confirmada."],verification:["Reconciliar período, entidade, moeda, escala e identidades com Financial e Debt Truth Sets.","Bloquear seção sem ponte da dívida, maturity wall ou abertura reportado versus ajustado quando aplicável."]},
  {id:"MA-11",slug:"transaction-section",title:"A operação",product:"Sources and uses, pró-forma, cronograma e impacto",templates:["institutional-credit-memo"],method:["Compilar sources and uses por bloco, pró-forma, cronograma, marcos e o que a operação resolve, não toca e cria.","Explicar o que se compra pela diferença quando o custo proposto superar o custo atual."],verification:["Sources and uses deve fechar sem plug silencioso.","Cada bloco precisa de dono, timing e evidência do valor."]},
  {id:"MA-12",slug:"structure-section",title:"Estrutura",product:"Termos indicativos ligados à respectiva base",templates:["institutional-credit-memo","indicative-term-sheet"],method:["Compilar instrumento, volume, prazo, amortização, garantias, covenants, subordinação e all-in com a base de cada termo.","Espelhar exatamente a versão corrente do term sheet indicativo."],verification:["Cruzar termo a termo memo e term sheet.","Bloquear termo sem cálculo, procedimento ou referência datada."]},
  {id:"MA-13",slug:"projections-scenarios",title:"Projeções e cenários",product:"Premissas, base, downside, estresses e DSCR",templates:["institutional-credit-memo"],method:["Separar premissas da companhia e ajustes da mesa, então compilar base, downside e estresses governados.","Exibir DSCR por período e identificar a variável que primeiro rompe a capacidade."],verification:["Rejeitar cenário sem premissas rastreadas ou sem métrica de cobertura aplicável.","Confirmar identidade com o modelo financeiro entregável."]},
  {id:"MA-14",slug:"evidence-appendix",title:"Apêndice de evidências",product:"Índice de evidências com hash, versão e marcadores",method:["Enumerar documentos citados com hash, versão, data e localizador e resolver todo marcador material.","Espelhar a mesma lista usada pelo índice da sala de saída."],verification:["Expor marcador órfão como erro, nunca removê-lo silenciosamente.","Exigir cobertura integral dos claims materiais."]},
  {id:"MA-15",slug:"memo-editorial-rules",title:"Regras editoriais do memo",product:"Relatório editorial objetivo e reproduzível",templates:["institutional-credit-memo"],method:["Aplicar voz ativa, datas absolutas, siglas abertas, número com fonte e adjetivo quantificado.","Executar lista vigiada de superlativos, linguagem conclusiva e jargão vazio."],verification:["Emitir achado por frase e regra, com localização no artefato.","Bloquear violações materiais; não reescrever fatos para fazê-los parecer melhores."]},
  {id:"MA-16",slug:"memo-boundary",title:"O que o memo não é",product:"Enquadramento issuer-side e fronteira consultiva",templates:["institutional-credit-memo"],method:["Aplicar enquadramento issuer-side: tese, méritos, riscos, estrutura e evidências de forma persuasiva e equilibrada.","Excluir linguagem de parecer de crédito, aprovação, recomendação de investimento, prospecto ou compromisso de capital."],verification:["Executar auditoria de vocabulário e presença do disclaimer vigente.","Exigir revisão jurídica quando o template de fronteira mudar."],legal:true},
  {id:"MA-17",slug:"canonical-clauses",title:"As cláusulas canônicas",product:"Term sheet indicativo completo e versionado",templates:["indicative-term-sheet"],method:["Compilar todas as cláusulas canônicas, incluindo mecânica das garantias, definições de covenants, CPs, eventos, cura, reporting e natureza não vinculante.","Usar defaults da casa e alternativas por perfil sem remover cláusula sem decisão registrada."],verification:["Exigir compatibilidade de dia um e mapa termo para base verde.","Comparar ids, ordem e completude ao template vigente."]},
  {id:"MA-18",slug:"term-basis",title:"A base de cada termo",product:"Mapa interno termo para base",templates:["indicative-term-sheet"],method:["Ligar cada termo a procedimento ES, cálculo, fato ou referência de mercado datada.","Registrar trade-offs e alternativas indicativas para explicação à companhia."],verification:["Exigir cobertura de 100% dos termos materiais.","Atualizar o mapa sempre que o fingerprint do term sheet mudar."]},
  {id:"MA-19",slug:"non-binding-language",title:"Linguagem não vinculante",product:"Validação da linguagem e vigência jurídica do template",templates:["indicative-term-sheet"],method:["Aplicar indicativo, sujeito a diligência, documentação definitiva e aprovações do financiador em todo o documento.","Verificar vigência da revisão jurídica do template."],verification:["Bloquear obrigação de contratar, termo final ou aprovação implícita.","Bloquear template vencido até nova revisão especializada."],legal:true},
  {id:"MA-20",slug:"conditions-precedent",title:"Condições precedentes",product:"Condições com base, responsável e momento",templates:["indicative-term-sheet"],method:["Compilar CPs societárias, de garantia, certidões, seguros, contratos e intercreditor aplicáveis.","Atribuir base, responsável e momento esperado a cada condição."],verification:["Rejeitar CP sem dono, base ou relação com a estrutura.","Não transformar a data room inicial em checklist de closing."]},
  {id:"MA-21",slug:"definitions-annex",title:"Anexo de definições",product:"Definições idênticas às usadas na análise",templates:["indicative-term-sheet"],method:["Anexar as definições governadas de dívida, EBITDA, caixa, CFADS e IFRS 16 usadas nos cálculos.","Gerar diff explícito quando existir alternativa de definição."],verification:["Comparar expressão e resultado às definições dos Truth Sets.","Divergência entre análise e documento é erro de compilação."]},
  {id:"MA-22",slug:"anticipated-questions",title:"As perguntas antecipadas",product:"Q&A por arquétipo e categoria",method:["Compilar perguntas recorrentes do arquétipo e das flags do caso, agrupadas por companhia, números, dívida, operação e estrutura.","Preencher somente com resposta suportada; caso contrário registrar não disponível, solicitado ou dependente de confirmação."],verification:["Exigir versão do padrão de perguntas e cobertura das flags materiais.","Pergunta nova recorrente vira proposta versionada de evolução, não resposta inventada."]},
  {id:"MA-23",slug:"sourced-answer",title:"Resposta com fonte",product:"Respostas auditadas ou lacunas explícitas",method:["Ligar cada resposta a marcador de documento, cálculo ou confirmação formal da companhia.","Converter ausência de suporte em lacuna com impacto e próxima solicitação."],verification:["Auditar Q&A pelo mesmo claim registry do memo.","Bloquear resposta de memória ou texto provável sem fonte."]},
  {id:"MA-24",slug:"outbound-room-index",title:"O índice da sala de saída",product:"Sala indexada por arquétipo, versão e hash",templates:["institutional-data-room-index"],method:["Organizar societário, financeiro, dívida, operacional, projeto, projeções, jurídico, Q&A e materiais conforme o arquétipo.","Registrar hash, versão, data, origem e classificação de cada arquivo."],verification:["Comparar índice, armazenamento e apêndice de evidências item a item.","Bloquear arquivo órfão ou material sem manifesto."]},
  {id:"MA-25",slug:"room-gates",title:"Portões da sala",product:"Matriz item, portão, autorização e acesso",templates:["institutional-data-room-index"],method:["Classificar item em pré-NDA, pós-NDA ou diligência avançada conforme sensibilidade.","Ligar exceção a autorização da companhia, fingerprint, destinatário e escopo."],verification:["Impedir que qualquer item pule portão.","Registrar acesso por pessoa para itens sensíveis."]},
  {id:"MA-26",slug:"room-hygiene",title:"Higiene da sala",product:"Relatório de duplicidade, versão, metadados e integridade",templates:["institutional-data-room-index"],method:["Detectar duplicatas, versões superadas, abas ocultas, metadados reveladores e inconsistências de nome ou hash.","Executar inspeção automatizada e amostra de mesa registrada."],verification:["Bloquear abertura com achado crítico não tratado.","Preservar originais e registrar qualquer cópia saneada como derivado."]},
  {id:"MA-27",slug:"deliverable-model",title:"O modelo financeiro entregável",product:"Modelo aberto, rastreado e reconciliado",method:["Compilar premissas, histórico, projeções, dívida, demonstrações, covenants e cenários em abas abertas e rastreadas.","Destacar entradas, preservar fórmulas e excluir macros ou abas ocultas."],verification:["Executar identidades financeiras e cruzar todos os números usados no memo.","Bloquear modelo com plug não explicado, fórmula quebrada ou fonte ausente."]},
  {id:"MA-28",slug:"cross-validation",title:"Validação cruzada obrigatória",product:"Relatório de consistência econômica entre artefatos",method:["Comparar companhia, período, moeda, escala, dívida, EBITDA, volume, uso, pricing, garantias e covenants entre teaser, memo, term sheet, modelo e Q&A.","Usar a mesma base decimal e o mesmo fingerprint econômico em todos os artefatos."],verification:["Bloquear a liberação na primeira divergência material e apontar artefatos e suporte.","Exigir nova validação quando qualquer artefato mudar."]},
  {id:"MA-29",slug:"bilingual-identity",title:"PT e EN",product:"Par bilíngue com identidade econômica",method:["Compilar PT e EN da mesma estrutura de dados e glossário vigente, sem retraduzir números.","Conservar períodos, escalas, sinais, unidades e definições."],verification:["Comparar campos econômicos e ids de suporte automaticamente.","Bloquear par com tradução ausente ou diferença econômica."]},
  {id:"MA-30",slug:"disclaimers",title:"Disclaimers",product:"Disclaimer vigente em todos os materiais",templates:["institutional-teaser","institutional-credit-memo","indicative-term-sheet"],method:["Inserir texto jurídico vigente sobre assessoria técnica, confidencialidade, underwriting do investidor e ausência de oferta, recomendação, parecer ou compromisso.","Ligar a versão do disclaimer ao manifesto do artefato."],verification:["Conferir presença e hash do texto em cada material aplicável.","Bloquear texto vencido, alterado ou ausente."],legal:true},
  {id:"MA-31",slug:"version-fingerprint",title:"Versão e fingerprint",product:"Manifesto imutável de cada artefato",method:["Gerar versão, data, hash de conteúdo e referências de template, base e políticas para cada artefato.","Marcar e retirar de circulação toda versão superada."],verification:["Exigir um único fingerprint vivo por artefato e escopo.","Invalidar aprovação e autorização herdadas quando o conteúdo mudar."]},
  {id:"MA-32",slug:"desk-release",title:"A liberação da mesa",product:"Decisão de liberação ligada à versão, aos carimbos e à autorização",method:["Exigir validação cruzada, auditoria de claims, revisão técnica e autorização da companhia para o mesmo fingerprint.","Vincular autorização a escopo e destinatários nomeados e emitir registro imutável da decisão."],verification:["Bloquear envio se qualquer carimbo faltar, divergir ou estiver vencido.","Registrar que a liberação confirma consistência e divulgação, não aprovação de crédito, recomendação ou compromisso de capital."]},
];

function canonical(spec: Spec): CanonicalProcedure {
  return canonicalProcedureSchema.parse({
    id:`${spec.id.toLowerCase()}-${spec.slug}`,version:VERSION,maturity:"candidate",title:{pt:spec.title,en:`${spec.id} governed institutional-material procedure`},role:spec.id === "MA-32" ? "independent_quality_control" : "institutional_materials",blueprintStage:10,
    owner:{role:spec.id === "MA-32" ? "Responsável independente de Quality Control" : "Head de Materiais Institucionais"},objective:`Executar ${spec.id} por compilação da base governada, sem prosa ou número livre.`,product:spec.product,
    procedure:[
      {id:"load",title:"Carregar contrato e base",instructions:["Fixar template, idioma, perímetro, data, versões e manifesto da run.","Consumir somente truth sets, claims auditados, decisões vigentes e evidências ligadas."],mode:"deterministic",tools:["case_materials","material_truth"],evidenceInputs:spec.inputs??["truth sets governados","claim registry","template registry"]},
      {id:"compile",title:"Executar método",instructions:spec.method,mode:"deterministic",tools:["case_materials","data_room"],evidenceInputs:spec.inputs??["base compilada","índice de evidências"]},
      {id:"verify",title:"Verificar contrato específico",instructions:spec.verification,mode:"deterministic",tools:["claim_auditor","material_truth"],evidenceInputs:["artefato exato","relatórios de auditoria"]},
      {id:"publish",title:"Publicar resultado governado",instructions:["Emitir resultado, lacunas, exceções, evidências e fingerprint sem preencher ausência.","Manter a saída interna até que todos os portões aplicáveis autorizem circulação externa."],mode:"deterministic",tools:["material_truth","release_gate"],evidenceInputs:["artefato exato","fingerprint","autorizações aplicáveis"]},
    ],
    output:{schemaId:`offroad.${spec.id.toLowerCase().replace("-","_")}.v1`,fields:[
      {id:"status",type:"enum",required:true,description:"Estado do procedimento.",evidenceRequired:false,allowedValues:["completed","partial","blocked","not_computable","not_applicable"]},
      {id:"result",type:"object",required:false,description:spec.product,evidenceRequired:true},
      {id:"exceptions",type:"array",required:true,description:"Falhas localizadas e impacto.",evidenceRequired:true},
      {id:"missing_inputs",type:"array",required:true,description:"Próximo insumo ou carimbo necessário.",evidenceRequired:false},
      {id:"evidence_links",type:"array",required:true,description:"Truth sets, claims, documentos, templates e autorizações.",evidenceRequired:true},
    ]},
    evidence:{hierarchy:["Truth sets governados e documentos com hash","Cálculos rastreados e claims auditados","Template e glossário vigentes","Julgamento aprovado para o fingerprint exato"],rules:["Material é compilado, não escrito livre.","Número material sem suporte bloqueia o artefato afetado.","Ausência permanece ausência.","Liberação de material não é aprovação de crédito, recomendação nem compromisso de capital."],materialClaimsRequireSupport:true},
    tests:{unit:[`schema, ordem, gates e output de ${spec.id}`],gold:[`${spec.product} fecha no caso gold aprovado`],adversarial:[`divergência, lacuna ou versão indevida bloqueia ${spec.id}`],acceptance:["resultado reproduzível","fingerprint exato","identidade econômica PT e EN","fronteira DCM preservada"]},
    source:{path:`${SOURCE}#${spec.id}`,effectiveDate:"2026-08-25"},knowledge:{houseProcedureIds:[spec.id],authorities:spec.legal?["CASA","LEI"]:["CASA"],referenceDataKeys:spec.id === "MA-32" ? ["policy.qc.numeric_tolerance"] : [],legalReviewRequired:Boolean(spec.legal)},
    prerequisites:["Financial, Debt, Operation, Structure e Pricing Truth Sets aplicáveis","claim registry","template vigente"],dependencies:[],decisionRules:["Uma única base decimal alimenta todos os materiais.","QC libera a versão e a divulgação, não o crédito.","A execução atual termina na introdução qualificada autorizada."],redFlags:["Número sem suporte","Seções fora de ordem","Versões divergentes","Identidade revelada sem autorização","Termo tratado como acordado"],stopConditions:["Claim material órfão","Divergência econômica","Template ou disclaimer vencido","Autorização ausente para saída externa"],exceptions:["Manter artefato interno ou retido com causa e próxima ação; nunca preencher para parecer completo."],templates:spec.templates??[],examples:{positive:[`${spec.id} fecha com base, auditoria e versão reproduzíveis.`],negative:[`${spec.id} usa texto livre, termo sem base ou autorização herdada.`]},runtime:{orchestration:"deterministic_pipeline",peerHandoffs:false,maxModelCalls:0,modelPurpose:[],allowedTools:["case_materials","material_truth","claim_auditor","data_room","release_gate"]},
  });
}

export const materialProcedures = specs.map(canonical);
export const materialProcedureRegistry = compileProcedureRegistry(materialProcedures, materialTemplates.map((template)=>template.id), referenceDataKeys);
