import {canonicalProcedureSchema, compileProcedureRegistry, type CanonicalProcedure, type ProcedureRole} from "../procedure-contract";
import {referenceDataKeys} from "../reference-data";

const VERSION = "2026.08.25-v1";
const SOURCE = "packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";
type Spec = {id: `PR-${string}`; slug: string; title: string; product: string; method: string[]; references: string[]; role?: ProcedureRole};

const specs: Spec[] = [
  {id:"PR-01",slug:"risk-curve",title:"Curva por perfil de risco",product:"Célula-fonte, amostra, recência, faixa e aproximações",method:["Selecionar somente a célula comparável ao perfil, prazo e garantia.","Alargar apenas por régua governada ou abster-se quando a amostra não suportar a inferência."],references:["market.pricing.curves","policy.pricing.sample-quality","policy.pricing.communication-width"]},
  {id:"PR-02",slug:"comparable-issues",title:"Comparáveis de emissões",product:"Comps elegíveis e rejeitados, normalização, mediana e dispersão",method:["Filtrar setor, porte, risco, instrumento, prazo, garantia, tamanho, regime e validade.","Registrar a inclusão e a rejeição de cada observação sem usar comp vencido na decisão."],references:["market.pricing.observation-registry","market.pricing.indexer-basis","policy.pricing.sample-quality","policy.pricing.regime"],role:"market_distribution"},
  {id:"PR-03",slug:"security-premium",title:"Prêmio da garantia",product:"Delta observado por reforço, número de pares e validade",method:["Usar apenas pares comparáveis que diferem no pacote de garantia.","Responder sem base suficiente quando contagem, independência ou validade falharem."],references:["market.pricing.security-premiums","policy.pricing.sample-quality"],role:"market_distribution"},
  {id:"PR-04",slug:"tenor-premium",title:"Prêmio do prazo",product:"Curva de prazo e degraus de apetite observados",method:["Ler a curva por perfil e identificar degraus com observação suficiente.","Não extrapolar além do último ponto observável; exigir sondagem."],references:["market.pricing.tenor-curve","policy.pricing.sample-quality"],role:"market_distribution"},
  {id:"PR-05",slug:"size-liquidity",title:"Prêmio de tamanho e liquidez",product:"Faixa de tíquete, ajustes e implicação de distribuição",method:["Separar custo fixo, liquidez e necessidade de distribuição.","Aplicar somente ajuste observado, datado e rastreável."],references:["market.pricing.size-liquidity"],role:"market_distribution"},
  {id:"PR-06",slug:"indexer",title:"Indexador econômico e vendável",product:"Indexador, casamento, comprador e descasamento quantificado",method:["Mapear receita, custo e ativos contra os indexadores aceitos pelos mandatos.","Bloquear tratamento fiscal ou jurídico não confirmado e manter o descasamento em cenário."],references:["market.pricing.indexer-basis","market.mandates"]},
  {id:"PR-07",slug:"house-grid",title:"Grade governada da casa",product:"Célula versionada, qualidade, fontes, validade e relatório de frescor",method:["Construir a célula apenas de observações autorizadas e válidas.","Célula sem fonte, data, owner, qualidade ou amostra responde sem referência confiável."],references:["market.pricing.curves","market.pricing.observation-registry","policy.pricing.sample-quality","policy.pricing.regime"],role:"market_distribution"},
  {id:"PR-08",slug:"price-gap",title:"Quando o preço não fecha",product:"Gap, diagnóstico e alternativas quantificadas",method:["Comparar a expectativa da companhia com a faixa suportada.","Redesenhar somente mediante alteração material de estrutura, garantia, volume ou expectativa."],references:["market.pricing.security-premiums","market.pricing.curves"]},
  {id:"PR-09",slug:"band-communication",title:"Comunicação da banda",product:"Texto indicativo, base, limitações e largura validada",method:["Comunicar faixa, base e sujeição à análise dos investidores.","Bloquear faixa estreita como promessa disfarçada e faixa larga como ausência de base."],references:["policy.pricing.communication-width","policy.pricing.sample-quality"]},
  {id:"PR-10",slug:"all-in",title:"Custo all-in",product:"Componentes com fonte e all-in anualizado por alternativa",method:["Somar spread, custos de estruturação, registro, garantias, monitoria, jurídico e distribuição.","Anualizar pelo prazo médio e comparar alternativas sempre em all-in."],references:["policy.pricing.cost-catalogue","market.pricing.indexer-basis"]},
  {id:"PR-11",slug:"current-cost",title:"Comparação com custo atual",product:"Custo atual, proposto, delta e benefício concreto comprado",method:["Comparar all-in com custo reconciliado e alternativa real da companhia.","Se mais caro, exigir prazo, carência, garantia liberada ou risco de rolagem quantificado."],references:["policy.pricing.cost-catalogue"]},
  {id:"PR-12",slug:"freshness",title:"Envelhecimento e vigência",product:"Estado de cada referência e log de invalidação",method:["Excluir dado vencido de decisão e de material novo.","Invalidar classe inteira quando houver choque de regime registrado."],references:["policy.pricing.regime","market.pricing.observation-registry"]},
  {id:"PR-13",slug:"proprietary-observation",title:"Observação proprietária",product:"Registro autorizado de observações que podem alimentar agregados",method:["Registrar fonte, status, data, qualidade, validade e autorização de uso agregado.","Manter boato, observação sem origem e dado não autorizado fora da grade."],references:["market.pricing.observation-registry"],role:"market_distribution"},
];

function canonical(spec: Spec): CanonicalProcedure {
  return canonicalProcedureSchema.parse({
    id:`${spec.id.toLowerCase()}-${spec.slug}`,version:VERSION,maturity:"candidate",title:{pt:spec.title,en:`${spec.id} governed pricing procedure`},role:spec.role??"credit_structuring",blueprintStage:8,
    owner:{role:"Head de Mercado e Distribuição"},objective:`Executar ${spec.id} com observações autorizadas, método reproduzível e abstenção explícita.`,product:spec.product,
    procedure:[
      {id:"validate",title:"Validar registro e política",instructions:["Confirmar fonte, status, data, validade, qualidade, regime e autorização de uso agregado.","Separar fechamento, termo, indicação, sondagem e histórico autorizado."],mode:"deterministic",tools:["pricing_truth"],evidenceInputs:["Pricing observation registry","Pricing policy"]},
      {id:"execute",title:"Executar método",instructions:spec.method,mode:"deterministic",tools:["market_reference","financial_core"],evidenceInputs:["observações elegíveis","estrutura proposta","custos rastreados"]},
      {id:"gate",title:"Aplicar comparabilidade e abstenção",instructions:["Publicar amostra, fontes, recência, dispersão, ajustes e limitações.","Abster-se quando qualquer gate crítico de qualidade, independência, validade ou largura falhar."],mode:"deterministic",tools:["pricing_truth","procedure_coverage"],evidenceInputs:["resultado estruturado"]},
    ],
    output:{schemaId:`offroad.${spec.id.toLowerCase().replace("-","_")}.v1`,fields:[
      {id:"status",type:"enum",required:true,description:"Estado do procedimento.",evidenceRequired:false,allowedValues:["completed","partial","blocked","not_computable","not_applicable"]},
      {id:"result",type:"object",required:false,description:spec.product,evidenceRequired:true},
      {id:"exceptions",type:"array",required:true,description:"Exceções e impacto na referência.",evidenceRequired:true},
      {id:"missing_inputs",type:"array",required:true,description:"Próximo insumo necessário.",evidenceRequired:false},
      {id:"evidence_links",type:"array",required:true,description:"Observações, políticas e custos de suporte.",evidenceRequired:true},
    ]},
    evidence:{hierarchy:["Termo ou fechamento autorizado e rastreável","Confirmação direta de gestor ou fonte pública identificada","Indicação ou sondagem registrada","Política e metodologia da casa"],rules:["Observação sem fonte, data, validade, qualidade e autorização não governa a grade.","Comparável rejeitado preserva o motivo da rejeição.","Pricing é referência indicativa e não oferta, compromisso ou decisão do investidor."],materialClaimsRequireSupport:true},
    tests:{unit:[`schema, filtros e gates de ${spec.id}`],gold:[`amostra comparável produz ${spec.product.toLowerCase()}`],adversarial:[`amostra enganosa ou vencida em ${spec.id} resulta em abstenção`],acceptance:["resultado reproduzível","lineage completo","abstenção fail-closed","fronteira consultiva preservada"]},
    source:{path:`${SOURCE}#${spec.id}`,effectiveDate:"2026-08-25"},knowledge:{houseProcedureIds:[spec.id],authorities:[spec.role==="market_distribution"?"MERCADO":"CASA"],referenceDataKeys:spec.references,legalReviewRequired:false},
    prerequisites:["Structure Truth Set","rating e instrumento identificados","pricing policy vigente"],dependencies:[],decisionRules:["Nenhum valor hardcoded substitui observação governada.","Amostra insuficiente produz abstenção.","A Offroad comunica referência indicativa e não compromete preço nem capital."],redFlags:["Comp vencido","Fonte repetida como amostra independente","Garantia incomparável","Faixa estreita demais","Custo sem fonte"],stopConditions:["Amostra ou independência abaixo da política","Choque de regime","Referência vencida","Largura fora da régua"],exceptions:["Emitir sem referência confiável e a causa exata quando o gate falhar."],templates:[],examples:{positive:[`${spec.id} fecha com amostra, fonte e validade.`],negative:[`${spec.id} usa o último deal ou opinião de mesa como curva.`]},runtime:{orchestration:"deterministic_pipeline",peerHandoffs:false,maxModelCalls:0,modelPurpose:[],allowedTools:["pricing_truth","market_reference","financial_core","procedure_coverage"]},
  });
}

export const pricingProcedures=specs.map(canonical);
export const pricingProcedureRegistry=compileProcedureRegistry(pricingProcedures,[],referenceDataKeys);
