import {canonicalProcedureSchema, compileProcedureRegistry, type CanonicalProcedure} from "../procedure-contract";
import {referenceDataKeys} from "../reference-data";

const VERSION = "2026.08.26-v1";
const SOURCE = "packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";

type Spec = {
  id: `RF-${string}`;
  slug: string;
  title: string;
  trigger: string;
  investigate: string[];
  treatment: string;
  untreatedEffect: string;
  authority: Array<"LEI" | "DEF" | "CASA" | "MERCADO" | "HEURÍSTICA">;
  referenceKeys?: string[];
};

const specs: Spec[] = [
  {id:"RF-01",slug:"inventory-outpaces-revenue",title:"Estoque crescendo acima da receita",trigger:"Crescimento material de estoque acima da receita na janela e materialidade governadas.",investigate:["Comparar giro e idade por linha, compras antecipadas suportadas e perdas observadas.","Confrontar provisão, obsolescência e elegibilidade da garantia com evidência de origem."],treatment:"Documentar causa física; sem suporte, propor ajuste de provisão e retirar o estoque da base de garantia.",untreatedEffect:"Eleva dúvida sobre qualidade de receita e se combina com RF-02 e RF-08.",authority:["DEF"],referenceKeys:["policy.financial.materiality","policy.red-flags.detectors"]},
  {id:"RF-02",slug:"receivables-days-stretch",title:"PMR esticando com receita estável",trigger:"PMR normalizado sobe além da faixa governada enquanto receita está estável ou cai.",investigate:["Abrir aging e concentração por cliente, renegociados e migração entre faixas.","Testar se provisão, perdas e recebimentos subsequentes acompanham a deterioração."],treatment:"Nomear causa suportada e reprecificar a carteira elegível líquida de perdas e concentração.",untreatedEffect:"Reduz valor de colateral e questiona a qualidade da receita.",authority:["DEF"],referenceKeys:["policy.receivables.aging","policy.red-flags.detectors"]},
  {id:"RF-03",slug:"unsupported-peer-margin",title:"Margem descolada dos pares",trigger:"Margem bruta ou EBITDA supera intervalo comparável sem causa operacional registrada.",investigate:["Testar mix, preço de transferência, capitalização de custos e reconhecimento de receita.","Separar diferença física comprovada de diferença apenas narrativa."],treatment:"Usar a causa comprovada ou normalizar o downside para a referência governada.",untreatedEffect:"Desconta projeções e, com RF-07, forma sinal severo.",authority:["DEF"],referenceKeys:["market.peer-benchmarks","policy.red-flags.detectors"]},
  {id:"RF-04",slug:"cash-with-expensive-debt",title:"Caixa alto com dívida cara",trigger:"Caixa relevante convive com custo de dívida alto segundo parâmetros governados.",investigate:["Usar saldo médio e não fotografia de fechamento.","Confirmar restrição, garantia, entidade detentora do caixa e entidade devedora."],treatment:"Reclassificar caixa vinculado ou inacessível e registrar a explicação econômica legítima.",untreatedEffect:"Dívida líquida considera somente caixa livre comprovado.",authority:["HEURÍSTICA"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-05",slug:"auditor-change",title:"Troca de auditor",trigger:"Auditor mudou nos três últimos exercícios, sobretudo de maior para menor porte.",investigate:["Obter motivo formal, parecer anterior, ressalvas, ênfases e mudança de honorários ou escopo.","Verificar proximidade entre troca, republicação e preparação da operação."],treatment:"Registrar racional suportado e antecipá-lo no memo, sem transformar troca legítima em acusação.",untreatedEffect:"Compõe a família cultura de números com RF-06, RF-07 e RF-13.",authority:["DEF"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-06",slug:"restatement",title:"Republicação",trigger:"Demonstração foi reapresentada em qualquer dos três últimos exercícios.",investigate:["Mapear linha, período, causa e efeito em cada métrica usada.","Distinguir adoção normativa de erro em receita, estoque, dívida ou caixa."],treatment:"Registrar base técnica e quantificar qualquer efeito material em análise e materiais.",untreatedEffect:"Erro material não explicado torna a base não apresentável.",authority:["DEF"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-07",slug:"management-bias",title:"Gerencial sistematicamente melhor",trigger:"Diferenças gerenciais são persistentemente favoráveis acima da faixa governada.",investigate:["Reconciliar as maiores divergências por linha, período e lançamento de reversão.","Testar se a direção do viés se repete em receita, EBITDA, dívida e caixa."],treatment:"Excluir número gerencial sem conciliação e aplicar viés medido ao downside.",untreatedEffect:"Com RF-05 ou RF-06 forma família severa de cultura de números.",authority:["CASA"],referenceKeys:["policy.financial.materiality","policy.red-flags.detectors"]},
  {id:"RF-08",slug:"period-end-revenue",title:"Receita concentrada no fim do período",trigger:"Receita concentra no fim do período além da faixa setorial sem sazonalidade ou entrega comprovada.",investigate:["Conferir entregas, medições, termos de venda, devoluções e recebimentos subsequentes.","Separar sazonalidade histórica de canal empurrado ou corte inadequado."],treatment:"Manter somente receita com entrega suportada; retirar o restante da base LTM até confirmação.",untreatedEffect:"Rebaixa qualidade de receita e compõe com RF-01 e RF-02.",authority:["DEF"],referenceKeys:["policy.revenue-quality.cutoff","policy.red-flags.detectors"]},
  {id:"RF-09",slug:"related-party-circularity",title:"Circularidade com partes relacionadas",trigger:"Fluxo material com relacionadas coincide com mútuos, garantias ou perímetro econômico divergente.",investigate:["Construir mapa de entidades, valores, preços, caixa e garantias.","Comparar perímetro legal, contábil, operacional e de suporte à dívida."],treatment:"Analisar o perímetro econômico real e propor controles e covenants que o fechem.",untreatedEffect:"Sem transparência total, recomenda declínio do mandato Offroad.",authority:["DEF"],referenceKeys:["policy.related-party.materiality","policy.red-flags.detectors"]},
  {id:"RF-10",slug:"shareholder-litigation",title:"Litígio entre sócios",trigger:"Processo, arbitragem ou bloqueio entre controladores afeta decisões no horizonte da dívida.",investigate:["Identificar objeto, estágio, poderes bloqueados e efeito sobre garantias, waivers e ativos.","Separar disputa remota de impasse que compromete governança da operação."],treatment:"Esperar solução ou, raramente, estruturar prazo e garantias independentes do conflito.",untreatedEffect:"Geralmente impede apresentação institucional enquanto o bloqueio persistir.",authority:["LEI","MERCADO"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-11",slug:"open-succession",title:"Sucessão aberta",trigger:"Função crítica permanece concentrada sem segunda linha ou continuidade compatível com a dívida.",investigate:["Mapear delegação real, executivos, seguro-chave e sucessão formal.","Comparar prazo do risco de pessoa com prazo e amortização da operação."],treatment:"Propor mitigantes reais, prazo menor ou condição de continuidade verificável.",untreatedEffect:"Prazo longo não é apresentável sem mitigação compatível.",authority:["MERCADO"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-12",slug:"cross-guarantee-contagion",title:"Garantia cruzada com empresa problemática",trigger:"A companhia garante entidade relacionada em dificuldade ou com execução relevante.",investigate:["Quantificar exposição jurídica máxima, gatilhos e estágio do problema.","Testar liberação, consolidação econômica e prioridade contra a nova operação."],treatment:"Exigir liberação como condição ou incorporar o risco integralmente na estrutura e análise.",untreatedEffect:"Contágio jurídico material sem tratamento recomenda declínio.",authority:["DEF"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-13",slug:"contingency-reclassification",title:"Contingência reclassificada na véspera",trigger:"Contingência provável vira possível no período de preparação da captação.",investigate:["Exigir fundamento novo, opinião legal e data do evento que justifica a mudança.","Comparar padrão de reclassificação nas demais contingências."],treatment:"Sem fundamento verificável, manter a classificação anterior para análise e explicar a divergência.",untreatedEffect:"Compõe sinal de maquiagem pré-operação.",authority:["DEF"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-14",slug:"changing-information",title:"A informação que muda",trigger:"Três ou mais versões materiais divergem sem trilha de alteração e fonte primária.",investigate:["Ordenar versões por data, origem, período, entidade, moeda e escala.","Confrontar com razão, extrato ou outra fonte primária e congelar a base governada."],treatment:"Explicitar divergências, método de escolha e versão oficial da base conciliada.",untreatedEffect:"Persistência sem fonte primária recomenda declínio do mandato.",authority:["CASA"],referenceKeys:["policy.reconciliation.tolerance","policy.red-flags.detectors"]},
  {id:"RF-15",slug:"analytical-resistance",title:"Resistência ao analítico",trigger:"Item material é negado ou adiado além da régua governada sem substituto verificável.",investigate:["Nomear o risco que o analítico deveria testar e a razão da indisponibilidade.","Avaliar amostra, agregado auditável ou acesso controlado como substituto."],treatment:"Aceitar substituto verificável ou registrar limitação material de forma explícita.",untreatedEffect:"Recusa persistente de analítico essencial recomenda declínio.",authority:["CASA"],referenceKeys:["policy.red-flags.detectors","policy.red-flags.response-sla"]},
  {id:"RF-16",slug:"incompatible-urgency",title:"Pressa incompatível com verificações",trigger:"Existe pressão para eliminar verificações sem causa objetiva e comprovada.",investigate:["Identificar vencimento, liquidez, outro processo e histórico de circulação.","Separar urgência econômica real de resistência ao rito."],treatment:"Estruturar ponte quando suportável ou manter o calendário mínimo de verificações.",untreatedEffect:"Atalho não é aceito; recusa do rito recomenda declínio.",authority:["CASA"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-17",slug:"previously-circulated-case",title:"O caso que já circulou",trigger:"Há material anterior, outro assessor ou retorno de que o fundo já recebeu o caso.",investigate:["Obter material, lista de destinatários, números e objeções anteriores.","Comparar cada versão com a base conciliada e o mandato atual."],treatment:"Reapresentar correção explícita somente a quem recebeu ou aguardar janela adequada.",untreatedEffect:"Mercado queimado restringe a lista e pode impedir aceitação do mandato.",authority:["MERCADO"],referenceKeys:["policy.red-flags.detectors"]},
  {id:"RF-18",slug:"composite-families",title:"Flags compostas",trigger:"Duas ou mais flags ficam ativas na mesma família governada.",investigate:["Calcular cultura de números, qualidade de receita, perímetro nebuloso e conduta sem usar score médio.","Confirmar que cada flag componente permanece ativa e material para o mesmo fingerprint."],treatment:"Exigir decisão explícita da mesa entre remediação reforçada e declínio.",untreatedEffect:"Família severa bloqueia circulação até decisão humana.",authority:["CASA"],referenceKeys:["policy.red-flags.materiality"]},
  {id:"RF-19",slug:"mandate-decline-criteria",title:"Critérios de declínio do mandato",trigger:"Base não analisável, analítico essencial negado, uso não declarável, integridade grave, expectativa incorrigível ou família severa sem tratamento.",investigate:["Revalidar evidências, tratamentos tentados, escopo Offroad e alternativa possível.","Submeter razão classificada à mesa sem automatizar a decisão."],treatment:"Registrar decisão humana de continuar, condicionar ou declinar, ligada ao fingerprint e com caminho de volta.",untreatedEffect:"Nenhum case com recomendação de declínio pendente pode circular.",authority:["CASA"],referenceKeys:["policy.red-flags.materiality"]},
  {id:"RF-20",slug:"decline-communication",title:"Como se declina",trigger:"A mesa decidiu declinar o mandato da Offroad para o fingerprint corrente.",investigate:["Confirmar razão técnica, evidência, linguagem simples, alternativa e condição de reabertura.","Validar que a comunicação não seja parecer de crédito nem julgamento moral."],treatment:"Comunicar diretamente dentro do SLA, registrar a mensagem e preservar o caminho de volta quando existir.",untreatedEffect:"Comunicação ausente ou ambígua degrada relação e governança do funil.",authority:["CASA"],referenceKeys:["policy.red-flags.response-sla"]},
];

function canonical(spec: Spec): CanonicalProcedure {
  const legal = spec.authority.includes("LEI");
  return canonicalProcedureSchema.parse({
    id:`${spec.id.toLowerCase()}-${spec.slug}`,version:VERSION,maturity:"candidate",title:{pt:spec.title,en:`${spec.id} governed red-flag procedure`},role:"independent_quality_control",blueprintStage:spec.id<"RF-18"?6:7,
    owner:{role:"Head de DCM e Quality Control"},objective:`Detectar, investigar e tratar ${spec.id} sem converter sinal em veredito automático.`,product:`Finding ${spec.id} versionado com evidência, severidade, falsos positivos, tratamento e efeito.`,
    procedure:[
      {id:"detect",title:"Executar detector",instructions:[spec.trigger,"Se o parâmetro governado estiver ausente, emitir not_computable em vez de estimar um limiar."],mode:"deterministic",tools:["red_flag_truth"],evidenceInputs:["facts reconciliados","truth sets financeiros, de dívida, operação e estrutura","parâmetros versionados"]},
      {id:"investigate",title:"Controlar falso positivo",instructions:spec.investigate,mode:"deterministic",tools:["red_flag_truth"],evidenceInputs:["evidências do gatilho","respostas e documentos de confirmação"]},
      {id:"treat",title:"Definir tratamento e efeito",instructions:[spec.treatment,spec.untreatedEffect,"Tratamento e decisão precisam apontar para o fingerprint exato da flag."],mode:"human_judgment",tools:["red_flag_review"],evidenceInputs:["finding corrente","evidência de remediação","decisão humana persistida"]},
      {id:"record",title:"Registrar sem emitir parecer",instructions:["Persistir estado, evidências, perguntas, falsos positivos, tratamento e efeito a jusante.","Nunca afirmar aprovação, reprovação de crédito ou compromisso de capital."],mode:"deterministic",tools:["red_flag_truth"],evidenceInputs:["resultado completo do procedimento"]},
    ],
    output:{schemaId:`offroad.${spec.id.toLowerCase().replace("-","_")}.v1`,fields:[
      {id:"status",type:"enum",required:true,description:"Estado do detector e de sua revisão.",evidenceRequired:false,allowedValues:["clear","candidate","confirmed","false_positive","treated","not_computable","not_applicable"]},
      {id:"severity",type:"enum",required:true,description:"Severidade governada sem score médio.",evidenceRequired:false,allowedValues:["information","low","medium","high","critical"]},
      {id:"evidence_links",type:"array",required:true,description:"Evidências mínimas do gatilho e da investigação.",evidenceRequired:true},
      {id:"confirmation_questions",type:"array",required:true,description:"Perguntas necessárias para separar sinal e falso positivo.",evidenceRequired:false},
      {id:"treatment",type:"object",required:false,description:"Tratamento, comprovação e efeito a jusante.",evidenceRequired:true},
    ]},
    evidence:{hierarchy:["Fonte primária conciliada e ancorada","Calculation trace governado","Documento ou resposta datada de confirmação","Julgamento humano registrado para o fingerprint exato"],rules:["Sinal sem evidência mínima não vira flag confirmada.","Ausência de parâmetro governado produz not_computable.","Revisão stale não trata finding novo."],materialClaimsRequireSupport:true},
    tests:{unit:[`Executar ${spec.id} em clear, candidate e not_computable.`],gold:[`Detectar ${spec.id}, confirmar a evidência e aplicar tratamento no gold case aplicável.`],adversarial:[`Produzir falso positivo plausível de ${spec.id} e provar que a investigação o encerra.`],acceptance:["Reason code estável e evidência mínima presente.","Severidade composta nunca é elevada por modelo.","Declínio depende de decisão humana corrente."]},
    source:{path:`${SOURCE}#${spec.id}`,effectiveDate:"2026-08-25"},knowledge:{houseProcedureIds:[spec.id],authorities:spec.authority,referenceDataKeys:spec.referenceKeys??["policy.red-flags.detectors"],legalReviewRequired:legal},
    prerequisites:["Case truth sets correntes","Parâmetros de detector e materialidade vigentes"],dependencies:spec.id==="RF-19"?["rf-18-composite-families"]:spec.id==="RF-20"?["rf-19-mandate-decline-criteria"]:[],decisionRules:[spec.trigger,spec.treatment,spec.untreatedEffect],redFlags:[spec.title,"Evidência contraditória","Revisão vencida"],stopConditions:["Evidência mínima ausente para confirmar","Parâmetro obrigatório ausente","Decisão humana necessária e pendente"],exceptions:["Falso positivo exige razão e evidência persistidas; nunca apaga o finding original."],templates:[],examples:{positive:[spec.treatment],negative:["Converter o gatilho em veto ou parecer automático."]},runtime:{orchestration:"deterministic_pipeline",peerHandoffs:false,maxModelCalls:0,modelPurpose:[],allowedTools:["red_flag_truth","red_flag_review"]},
  });
}

export const redFlagProcedures=specs.map(canonical);
export const redFlagProcedureRegistry=compileProcedureRegistry(redFlagProcedures,[],referenceDataKeys);
