import {materialTemplates} from "../material-templates";
import {canonicalProcedureSchema, compileProcedureRegistry, type CanonicalProcedure, type ProcedureAuthority} from "../procedure-contract";
import {referenceDataKeys} from "../reference-data";

const VERSION = "2026.08.25-v1";
const SOURCE = "packages/credit-playbook/knowledge/HOUSE-PLAYBOOK-COMPLETO-v2.md";
const templateIds = materialTemplates.map((template) => template.id);
type Spec = {id: `ES-${string}`; slug: string; title: string; product: string; method: string[]; references?: string[]; authorities?: ProcedureAuthority[]; legal?: boolean; templates?: string[]};

const specs: Spec[] = [
  {id:"ES-01",slug:"maximum-leverage",title:"Alavancagem máxima por perfil",product:"Alavancagem pró-forma posicionada na banda versionada",method:["Calcular dívida líquida ajustada sobre EBITDA mesa no pró-forma.","Comparar com a banda por setor, ciclicidade, porte e pacote de garantias."],references:["policy.structure.leverage-bands"]},
  {id:"ES-02",slug:"minimum-coverage",title:"Cobertura mínima",product:"DSCR por período em base e downside, com ano crítico",method:["Calcular CFADS sobre serviço proposto por período e cenário.","Usar o menor DSCR do cronograma e testar o piso do perfil."],references:["policy.structure.coverage-floors"]},
  {id:"ES-03",slug:"binding-envelope",title:"O menor limite manda",product:"Envelope com tetos por alavancagem, DSCR, LTV e covenant existente",method:["Computar cada teto sem substituir dimensão ausente por infinito.","Publicar o menor teto e a restrição vinculante."],references:["policy.structure.leverage-bands","policy.structure.coverage-floors","policy.structure.collateral-coverage"]},
  {id:"ES-04",slug:"covenant-headroom",title:"Headroom de covenant",product:"Folga base e resultado downside por covenant",method:["Calcular folga contra o nível proposto em cada cenário.","Bloquear covenant que nasce colado no plano ou quebra no downside inicial."],references:["policy.structure.covenant_headroom","policy.structure.coverage-floors"]},
  {id:"ES-05",slug:"cash-flow-amortisation",title:"Amortização casada com o fluxo",product:"Cronograma proposto e DSCR por período",method:["Desenhar amortização sobre CFADS downside, não sobre o cenário base.","Confirmar cobertura em todos os períodos e ausência de lacuna de liquidez."],references:["policy.structure.repayment-design","policy.structure.coverage-floors"]},
  {id:"ES-06",slug:"amortisation-format",title:"SAC, Price, bullet e balão",product:"Formato com justificativa e fonte do principal",method:["Comparar SAC, Price, bullet e balão contra o perfil de geração.","Aceitar bullet apenas com fonte de repagamento nomeada e evidenciada."],references:["policy.structure.repayment-design"]},
  {id:"ES-07",slug:"grace-and-pik",title:"Carência paga ou capitalizada",product:"Tipo, prazo e efeito da carência no saldo",method:["Tratar juros pagos como padrão e PIK como exceção justificada por fluxo.","Mostrar a evolução do saldo sempre que houver capitalização."],references:["policy.structure.repayment-design"]},
  {id:"ES-08",slug:"seasonal-design",title:"Desenho sazonal",product:"Calendário de parcelas e mecanismo de liquidez",method:["Detectar sazonalidade material e casar parcelas ao ciclo econômico.","Usar conta reserva ou outro mecanismo explícito quando o serviço for constante."],references:["policy.seasonality.materiality","policy.structure.repayment-design","policy.structure.reserve-account"]},
  {id:"ES-09",slug:"project-ramp-up",title:"Ramp-up de projeto",product:"Carência, marcos físicos e covenant de obra",method:["Casar carência ao cronograma físico acrescido da margem de atraso governada.","Trocar covenant financeiro prematuro por marco físico verificável durante a obra."],references:["policy.structure.construction-delay","policy.structure.repayment-design","policy.structure.reserve-account"]},
  {id:"ES-10",slug:"maturity-wall",title:"Não criar a próxima parede",product:"Perfil consolidado pró-forma e teste de concentração",method:["Somar o cronograma proposto ao serviço existente.","Redesenhar qualquer período acima do limite de concentração versionado."],references:["policy.debt.maturity-concentration","policy.structure.maturity-concentration"]},
  {id:"ES-11",slug:"receivables-assignment",title:"Cessão fiduciária de recebíveis",product:"Razão, trava, recomposição, elegibilidade e evidências",method:["Calcular cobertura sobre fluxo líquido elegível e livre de cessão anterior.","Definir domicílio, retenção, recomposição e liberação de excedente."],references:["policy.receivables.aging","policy.structure.collateral_haircuts","policy.structure.collateral-coverage"]},
  {id:"ES-12",slug:"performed-receivables",title:"Performados contra a performar",product:"Carteira segmentada com haircuts distintos",method:["Separar risco de crédito de risco de execução por evidência de performance.","Aplicar elegibilidade e haircut próprios sem promover a performar a performado."],references:["policy.receivables.aging","policy.structure.collateral_haircuts"]},
  {id:"ES-13",slug:"property-lien",title:"Alienação fiduciária de imóvel",product:"Imóvel, laudo, LTV, valor elegível e pendências",method:["Validar independência, data, método, liquidez e matrícula do laudo.","Contar apenas valor residual livre após ônus e haircut aplicável."],references:["policy.structure.collateral_haircuts","policy.structure.collateral-coverage","policy.structure.appraisal-validity"],authorities:["LEI","DEF"],legal:true},
  {id:"ES-14",slug:"inventory-security",title:"Estoque como garantia",product:"Elegibilidade, haircut, monitoria e custo",method:["Testar identificabilidade, revenda, perecibilidade, giro e monitoria independente.","Excluir estoque com red flag ativa e levar monitoria ao all-in."],references:["policy.structure.collateral_haircuts"]},
  {id:"ES-15",slug:"equipment-security",title:"Equipamentos e frota",product:"Valor de revenda, haircut, seguro e registro",method:["Usar valor de revenda e vida útil, nunca apenas custo histórico.","Exigir seguro, beneficiário e gravame compatíveis com o bem."],references:["policy.structure.collateral_haircuts","policy.structure.appraisal-validity"]},
  {id:"ES-16",slug:"share-security",title:"Quotas e ações",product:"Participação, direitos, execução factível e papel no pacote",method:["Avaliar controle no cenário de execução e restrições societárias.","Tratar quotas e ações como reforço, nunca como lastro principal isolado."],references:["policy.structure.collateral_haircuts"],authorities:["DEF","LEI"],legal:true},
  {id:"ES-17",slug:"reserve-account",title:"Conta reserva",product:"Meses, constituição, recomposição e travas",method:["Dimensionar a reserva contra o serviço do perfil.","Definir formação, recomposição, prazo e trava de distribuição."],references:["policy.structure.reserve-account"]},
  {id:"ES-18",slug:"bank-guarantee",title:"Fiança bancária e seguro garantia",product:"Garantidor, rating, prazo, renovação e exclusões",method:["Comparar prazo da proteção ao prazo da dívida e ler condições de execução.","Bloquear descasamento sem renovação objetiva e incluir custo no all-in."],references:["policy.structure.collateral_haircuts"]},
  {id:"ES-19",slug:"personal-guarantee",title:"O aval",product:"Avalista, avais existentes, valor atribuído e papel",method:["Mapear avais já prestados e patrimônio alcançável quando material.","Usar aval como alinhamento e nunca como substituto automático de garantia real."],references:["policy.structure.collateral_haircuts"]},
  {id:"ES-20",slug:"combined-security",title:"O pacote combinado",product:"Garantias pós-haircut, cobertura, downside e sobreposições",method:["Somar valores elegíveis livres sem dupla contagem.","Testar preservação de valor no downside e cobertura contra a dívida."],references:["policy.structure.collateral_haircuts","policy.structure.collateral-coverage"]},
  {id:"ES-21",slug:"dedicated-cash-flow",title:"Fluxo em estrutura dedicada",product:"Perímetro, conta centralizadora, cascata e custo incremental",method:["Separar fluxo, conta e prioridades quando o crédito pertence ao projeto ou ativo.","Definir opex mínimo, serviço, reservas, excedente e gatilho de retenção."],references:["policy.structure.route-catalogue"]},
  {id:"ES-22",slug:"shared-security",title:"Compartilhamento com dívida existente",product:"Status, liberação ou compartilhamento e evidência por garantia",method:["Cruzar cada garantia com contratos e registros existentes.","Usar apenas liberação documentada ou compartilhamento formal como caminho viável."],references:["policy.structure.intercreditor"],authorities:["CASA","LEI"],legal:true},
  {id:"ES-23",slug:"leverage-step-down",title:"Alavancagem com step-down",product:"Níveis anuais, definição e teste downside",method:["Calibrar o nível inicial com headroom e reduzir conforme amortização.","Usar a mesma definição de dívida, EBITDA e IFRS 16 da análise."],references:["policy.structure.leverage-bands","policy.structure.covenant_headroom"]},
  {id:"ES-24",slug:"coverage-covenant",title:"Cobertura como covenant",product:"Métrica, nível, janela de apuração e definição",method:["Escolher DSCR ou ICR conforme o formato e definir CFADS.","Usar doze meses móveis em casos sazonais e testar no downside."],references:["policy.structure.coverage-floors","policy.structure.covenant_headroom","policy.seasonality.materiality"]},
  {id:"ES-25",slug:"dividend-restriction",title:"Dividendos condicionados",product:"Régua de distribuição conectada a covenants e reserva",method:["Permitir distribuição acima da folga e travar abaixo do gatilho definido.","Conectar reserva descomposta e mútuos com partes relacionadas à régua."],references:["policy.structure.covenant_headroom","policy.structure.reserve-account"]},
  {id:"ES-26",slug:"negative-pledge",title:"Negative pledge",product:"Cláusula indicativa e teste contra obrigações existentes",method:["Listar vedação e exceções compatíveis com a operação normal.","Detectar conflito com negative pledges existentes antes do term sheet."],references:["policy.structure.covenant_headroom"],authorities:["LEI","DEF"],legal:true},
  {id:"ES-27",slug:"additional-debt",title:"Endividamento adicional",product:"Teto e cesta operacional de exceções",method:["Calibrar dívida adicional por valor ou razão e listar exceções necessárias.","Confirmar que a cesta não estrangula giro, equipamento ou operação corrente."],references:["policy.structure.covenant_headroom"]},
  {id:"ES-28",slug:"cross-default",title:"Cross-default com threshold",product:"Threshold, escopo e cascata consolidada",method:["Aplicar threshold versionado por porte e perímetro.","Testar o efeito da nova dívida nos cross-defaults existentes."],references:["policy.structure.cross-default-threshold"]},
  {id:"ES-29",slug:"cash-sweep",title:"Cash sweep",product:"Percentual, gatilhos e conexão com fonte de bullet",method:["Definir eventos extraordinários e parcela destinada à amortização.","Preservar incentivo econômico e ligar sweep à fonte de repagamento quando necessário."],references:["policy.structure.repayment-design"]},
  {id:"ES-30",slug:"information-covenants",title:"Obrigações de informação",product:"Calendário de reporte calibrado à capacidade real",method:["Medir o prazo histórico de fechamento e propor entregas executáveis.","Incluir balancete, demonstrações, certificado e eventos materiais sem fabricar default."],references:["policy.structure.reporting-cadence"]},
  {id:"ES-31",slug:"definition-annex",title:"A guerra das definições",product:"Anexo versionado e diff de alternativas",method:["Referenciar dívida, EBITDA, caixa, CFADS e IFRS 16 usados nos cálculos.","Mostrar o efeito de cada definição alternativa sem negociar em nome das partes."],references:["policy.financial.normalization","policy.cash-flow.bridge"],templates:["indicative-term-sheet"]},
  {id:"ES-32",slug:"cure-waiver",title:"Cura e waiver",product:"Matriz de evento, cura, prazo e processo",method:["Distinguir pagamento, informação e covenant financeiro.","Limitar equity cure e registrar processo indicativo de waiver."],references:["policy.structure.cure-waiver"]},
  {id:"ES-33",slug:"acceleration-events",title:"Vencimento antecipado",product:"Menu calibrado de eventos, materialidade e cura",method:["Montar eventos do catálogo vigente conforme os riscos do caso.","Excluir gatilhos sem materialidade, definição ou cura apropriada."],references:["policy.structure.acceleration-events","policy.structure.cure-waiver"],authorities:["LEI","DEF"],legal:true},
  {id:"ES-34",slug:"change-of-control",title:"Mudança de controle",product:"Definição indicativa compatível com acordo e pessoa-chave",method:["Definir controle, vetos e saída de pessoa-chave que disparam a cláusula.","Conferir compatibilidade com acordo societário e governança real."],references:["policy.structure.acceleration-events"],authorities:["DEF","LEI"],legal:true},
  {id:"ES-35",slug:"market-disruption",title:"Cláusulas de mercado em estresse",product:"MAC indicativa com critérios objetivos",method:["Usar apenas em ponte ou compromisso longo quando necessário.","Exigir métricas ou eventos verificáveis e rejeitar discricionariedade ampla."],references:["policy.structure.acceleration-events"],authorities:["MERCADO","LEI"],legal:true},
  {id:"ES-36",slug:"issuer",title:"Quem emite",product:"Emissor, justificativa e compensações",method:["Escolher a entidade com fluxo e ativos que pagam a dívida.","Quando a dívida ficar na holding, declarar e mitigar a distância ao fluxo."],references:["policy.structure.corporate-authority"]},
  {id:"ES-37",slug:"group-guarantors",title:"Garantidores do grupo",product:"Garantidor, limite e verificações",method:["Definir entidades e limites sem desviar propósito econômico.","Conferir capacidade societária e covenants próprios de cada garantidor."],references:["policy.structure.corporate-authority"],authorities:["DEF","LEI"],legal:true},
  {id:"ES-38",slug:"structural-subordination",title:"Subordinação estrutural",product:"Diagnóstico, mitigação e efeito econômico",method:["Identificar dívida acima do fluxo operacional e declarar a subordinação.","Avaliar garantias diretas, upstream e reflexo na referência de preço."],references:["policy.structure.corporate-authority"]},
  {id:"ES-39",slug:"intercreditor",title:"Intercreditor",product:"Mapa de credores, prioridade, princípios e condições",method:["Identificar sobreposição de garantias, consentimentos e prioridade pretendida.","Não prometer compartilhamento antes de acordo e revisão jurídica das partes."],references:["policy.structure.intercreditor"],authorities:["LEI","DEF"],legal:true},
  {id:"ES-40",slug:"adjustment-tree",title:"Quando não fecha",product:"Alternativas quantificadas por restrição vinculante",method:["Gerar alternativas que tratem a restrição: garantia, volume, prazo, amortização, aporte, fases ou espera.","Comparar capacidade, serviço, risco, custo e executabilidade sem forçar o pedido."],references:["policy.structure.minimum-sellable"]},
  {id:"ES-41",slug:"minimum-sellable",title:"A estrutura mínima vendável",product:"Estrutura simples, comprador alvo, all-in e alternativa descartada",method:["Escolher a menor complexidade aceita por um comprador aderente.","Comparar custo e tempo contra a alternativa sofisticada."],references:["policy.structure.minimum-sellable","policy.structure.mandate-ticket"]},
  {id:"ES-42",slug:"day-one-compatibility",title:"Compatibilidade dia um",product:"Checklist de covenant, negative pledge, autorização e maturidade",method:["Executar os quatro testes com evidência antes de liberar material.","Bloquear a estrutura se qualquer check nascer em violação."],references:["policy.structure.maturity-concentration","policy.structure.corporate-authority","policy.structure.intercreditor"]},
  {id:"ES-43",slug:"term-basis-map",title:"Da estrutura ao term sheet",product:"Mapa completo de termo para base",method:["Ligar cada termo a procedimento, cálculo, fato ou referência datada.","Bloquear termo sem suporte ou com suporte expirado."],templates:["indicative-term-sheet"]},
  {id:"ES-44",slug:"route-anatomy",title:"Documento, mecanismo e veículo",product:"Alternativas por ativo, documento, mecanismo, veículo, partes, custo e prazo",method:["Separar as cinco dimensões antes de comparar rotas.","Aplicar elegibilidade vigente e revisão especializada às afirmações jurídicas."],references:["policy.structure.route-catalogue","market.instrument.eligibility"],authorities:["LEI","DEF"],legal:true},
  {id:"ES-45",slug:"final-sizing",title:"Sizing final",product:"Pedido, calculado, proposto e justificativas",method:["Limitar o proposto pelo envelope, sources and uses, excesso permitido e mandato.","Registrar toda diferença para a conversa com a companhia."],references:["policy.transaction-sizing.materiality","policy.structure.leverage-bands","policy.structure.mandate-ticket"]},
];

function canonical(spec: Spec): CanonicalProcedure {
  const authorities = spec.authorities ?? ["CASA","DEF"];
  return canonicalProcedureSchema.parse({
    id:`${spec.id.toLowerCase()}-${spec.slug}`,version:VERSION,maturity:"candidate",title:{pt:spec.title,en:`${spec.id} governed structuring procedure`},role:"credit_structuring",blueprintStage:8,
    owner:{role:"Head de DCM e Estruturação"},objective:`Executar ${spec.id} com cálculo, base e gate reproduzíveis.`,product:spec.product,
    procedure:[
      {id:"validate",title:"Validar base",instructions:["Confirmar versão da operação, entidade, moeda, escala, data e perímetro.","Separar fato, cálculo, política, mercado, hipótese e julgamento."],mode:"deterministic",tools:["structure_truth"],evidenceInputs:["Financial Truth Set","Debt Truth Set","Operation Truth Set"]},
      {id:"execute",title:"Executar método",instructions:spec.method,mode:"deterministic",tools:["financial_core","structure_truth"],evidenceInputs:["fatos reconciliados","referências versionadas"]},
      {id:"challenge",title:"Aplicar downside e compatibilidade",instructions:["Testar a estrutura no downside e contra obrigações existentes.","Gerar alternativa quando a configuração não fechar, sem esconder o bloqueio."],mode:"deterministic",tools:["structure_truth","procedure_coverage"],evidenceInputs:["cenários governados","contratos e políticas aplicáveis"]},
      {id:"publish",title:"Publicar base",instructions:["Emitir resultado, limitações, exceções e próxima melhor solicitação separadamente.","Ligar cada termo material à base que o produziu."],mode:"deterministic",tools:["term_basis_map"],evidenceInputs:["resultado estruturado"]},
    ],
    output:{schemaId:`offroad.${spec.id.toLowerCase().replace("-","_")}.v1`,fields:[
      {id:"status",type:"enum",required:true,description:"Estado do procedimento.",evidenceRequired:false,allowedValues:["completed","partial","blocked","not_computable","not_applicable"]},
      {id:"result",type:"object",required:false,description:spec.product,evidenceRequired:true},
      {id:"alternatives",type:"array",required:true,description:"Alternativas que preservam o objetivo econômico.",evidenceRequired:true},
      {id:"exceptions",type:"array",required:true,description:"Exceções, impacto e gate afetado.",evidenceRequired:true},
      {id:"missing_inputs",type:"array",required:true,description:"Próximos insumos necessários.",evidenceRequired:false},
      {id:"evidence_links",type:"array",required:true,description:"Fatos, cálculos, políticas e referências de suporte.",evidenceRequired:true},
    ]},
    evidence:{hierarchy:["Contratos, registros, laudos e documentos da operação","Financial, Debt e Operation Truth Sets","Política da casa aprovada e versionada","Referência de mercado datada","Premissa ou julgamento explicitamente classificado"],rules:["Toda cláusula econômica aponta para cálculo ou referência.","Garantia só conta após elegibilidade, ônus e haircut.","Afirmação jurídica exige fonte vigente e revisão especializada.","Ausência não vira default silencioso."],materialClaimsRequireSupport:true},
    tests:{unit:[`schema, aritmética e gates de ${spec.id}`],gold:[`caso limpo produz ${spec.product.toLowerCase()}`],adversarial:[`conflito ou ausência em ${spec.id} não vira termo silencioso`],acceptance:["resultado reproduzível","base completa","bloqueio localizado","fronteira de assessoria preservada"]},
    source:{path:`${SOURCE}#${spec.id}`,effectiveDate:"2026-08-25"},knowledge:{houseProcedureIds:[spec.id],authorities,referenceDataKeys:spec.references??[],legalReviewRequired:spec.legal??false},
    prerequisites:["Financial Truth Set","Debt Truth Set","Operation Truth Set","versão da operação confirmada"],dependencies:[],decisionRules:["O menor limite comprovado governa.","Termo sem base não entra no material.","A Offroad propõe estrutura indicativa e não compromete capital nem representa as partes em negociação."],redFlags:["Número sem fonte","Plug não explicado","Garantia já onerada","Covenant sem headroom","Estrutura que nasce em default"],stopConditions:["Identidade econômica material falha","Política obrigatória ausente ou expirada","Compatibilidade dia um falha","Afirmação jurídica material sem revisão"],exceptions:["Emitir not_computable e a próxima melhor solicitação quando faltar base."],templates:spec.templates??[],examples:{positive:[`${spec.id} fecha com base e alternativa reproduzíveis.`],negative:[`${spec.id} produz termo sem fonte ou ignora conflito existente.`]},runtime:{orchestration:"deterministic_pipeline",peerHandoffs:false,maxModelCalls:0,modelPurpose:[],allowedTools:["financial_core","structure_truth","procedure_coverage","term_basis_map"]},
  });
}

export const structureProcedures = specs.map(canonical);
export const structureProcedureRegistry = compileProcedureRegistry(structureProcedures, templateIds, referenceDataKeys);
