/**
 * Case 01 (Camil, banker preparing a meeting): the frozen inputs of `build-interest-and-indexation-schedule` as the
 * executor consumes them, curated from the review corpus of the case with an anchor on every
 * value, plus the helpers that build them. The product's integration_preview reads these
 * inputs instead of extracting them live; that is declared wherever they appear. Hypothetical
 * fixtures in this file are labelled as such in their own notes.
 */
import Decimal from "decimal.js";
import {buildInterestAndIndexationSchedule, type InterestScheduleInput} from "../../executors/build-interest-and-indexation-schedule";

export const d = (value: Decimal.Value) => new Decimal(value);
export const itr = (page: number, note?: string) => ({document: "01_ITR_1T26_31mai2026.pdf", page, ...(note ? {note} : {})});
export const esc = (document: string, clause: string, note?: string) => ({document, clause, ...(note ? {note} : {})});
/** A synthetic 252-day calendar for the test: 63 business days per quarter, declared as such; production reads the ANBIMA calendar. */
export const calendar = {document: "calendario_sintetico_teste.md", note: "63 dias úteis por trimestre e posições declaradas das datas de pagamento; hipótese de teste, produção usa o calendário ANBIMA"};
export const periods: InterestScheduleInput["periods"] = [
  {id: "2026Q3", start: "2026-05-31", end: "2026-08-31", businessDays: 63, anchor: calendar},
  {id: "2026Q4", start: "2026-08-31", end: "2026-11-30", businessDays: 63, anchor: calendar},
  {id: "2027Q1", start: "2026-11-30", end: "2027-02-28", businessDays: 63, anchor: calendar},
  {id: "2027Q2", start: "2027-02-28", end: "2027-05-31", businessDays: 63, anchor: calendar},
];
export const flat = (value: string) => Object.fromEntries(periods.map((period) => [period.id, value]));
export const months = Object.fromEntries(["2026-03", "2026-04", "2026-05", "2026-06", "2026-07", "2026-08", "2026-09", "2026-10", "2026-11", "2026-12", "2027-01", "2027-02", "2027-03", "2027-04", "2027-05"].map((month) => [month, "0.004"]));
export const cdiCurve: NonNullable<InterestScheduleInput["curves"]>[number] = {id: "cdi-bcb-2026-09-04", kind: "CDI", dailyRateByPeriod: flat("0.0005166"), source: {title: "Banco Central, SGS 12, CDI diário de 0,05166% em 1 a 3 de setembro de 2026", asOf: "2026-09-04", anchor: {document: "bcb_sgs_cdi_diario.json", note: "taxa diária publicada; o executor anualiza"}}};
export const ipcaCurve: NonNullable<InterestScheduleInput["curves"]>[number] = {id: "ipca-hipotetico", kind: "IPCA", annualRateByPeriod: flat("0.0490"), monthlyRateByMonth: months, source: {title: "variação mensal hipotética de 0,40% (fixture de teste, não é a curva ANBIMA)", asOf: "2026-05-31", anchor: {document: "fixture_hipotetico.md", note: "curva declarada como hipótese"}}};
export type Series = InterestScheduleInput["series"][number];
export const nominal = (value: string, document: string, note: string): Series["openingPrincipal"] => ({value, basis: "unit_value_x_quantity", anchor: {document, note}});
/** Camil at 31/05/2026. The DI series carry their nominal from the indentures (unit value times quantity); the IPCA balances of the ITR include accrued interest and are not nominals. */
export const rounding14 = {indexFactor: {decimals: 8, mode: "round" as const}, spreadFactor: {decimals: 8, mode: "round" as const}, interestFactor: {decimals: 8, mode: "round" as const}, dailyAccumulation: {decimals: 16, mode: "truncate" as const}, amount: {decimals: 8, mode: "truncate" as const}, anchor: esc("escritura_14a_emissao.pdf", "7.10.1.2", "Fator DI com 8 casas decimais, arredondado; produtório diário truncado em 16 casas")};
export const rounding13 = {indexFactor: {decimals: 8, mode: "round" as const}, spreadFactor: {decimals: 9, mode: "round" as const}, interestFactor: {decimals: 9, mode: "round" as const}, dailyAccumulation: {decimals: 16, mode: "truncate" as const}, amount: {decimals: 8, mode: "truncate" as const}, anchor: esc("escritura_13a_emissao.pdf", "7.7", "fator DI com 8 casas, spread e Fator Juros com 9, acumulação diária truncada em 16, J com 8 sem arredondamento")};
export const camil = (): InterestScheduleInput => ({
  referenceDate: "2026-05-31",
  unit: "BRL thousand",
  unitAnchor: {document: "01_ITR_1T26_31mai2026.pdf", page: 39, note: "nota 15, valores em R$ mil"},
  periods,
  curves: [cdiCurve, ipcaCurve],
  series: [
    {id: "deb-13-1", label: "13ª 1ª série DI + 0,65%", openingPrincipal: nominal("304160", "escritura_13a_emissao.pdf", "304.160 debêntures de R$ 1.000 (o saldo contábil do ITR, 306.038, inclui juros corridos e custos)"), openingAccrued: null, indexer: "CDI", remuneration: {type: "spread_over_index", spreadPerYear: "0.0065"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: [{date: "2028-11-14", amount: "304160", businessDaysFromPeriodStart: 53}], indexationTreatment: null, indexation: null, rounding: rounding13, curveId: "cdi-bcb-2026-09-04", anchors: {balance: itr(39, "15"), terms: {document: "af_13a_emissao.pdf", page: 2}, payments: esc("escritura_13a_emissao.pdf", "7.12.1 e Anexo I", "pagamento semestral, 14/05 e 14/11"), amortization: esc("escritura_13a_emissao.pdf", "7.8.1 e Anexo I", "parcela única em 14/11/2028")}},
    {id: "deb-14-1", label: "14ª 1ª série 104% do DI", openingPrincipal: nominal("411643", "escritura_14a_emissao.pdf", "411.643 debêntures de R$ 1.000 (saldo contábil do ITR: 438.918)"), openingAccrued: null, indexer: "CDI", remuneration: {type: "percent_of_index", percentOfIndex: "1.04"}, couponDates: [{date: "2026-06-12", businessDaysFromPeriodStart: 9}, {date: "2026-12-14", businessDaysFromPeriodStart: 10}], amortization: [{date: "2029-06-14", amount: "411643", businessDaysFromPeriodStart: 10}], indexationTreatment: null, indexation: null, rounding: rounding14, curveId: "cdi-bcb-2026-09-04", anchors: {balance: itr(39, "15"), terms: {document: "af_14a_emissao.pdf", page: 2}, payments: esc("escritura_14a_emissao.pdf", "7.12.1 e Anexo I", "pagamento semestral, 14/06 e 14/12"), amortization: esc("escritura_14a_emissao.pdf", "7.8.1 e Anexo I", "parcela única em 14/06/2029")}},
    {id: "deb-15-2", label: "15ª 2ª série prefixada 14,15%", openingPrincipal: nominal("406349", "escritura_15a_emissao.pdf", "406.349 debêntures de R$ 1.000 (saldo contábil do ITR: 408.703)"), openingAccrued: null, indexer: "fixed", remuneration: {type: "fixed", ratePerYear: "0.1415"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: [{date: "2031-11-14", amount: "203174.5", businessDaysFromPeriodStart: 53}, {date: "2032-11-12", amount: "203174.5", businessDaysFromPeriodStart: 52}], indexationTreatment: null, indexation: null, rounding: {...rounding13, anchor: esc("escritura_15a_emissao.pdf", "7.10.1.2.1")}, curveId: null, anchors: {balance: itr(39, "15"), terms: {document: "af_15a_emissao.pdf", page: 3}, payments: esc("escritura_15a_emissao.pdf", "7.12.1 e Anexo I", "pagamento semestral, 14/05 e 14/11"), amortization: esc("escritura_15a_emissao.pdf", "7.8.2 e Anexo I", "50% em 14/11/2031 e o saldo em 12/11/2032")}},
    {id: "deb-13-2", label: "13ª 2ª série IPCA + 6,3416%", openingPrincipal: {value: "282357", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.063416"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_13a_emissao.pdf", "7.9", "atualização incorporada ao Valor Nominal Unitário Atualizado")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_13a_emissao.pdf", page: 3}, payments: esc("escritura_13a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-11-1", label: "11ª 1ª série CDI + 1,55%", openingPrincipal: {value: "151795", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "CDI", remuneration: {type: "spread_over_index", spreadPerYear: "0.0155"}, couponDates: null, amortization: null, indexationTreatment: null, indexation: null, rounding: null, curveId: "cdi-bcb-2026-09-04", anchors: {balance: itr(39, "15"), terms: {document: "af_11a_emissao.pdf", page: 2}, payments: null, amortization: null}},
    {id: "deb-11-2", label: "11ª 2ª série CDI + 1,55%", openingPrincipal: {value: "505984", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "CDI", remuneration: {type: "spread_over_index", spreadPerYear: "0.0155"}, couponDates: null, amortization: null, indexationTreatment: null, indexation: null, rounding: null, curveId: "cdi-bcb-2026-09-04", anchors: {balance: itr(39, "15"), terms: {document: "af_11a_emissao.pdf", page: 2}, payments: null, amortization: null}},
    {id: "deb-13-3", label: "13ª 3ª série IPCA + 6,5264%", openingPrincipal: {value: "110321", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.065264"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_13a_emissao.pdf", "7.9")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_13a_emissao.pdf", page: 4}, payments: esc("escritura_13a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-14-2", label: "14ª 2ª série IPCA + 6,8286%", openingPrincipal: {value: "204059", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.068286"}, couponDates: [{date: "2026-06-12", businessDaysFromPeriodStart: 9}, {date: "2026-12-14", businessDaysFromPeriodStart: 10}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_14a_emissao.pdf", "7.9")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_14a_emissao.pdf", page: 3}, payments: esc("escritura_14a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-14-3", label: "14ª 3ª série IPCA + 6,9982%", openingPrincipal: {value: "66024", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.069982"}, couponDates: [{date: "2026-06-12", businessDaysFromPeriodStart: 9}, {date: "2026-12-14", businessDaysFromPeriodStart: 10}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_14a_emissao.pdf", "7.9")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_14a_emissao.pdf", page: 4}, payments: esc("escritura_14a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-15-1", label: "15ª 1ª série 105% do DI", openingPrincipal: {value: "770123", basis: "ledger_balance_including_accrued", anchor: itr(39, "15; o relatório fiduciário registra nominal de 765.389")}, openingAccrued: null, indexer: "CDI", remuneration: {type: "percent_of_index", percentOfIndex: "1.05"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: null, indexationTreatment: null, indexation: null, rounding: null, curveId: "cdi-bcb-2026-09-04", anchors: {balance: itr(39, "15"), terms: {document: "af_15a_emissao.pdf", page: 2}, payments: esc("escritura_15a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-15-3", label: "15ª 3ª série IPCA + 8,20%", openingPrincipal: {value: "50401", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.082"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_15a_emissao.pdf", "7.9")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_15a_emissao.pdf", page: 4}, payments: esc("escritura_15a_emissao.pdf", "7.8"), amortization: null}},
    {id: "deb-15-4", label: "15ª 4ª série IPCA + 8,70%", openingPrincipal: {value: "30793", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "IPCA", remuneration: {type: "spread_over_index", spreadPerYear: "0.087"}, couponDates: [{date: "2026-11-13", businessDaysFromPeriodStart: 53}, {date: "2027-05-14", businessDaysFromPeriodStart: 52}], amortization: null, indexationTreatment: "capitalized_principal", indexation: {anniversaryDay: 14, lagMonths: 2, anniversaryDates: null, proRataByPeriod: null, anchor: esc("escritura_15a_emissao.pdf", "7.9")}, rounding: null, curveId: "ipca-hipotetico", anchors: {balance: itr(39, "15"), terms: {document: "af_15a_emissao.pdf", page: 5}, payments: esc("escritura_15a_emissao.pdf", "7.8"), amortization: null}},
    {id: "loan-usd", label: "Capital de giro, USD", openingPrincipal: {value: "867244", basis: "ledger_balance_including_accrued", anchor: itr(39, "15")}, openingAccrued: null, indexer: "unknown", remuneration: null, couponDates: null, amortization: null, indexationTreatment: null, indexation: null, rounding: null, curveId: null, anchors: {balance: itr(39, "15"), terms: null, payments: null, amortization: null}},
  ],
  ledgerControl: {seriesIds: ["deb-11-1", "deb-11-2", "deb-13-1", "deb-13-2", "deb-13-3", "deb-14-1", "deb-14-2", "deb-14-3", "deb-15-1", "deb-15-2", "deb-15-3", "deb-15-4", "loan-usd", "loan-brl", "loan-clp", "loan-pen"], grossDebt: "5670186", grossDebtBasis: "carrying_amount", anchor: itr(40, "nota 15, total")},
  accountingInterestLastPeriod: {periodId: "2026Q2", interest: {value: "170548", anchor: itr(48, "22, Juros")}, monetaryVariation: {value: "1247", anchor: itr(48, "22, Atualização monetária")}},
});
export const by = (result: ReturnType<typeof buildInterestAndIndexationSchedule>, id: string) => result.schedule_by_series.find((schedule) => schedule.series_id === id)!;
export const annualCdi = d("1.0005166").pow(252).minus(1).toDecimalPlaces(8).toFixed();
export const r8 = (value: string) => d(value).toDecimalPlaces(8);
export const r9 = (value: string) => d(value).toDecimalPlaces(9);
