"use client";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {useTranslations} from "next-intl";
import type {AdoptionCandidate,AdoptionWorkContext} from "@/lib/advisor/adoption-basis-reader";
import {saveAdoptionDecision,previewAdoptedLeverage,recordBasisDefinition,recordBasisEntity} from "@/app/[locale]/app/projects/[projectId]/basis/actions";
import {EvidenceDifference} from "./evidence-difference";
import "./adoption-basis.css";
import {formatBasisValue} from "./adoption-basis-format";
const purpose="prepare-capital-structure-decision";
export function AdoptionBasisWork({locale,projectId,contextKey,data}:{locale:string;projectId:string;contextKey:string;data:AdoptionWorkContext}) {
 const t=useTranslations("App.adoptionBasis"),router=useRouter();
 const [pending,startTransition]=useTransition();
 const [error,setError]=useState<string|null>(null),[reference,setReference]=useState<AdoptionCandidate|null>(null);
 const [result,setResult]=useState<Awaited<ReturnType<typeof previewAdoptedLeverage>>|null>(null);
 const display=(value:{type:string;value:unknown}|null)=>formatBasisValue(value,locale,{absent:t("absent"),yes:t("yes"),no:t("no")});
 const metric=(path:string)=>path==="financials.net_debt"?t("netDebt"):path==="financials.ebitda"?t("ebitda"):path;
 const request=useRef<{payload:string;id:string}|null>(null);
 const path=`/${locale}/app/projects/${projectId}/basis`;
 function requestId(payload:unknown) {const serialized=JSON.stringify(payload);if(request.current?.payload!==serialized)request.current={payload:serialized,id:crypto.randomUUID()};return request.current.id;}
 function save(mode:"observation"|"hypothesis",body:Record<string,unknown>) {
  const payload={workId:projectId,purpose,contextKey,expectedVersionId:data.basis?.versionId??null,...body};
  const id=requestId(payload);setError(null);
  startTransition(async()=>{try{const saved=await saveAdoptionDecision({locale,projectId,mode,payload:{...payload,requestId:id}});if(!saved.ok){setError(saved.error);return;}setResult(null);router.push(`${path}?context=${encodeURIComponent(contextKey)}&version=${saved.versionId}`);router.refresh();}catch{setError("unavailable");}});
 }
 const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
 const field=(key:string,type="text",defaultValue="",required=true)=><label>{t(`fields.${key}`)}<input name={key} type={type} defaultValue={defaultValue} required={required}/></label>;
 const entityOptions=data.entities.map(e=><option key={e.id} value={e.id}>{e.legal_name}</option>);
 const definitionOptions=data.definitions.map(d=><option key={d.id} value={d.id}>{d.label}</option>);
 const dossiers=<label>{t("dossier")}<select name="dossierId" required defaultValue=""><option value="">{t("choose")}</option>{data.dossiers.map((d,i)=><option key={d.id} value={d.id}>{t("dossierNumber",{number:i+1})}</option>)}</select></label>;
 const reason=<label>{t("fields.reason")}<textarea name="reason" required minLength={5} maxLength={2000}/></label>;
 const values=data.basis?.entries.filter(e=>e.value.type==="number")??[];
 return <>
  <form action={path} className="basis-context"><label>{t("context")}<input name="context" defaultValue={contextKey} required maxLength={160}/></label><button>{t("openContext")}</button></form>
  <nav aria-label={t("versions")}>{data.versions.map(v=><Link key={v.id} aria-current={v.id===data.basis?.versionId?"page":undefined} href={`${path}?context=${encodeURIComponent(contextKey)}&version=${v.id}`}>{t("version",{number:v.revision})}</Link>)}</nav>
  {error?<p role="alert">{t(`errors.${error}`)} {error==="conflict"?<button onClick={()=>{router.push(`${path}?context=${encodeURIComponent(contextKey)}`);router.refresh();}}>{t("reload")}</button>:null}</p>:null}
  <section><h2>{t("selected")}</h2>{!data.basis?<p>{t("empty")}</p>:<ul className="basis-records">{data.basis.entries.map(e=><li key={e.decisionId}><strong>{metric(e.fieldPath)}</strong><span className="basis-kind">{t(e.kind==="hypothesis"?"hypothesis":"observation")}</span><p>{display(e.value)} · {e.dimensions.currency} · {e.dimensions.unit}</p><p>{e.dimensions.perimeter} · {e.dimensions.periodStart} · {e.dimensions.periodEnd} · {e.dimensions.scenario}</p><p>{e.reason}</p>{e.referenceValue?<p>{t("referenceValue")}: {display(e.referenceValue)}</p>:null}<details><summary>{t("lineage")}</summary><p>{t("actor")}: {e.actorId}</p><p>{t("fields.definitionVersionId")}: {e.dimensions.definitionVersionId}</p><p>{t("source")}: {e.observationId??t("originalHypothesis")}</p></details></li>)}</ul>}</section>
  <EvidenceDifference locale={locale} differences={data.differences} unavailable={data.comparisonUnavailable}/>
  <section><h2>{t("sources")}</h2>{!data.candidates.length?<p>{t("noSources")}</p>:<ul className="basis-records">{data.candidates.map(c=><li key={c.id}><strong>{metric(c.fieldPath)}</strong><p>{display(c.value)} · {c.dimensions.currency} · {c.dimensions.scenario}</p><p>{c.sourceName} · {c.dimensions.periodStart} · {c.dimensions.periodEnd}</p>{c.incompleteReasons.length?<p>{t("incomplete")}: {c.incompleteReasons.join(", ")}</p>:<form action={f=>save("observation",{observationId:c.id,reason:text(f,"reason")})}>{reason}<button disabled={pending}>{t("adopt")}</button></form>}<button disabled={pending} onClick={()=>setReference(c)}>{t("contributeFrom")}</button></li>)}</ul>}{data.nextCursor?<Link href={`${path}?context=${encodeURIComponent(contextKey)}&before=${data.nextCursor}${data.basis?`&version=${data.basis.versionId}`:""}`}>{t("next")}</Link>:null}</section>
  <section><h2>{t("newHypothesis")}</h2><p>{t("hypothesisHelp")}</p>{reference?<p>{t("referenceValue")}: {display(reference.value)} <button onClick={()=>setReference(null)}>{t("clearReference")}</button></p>:null}
  <form key={reference?.id??"original"} action={f=>{let value:unknown=text(f,"value");const type=text(f,"type");if(type==="boolean"){if(value!=="true"&&value!=="false"){setError("invalid");return;}value=value==="true";}if(type==="list"){try{value=JSON.parse(String(value));}catch{setError("invalid");return;}}save("hypothesis",{fieldPath:text(f,"fieldPath"),reason:text(f,"reason"),referenceObservationId:reference?.id??null,value:{type,value},dimensions:{entityId:text(f,"entityId"),definitionVersionId:text(f,"definitionVersionId"),perimeter:text(f,"perimeter"),periodStart:text(f,"periodStart")||null,periodEnd:text(f,"periodEnd"),currency:text(f,"currency")||null,unit:text(f,"unit"),scale:text(f,"scale"),scenario:text(f,"scenario")}});}}>
  {field("fieldPath","text",reference?.fieldPath??"")}
  <label>{t("fields.type")}<select name="type" defaultValue={reference?.value.type??"number"}>{["number","text","date","boolean","list"].map(v=><option key={v} value={v}>{t(`types.${v}`)}</option>)}</select></label>
  {field("value","text",reference?typeof reference.value.value==="string"?reference.value.value:JSON.stringify(reference.value.value):"")}
  <label>{t("fields.entityId")}<select name="entityId" defaultValue={reference?.dimensions.entityId??""} required><option value="">{t("choose")}</option>{entityOptions}</select></label>
  <label>{t("fields.definitionVersionId")}<select name="definitionVersionId" defaultValue={reference?.dimensions.definitionVersionId??""} required><option value="">{t("choose")}</option>{definitionOptions}</select></label>
  {field("perimeter","text",reference?.dimensions.perimeter??"")}{field("periodStart","date",reference?.dimensions.periodStart??"",false)}{field("periodEnd","date",reference?.dimensions.periodEnd??"")}{field("currency","text",reference?.dimensions.currency??"",false)}{field("unit","text",reference?.dimensions.unit??"")}{field("scale","text",reference?.dimensions.scale??"")}{field("scenario","text",reference?.dimensions.scenario??"")}{reason}
  <p>{t("valueHelp")}</p><button disabled={pending}>{t("saveHypothesis")}</button></form></section>
  <details><summary>{t("defineEntity")}</summary><form action={f=>{setError(null);startTransition(async()=>{try{const saved=await recordBasisEntity({locale,projectId,dossierId:text(f,"dossierId"),name:text(f,"name"),namespace:text(f,"namespace"),value:text(f,"value"),reason:text(f,"reason")});if(!saved.ok)setError(saved.error);else router.refresh();}catch{setError("unavailable");}});}}>{dossiers}{field("name")}{field("namespace")}{field("value")}{reason}<button disabled={pending}>{t("saveEntity")}</button></form></details>
  <details><summary>{t("defineMetric")}</summary><form action={f=>{const source=text(f,"contractSourceVersionId");const body={dossierId:text(f,"dossierId"),metricKey:text(f,"fieldPath"),version:{kind:text(f,"kind"),definition:text(f,"definition"),contractSourceVersionId:source||null,contractAnchor:source?{locator:text(f,"anchor")}:null}};setError(null);startTransition(async()=>{try{const saved=await recordBasisDefinition({locale,projectId,...body,requestId:requestId(body)});if(!saved.ok)setError(saved.error);else router.refresh();}catch{setError("unavailable");}});}}>{dossiers}{field("fieldPath")}<label>{t("fields.kind")}<select name="kind">{["reported","managerial","contractual"].map(k=><option key={k} value={k}>{t(`kinds.${k}`)}</option>)}</select></label><label>{t("fields.definition")}<textarea name="definition" required/></label><label>{t("contractSource")}<select name="contractSourceVersionId" defaultValue=""><option value="">{t("choose")}</option>{[...new Map(data.candidates.filter(c=>c.sourceVersionId).map(c=>[c.sourceVersionId,c])).values()].map(c=><option key={c.sourceVersionId} value={c.sourceVersionId!}>{c.sourceName}</option>)}</select></label>{field("anchor","text","",false)}<p>{t("contractHelp")}</p><button disabled={pending}>{t("saveDefinition")}</button></form></details>
  {data.basis?<section><h2>{t("calculate")}</h2><p>{t("calculateHelp")}</p><form action={f=>{setError(null);setResult(null);startTransition(async()=>{try{const calculated=await previewAdoptedLeverage({locale,projectId,versionId:data.basis!.versionId,netDebtDecisionId:text(f,"netDebt"),ebitdaDecisionId:text(f,"ebitda")});if(!calculated.ok)setError(calculated.error);else setResult(calculated);}catch{setError("unavailable");}});}}>{["netDebt","ebitda"].map(k=><label key={k}>{t(k)}<select name={k} required defaultValue=""><option value="">{t("choose")}</option>{values.map(e=><option key={e.decisionId} value={e.decisionId}>{metric(e.fieldPath)} · {display(e.value)} · {e.dimensions.scenario}</option>)}</select></label>)}<button disabled={pending}>{t("runCalculation")}</button></form>{result?.ok?<output><strong>{result.result.value===null?t("absent"):display({type:"number",value:result.result.value})+"×"}</strong><p>{t("version",{number:data.basis.revision})} · {result.result.engineVersion}</p><code>{result.result.basisFingerprint}</code></output>:null}</section>:null}
 </>;
}
