import{renderToStaticMarkup}from"react-dom/server";
import{NextIntlClientProvider}from"next-intl";
import{it,expect,vi}from"vitest";
import pt from"../../../messages/pt-BR.json";import en from"../../../messages/en-US.json";
import{WorkReviewHistory}from"./work-review-history";
import{refreshWorkReviewPages,type WorkReviewDashboard}from"@/lib/advisor/work-review-dashboard";
vi.mock("next/navigation",()=>({useRouter:()=>({refresh:vi.fn()})}));
vi.mock("@/app/[locale]/app/projects/[projectId]/work-review-actions",()=>({submitWorkReviewCommand:vi.fn(),readMoreWorkReview:vi.fn()}));
const work="10000000-0000-4000-8000-000000000001",org="20000000-0000-4000-8000-000000000001",actor="30000000-0000-4000-8000-000000000001",target="40000000-0000-4000-8000-000000000001";
const base:WorkReviewDashboard={schemaVersion:"work-review-dashboard.v1",workId:work,organizationId:org,viewerId:actor,canReport:true,canManage:false,revisions:[],decisions:[],assignments:[],decisionsTruncated:false,nextDecisionCursor:null,nextCursor:null};
const revision={revisionId:target,artifactId:org,kind:"answer",revisionNo:2,manifestFingerprint:"a".repeat(64),withheld:false as const,pending:true,preparedBy:actor,reviews:[{id:target,act:"approve",reviewerId:actor,preparedBy:actor,createdAt:"2026-10-02T10:00:00Z",note:"Observed rationale"}],basisReviewId:actor,change:{outcome:"cosmetic"as const,reasons:["manifest_context"]},canReaffirm:true};
function render(d:WorkReviewDashboard|null,locale:"pt-BR"|"en-US"="pt-BR"){return renderToStaticMarkup(<NextIntlClientProvider locale={locale}messages={locale==="pt-BR"?pt:en}><WorkReviewHistory dashboard={d}locale={locale}projectId={work}labels={{[actor]:"Ana"}}/></NextIntlClientProvider>);}
for(const locale of["pt-BR","en-US"]as const)it(`renders authorized pending/history/classification in ${locale}`,()=>{const html=render({...base,revisions:[revision]},locale),copy=locale==="pt-BR"?pt.WorkReviewHistory:en.WorkReviewHistory;expect(html).toContain(copy.reaffirm);expect(html).toContain(copy.change.cosmetic);expect(html).toContain("Observed rationale");expect(html).toContain("Ana");expect(html).not.toContain('name="effects"');expect(html).not.toContain("queue_execution");});
it("unavailable enumeration does not become empty permitted controls",()=>{const html=render(null);expect(html).toContain(pt.WorkReviewHistory.unavailable);expect(html).not.toContain("button");expect(html).not.toContain("input");});
it("withheld entries reveal no author, note or classification",()=>{const html=render({...base,revisions:[{revisionId:target,withheld:true}]});expect(html).toContain(pt.WorkReviewHistory.withheld);expect(html).not.toContain("Observed rationale");expect(html).not.toContain("data-change-classification");expect(html).not.toContain(target);});
it("material changes require a fresh act and cannot offer reaffirm",()=>{const html=render({...base,revisions:[{...revision,change:{outcome:"material",reasons:["manifest_context"]},canReaffirm:false}]});expect(html).toContain(pt.WorkReviewHistory.change.material);expect(html).not.toContain('>'+pt.WorkReviewHistory.reaffirm+'<');});
it("membership labels or client roles never supply reassignment eligibility",()=>{const html=render({...base,assignments:[{fromUserId:actor,eligible:[{userId:target,label:"Other member"}]}]});expect(html).not.toContain("review_reassign_recipient");});
it("manage sees only the server eligible recipients; historical identity is preserved",()=>{const html=render({...base,canManage:true,assignments:[{fromUserId:actor,eligible:[{userId:target,label:"Eligible reviewer"}]}]});expect(html).toContain("review_reassign_recipient");expect(html).toContain("Eligible reviewer");expect(html).toContain("Reassociar pendências de Ana");});
it("reported decision is visibly distinct and never has an operational selector",()=>{const html=render({...base,decisions:[{withheld:false,canContest:true,decision:{id:target,decisionKey:"Capital choice",revision:1,fingerprint:"a".repeat(64),kind:"record_report",origin:"reported",note:"Board reported",decidedBy:actor,createdAt:"2026-10-02",effects:["none"]},precedence:{state:"contested"}}]});expect(html).toContain(pt.WorkReviewHistory.origin.reported);expect(html).toContain(pt.WorkReviewHistory.precedence.contested);expect(html).toContain(pt.WorkReviewHistory.reportScope);expect(html).not.toContain('name="effects"');});
it("server permission flags remove contest and report actions",()=>{const html=render({...base,canReport:false,decisions:[{withheld:false,canContest:false,decision:{id:target,decisionKey:"Capital choice",revision:1,fingerprint:"a".repeat(64),kind:"choose_alternative",origin:"in_product",note:null,decidedBy:actor,createdAt:"2026-10-02",effects:["none"]},precedence:{state:"current"}}]});expect(html).not.toContain('>'+pt.WorkReviewHistory.contest+'<');expect(html).not.toContain('name="reported_decision_key"');});
it("in-product decisions use translated acts rather than internal keys",()=>{const internal="authorize_execution:10000000-0000-4000-8000-000000000099:sha256abcdef";const html=render({...base,decisions:[{withheld:false,canContest:false,decision:{id:target,decisionKey:internal,revision:1,fingerprint:"a".repeat(64),kind:"authorize_execution",origin:"in_product",note:null,decidedBy:actor,createdAt:"2026-10-02",effects:["none"]},precedence:{state:"current"}}]});expect(html).not.toContain(internal);expect(html).toContain(pt.WorkReviewHistory.decisionKinds.authorize_execution);});

it("server refresh replaces current pending state and revalidates visited pagination",async()=>{const oldCursor=target;const fresh={...base,revisions:[{...revision,pending:false,canReaffirm:false}],nextCursor:oldCursor};const load=vi.fn(async()=>({...base,revisions:[{revisionId:actor,withheld:true as const}],nextCursor:null}));const result=await refreshWorkReviewPages(fresh,{revisions:[oldCursor],decisions:[]},load);expect(load).toHaveBeenCalledExactlyOnceWith(oldCursor,null);expect(result?.revisions).toEqual([...fresh.revisions,{revisionId:actor,withheld:true}]);expect(result?.nextCursor).toBeNull();expect(render(result)).not.toContain('>'+pt.WorkReviewHistory.reaffirm+'<');});
it("refresh loses cached authority when a visited page is denied",async()=>{expect(await refreshWorkReviewPages({...base,revisions:[revision]},{revisions:[target],decisions:[]},async()=>null)).toBeNull();});
