import {offroadTaskRegistry} from "./task-registry";

export type WorkPlanLocale = "pt-BR" | "en-US";

const englishLabels: Record<(typeof offroadTaskRegistry)[number]["id"], string> = {
  M01: "Resolve company, group, jurisdiction and evidence regime",
  M02: "Normalize objective",
  M03: "Record constraints",
  M04: "Infer candidate archetypes",
  M05: "Define deliverables, language and audience",
  M06: "Compile task plan",
  M07: "Issue corrigible understanding",
  D01: "Ingest and version files",
  D02: "Classify document",
  D03: "Extract layout and content",
  D04: "Extract fact candidates",
  D05: "Resolve entity, period and unit",
  D06: "Reconcile sources",
  D07: "Run accounting identities",
  D08: "Measure sufficiency",
  D09: "Prioritize gaps",
  D10: "Compile questions in a batch",
  D11: "Process new response and invalidate descendants",
  C01: "Reconstruct business model",
  C02: "Load applicable knowledge and research sector and regulation",
  C03: "Build financial spreading",
  C04: "Assess earnings quality",
  C05: "Map economic debt",
  C06: "Analyze working capital",
  C07: "Normalize projections",
  C08: "Run scenarios and stress tests",
  C09: "Identify risks and mitigants",
  C10: "Calculate debt capacity",
  C11: "Compile structuring thesis",
  S01: "Compare request and economic need",
  S02: "Generate instrument universe",
  S03: "Apply legal, jurisdictional and economic filters",
  S04: "Map collateral and haircuts",
  S05: "Design alternatives",
  S06: "Research pricing and comparable terms",
  S07: "Calculate all-in cost",
  S08: "Define covenants and protections",
  S09: "Close sources and uses",
  S10: "Compare alternatives",
  S11: "Recommend target structure",
  S12: "Compile indicative term sheet",
  K01: "Update lender universe",
  K02: "Normalize mandates",
  K03: "Update relationships and recency",
  K04: "Research comparable transactions",
  K05: "Apply hard filters",
  K06: "Calculate explainable fit",
  K07: "Generate lender rationale",
  K08: "Detect coverage gaps",
  K09: "Build introduction waves",
  K10: "Define package and disclosure",
  A01: "Define narrative",
  A02: "Build evidence pack",
  A03: "Compile teaser",
  A04: "Compile lender memo",
  A05: "Compile financial model",
  A06: "Compile indicative term sheet",
  A07: "Compile initial Q&A",
  A08: "Compile data room index",
  A09: "Generate audience and language variants",
  A10: "Run consistency gate",
  A11: "Render and inspect",
  X01: "Verify introduction authorization",
  X02: "Build recipient-specific package",
  X03: "Apply watermark and permissions",
  X04: "Execute authorized introduction",
  X05: "Capture response signals",
  X06: "Classify incoming questions",
  X07: "Draft evidence-backed response",
  X08: "Update authorized disclosure",
  X09: "Calculate recommended next action",
  X10: "Record proposal signal",
  X11: "Record underwriting progress",
  X12: "Record funding signal",
  L01: "Classify decline or progress",
  L02: "Update lender profile",
  L03: "Measure match quality",
  L04: "Measure material quality",
  L05: "Create regression case",
  L06: "Run pre-release suite",
};

export function localizedOffroadTaskLabel(taskId: string, fallback: string, locale: WorkPlanLocale): string {
  if (locale === "pt-BR") return fallback;
  return englishLabels[taskId as keyof typeof englishLabels] ?? fallback;
}

export function hasLocalizedOffroadTaskLabel(taskId: string): boolean {
  return taskId in englishLabels;
}
