-- ---------------------------------------------------------------------------------------------
-- Provider mandate confirmations: a deterministic order for "the last confirmation"
--
-- `provider_mandate_confirmations.confirmed_at` defaults to `now()`, which is the transaction
-- timestamp. Two confirmations recorded in one transaction therefore share the exact same
-- `confirmed_at`, and both readers of "the last confirmation" (`public.list_provider_mandates_v1`
-- and the case-fit projection `private.provider_case_fit_owned_sources_v1`) broke that tie by
-- `id desc`, a random uuid. Which confirmation counted as the last one was a coin flip, in the
-- contract test (which renews a mandate right after confirming it) and at runtime whenever two
-- confirmations land in the same transaction.
--
-- The fix is an identity column `sequence` that grows with every insert and never repeats, so the
-- readers order by `confirmed_at desc, sequence desc`. Existing rows are numbered in their
-- `confirmed_at, id` order once, and after that only the database assigns the value: the column is
-- `generated always`, so no caller can supply or rewrite it. Additive only: no policy, grant or
-- signature changes; the two functions are re-created with the same bodies except for the tiebreak.
-- ---------------------------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'provider_mandate_confirmations'
      and column_name = 'sequence') then
    alter table public.provider_mandate_confirmations
      add column sequence bigint generated by default as identity;

    -- Rows that already exist get their number in the order the readers used to assume.
    with ordered as (
      select id, row_number() over (order by confirmed_at, id) as position
      from public.provider_mandate_confirmations
    )
    update public.provider_mandate_confirmations confirmation
    set sequence = ordered.position
    from ordered
    where ordered.id = confirmation.id;

    perform setval(
      pg_get_serial_sequence('public.provider_mandate_confirmations', 'sequence'),
      coalesce((select max(sequence) from public.provider_mandate_confirmations), 1),
      (select max(sequence) from public.provider_mandate_confirmations) is not null);

    -- From here on only the database assigns it.
    alter table public.provider_mandate_confirmations
      alter column sequence set generated always;
  end if;
end;
$$;

comment on column public.provider_mandate_confirmations.sequence is
  'Insertion order, assigned by the database and never reused. Breaks ties between confirmations that share the same confirmed_at (two events recorded in one transaction share the transaction timestamp), so "the last confirmation" is the one recorded last, deterministically.';

-- The lookup index now carries the tiebreak. The old index covered the same prefix and would be
-- reported as redundant, so it goes.
create index if not exists provider_mandate_confirmations_mandate_order_idx
  on public.provider_mandate_confirmations (organization_id, mandate_id, confirmed_at desc, sequence desc);
drop index if exists public.provider_mandate_confirmations_mandate_idx;

-- ---------------------------------------------------------------------------------------------
-- The organization's own reading: same contract, deterministic last confirmation
-- ---------------------------------------------------------------------------------------------

create or replace function public.list_provider_mandates_v1(p_organization_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(jsonb_agg(row_value order by fund_name, version_number desc), '[]'::jsonb)
  from (
    select
      fund.name as fund_name,
      mandate.version_number,
      jsonb_build_object(
        'id', mandate.id,
        'fundId', mandate.fund_id,
        'fundName', fund.name,
        'fundStrategy', fund.strategy,
        'versionNumber', mandate.version_number,
        'status', mandate.status,
        'effectiveStatus', private.provider_mandate_effective_status_v1(
          mandate.status, mandate.valid_from, mandate.valid_until, current_date),
        'currency', mandate.currency,
        'ticketMin', mandate.ticket_min::text,
        'ticketMax', mandate.ticket_max::text,
        'instruments', to_jsonb(mandate.instruments),
        'sectors', to_jsonb(mandate.sectors),
        'geographies', to_jsonb(mandate.geographies),
        'collateral', to_jsonb(mandate.collateral),
        'termMonthsMin', mandate.term_months_min,
        'termMonthsMax', mandate.term_months_max,
        'leverageCeiling', mandate.leverage_ceiling::text,
        'minimumDscr', mandate.minimum_dscr::text,
        'acceptingNewTransactions', mandate.accepting_new_transactions,
        'validFrom', mandate.valid_from,
        'validUntil', mandate.valid_until,
        'sources', mandate.sources,
        'confirmedAt', mandate.confirmed_at,
        'withdrawnAt', mandate.withdrawn_at,
        'note', mandate.note,
        'lastConfirmation', (
          select jsonb_build_object(
            'channel', event.channel, 'confirmedAt', event.confirmed_at,
            'documentReference', event.document_reference,
            'contactRecordId', event.contact_record_id, 'contactDate', event.contact_date,
            'validFrom', event.valid_from, 'validUntil', event.valid_until)
          from public.provider_mandate_confirmations event
          where event.organization_id = mandate.organization_id
            and event.mandate_id = mandate.id
          order by event.confirmed_at desc, event.sequence desc
          limit 1
        ),
        'confirmationCount', (
          select count(*) from public.provider_mandate_confirmations event
          where event.organization_id = mandate.organization_id and event.mandate_id = mandate.id
        )
      ) as row_value
    from public.provider_mandates mandate
    join public.funds fund
      on fund.organization_id = mandate.organization_id and fund.id = mandate.fund_id
    where mandate.organization_id = p_organization_id
  ) ordered;
$$;

revoke all on function public.list_provider_mandates_v1(uuid) from public, anon, authenticated;
grant execute on function public.list_provider_mandates_v1(uuid) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- The case-fit projection: same contract, deterministic last confirmation
-- ---------------------------------------------------------------------------------------------

create or replace function private.provider_case_fit_owned_sources_v1(p_org uuid, p_as_of timestamptz)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb := '[]';
  r record;
  verified public.provider_mandates;
  event public.provider_mandate_confirmations;
  effective text;
  record_summary jsonb;
  c jsonb;
  fields jsonb;
  k text;
  raw jsonb;
  value jsonb;
  obs jsonb;
  provenance text;
  observed timestamptz;
begin
  for r in
    select f.id, f.name, f.organization_id, m.id mandate_id, m.constraints, m.source_kind, m.valid_from
    from public.funds f
    left join lateral (
      select mv.* from public.mandate_versions mv
      where mv.organization_id = p_org and mv.fund_id = f.id and mv.status = 'active'
        and mv.created_at <= p_as_of and mv.valid_from <= p_as_of::date
        and (mv.valid_until is null or mv.valid_until >= p_as_of::date)
      order by mv.version_number desc limit 1
    ) m on true
    where f.organization_id = p_org and f.status = 'active' and f.created_at <= p_as_of
    order by f.id
  loop
    -- The newest registered version answers, draft included. A fund that started describing new
    -- terms is not still offering the old ones, and saying so is the point of this record.
    select * into verified from public.provider_mandates pm
    where pm.organization_id = p_org and pm.fund_id = r.id and pm.created_at <= p_as_of
    order by pm.version_number desc limit 1;

    fields := '{}';
    record_summary := null;

    if found then
      -- The verified record answers for this fund, whatever the legacy row says.
      effective := private.provider_mandate_effective_status_v1(
        verified.status, verified.valid_from, verified.valid_until, p_as_of::date);
      select * into event from public.provider_mandate_confirmations e
      where e.organization_id = p_org and e.mandate_id = verified.id and e.confirmed_at <= p_as_of
      order by e.confirmed_at desc, e.sequence desc limit 1;
      record_summary := jsonb_build_object(
        'versionNumber', verified.version_number,
        'status', verified.status,
        'effectiveStatus', effective,
        'validFrom', verified.valid_from,
        'validUntil', verified.valid_until,
        'confirmedAt', verified.confirmed_at,
        'channel', event.channel,
        'confirmationCount', (select count(*) from public.provider_mandate_confirmations e2
          where e2.organization_id = p_org and e2.mandate_id = verified.id and e2.confirmed_at <= p_as_of));

      if effective = 'confirmed' and event.id is not null then
        observed := event.confirmed_at;
        foreach k in array array['ticket','termMonths','sectors','instruments','collateral','geographies','leverageCeiling','minimumDscr','active','currencies'] loop
          value := null;
          if k = 'ticket' then value := jsonb_build_object('min', trim(trailing '.' from trim(trailing '0' from verified.ticket_min::text)), 'max', trim(trailing '.' from trim(trailing '0' from verified.ticket_max::text)));
          elsif k = 'termMonths' and verified.term_months_min is not null and verified.term_months_max is not null then
            value := jsonb_build_object('min', verified.term_months_min, 'max', verified.term_months_max);
          elsif k = 'sectors' and cardinality(verified.sectors) > 0 then value := to_jsonb(verified.sectors);
          elsif k = 'instruments' then value := to_jsonb(verified.instruments);
          elsif k = 'collateral' and cardinality(verified.collateral) > 0 then value := to_jsonb(verified.collateral);
          elsif k = 'geographies' and cardinality(verified.geographies) > 0 then value := to_jsonb(verified.geographies);
          elsif k = 'leverageCeiling' and verified.leverage_ceiling is not null then
            value := to_jsonb(trim(trailing '.' from trim(trailing '0' from verified.leverage_ceiling::text)));
          elsif k = 'minimumDscr' and verified.minimum_dscr is not null then
            value := to_jsonb(trim(trailing '.' from trim(trailing '0' from verified.minimum_dscr::text)));
          elsif k = 'active' then value := to_jsonb(verified.accepting_new_transactions);
          elsif k = 'currencies' then value := jsonb_build_array(verified.currency);
          end if;
          obs := case when value is not null then jsonb_build_array(jsonb_build_object(
            'value', value, 'provenance', 'declared', 'observedAt', observed,
            'note', 'provider_mandates/' || verified.id::text || '; v' || verified.version_number::text || '; ' || event.channel))
            else '[]'::jsonb end;
          fields := fields || jsonb_build_object(k, obs);
        end loop;
      else
        -- Draft, expired or withdrawn: recorded, shown on the surface, never matched.
        foreach k in array array['ticket','termMonths','sectors','instruments','collateral','geographies','leverageCeiling','minimumDscr','active','currencies'] loop
          fields := fields || jsonb_build_object(k, '[]'::jsonb);
        end loop;
      end if;
    else
      c := coalesce(r.constraints, '{}'::jsonb);
      provenance := case r.source_kind when 'declared' then 'declared' when 'public' then 'published' else 'inferred' end;
      foreach k in array array['ticket','termMonths','sectors','instruments','collateral','geographies','leverageCeiling','minimumDscr','active','currencies'] loop
        value := null;
        if k='ticket' and c->>'ticket_min' ~ '^(0|[1-9][0-9]*)([.][0-9]+)?$' and c->>'ticket_max' ~ '^(0|[1-9][0-9]*)([.][0-9]+)?$' then value:=jsonb_build_object('min',c->>'ticket_min','max',c->>'ticket_max');
        elsif k='termMonths' and c->>'term_months_min' ~ '^[0-9]{1,4}$' and c->>'term_months_max' ~ '^[0-9]{1,4}$' then value:=jsonb_build_object('min',(c->>'term_months_min')::integer,'max',(c->>'term_months_max')::integer);
        elsif k in ('leverageCeiling','minimumDscr') then raw:=c->case k when 'leverageCeiling' then 'leverage_ceiling' else 'minimum_dscr' end;
          if raw#>>'{}' ~ '^(0|[1-9][0-9]*)([.][0-9]+)?$' then value:=to_jsonb(raw#>>'{}'); end if;
        elsif k='active' and jsonb_typeof(c->'active')='boolean' then value:=c->'active';
        elsif k in ('sectors','instruments','collateral','geographies','currencies') and jsonb_typeof(c->k)='array' and jsonb_array_length(c->k)>0
          and not exists(select 1 from jsonb_array_elements(c->k)a where jsonb_typeof(a)<>'string') then value:=c->k;
        end if;
        obs := case when value is not null then jsonb_build_array(jsonb_build_object('value',value,'provenance',provenance,'observedAt',(r.valid_from::timestamp at time zone 'UTC'),'note','mandate_versions/'||r.mandate_id::text||'; source='||r.source_kind||'; valid_from')) else '[]'::jsonb end;
        fields := fields || jsonb_build_object(k, obs);
      end loop;
    end if;

    result := result || jsonb_build_array(
      jsonb_build_object('providerId', r.id, 'name', r.name, 'ownerOrganizationId', p_org,
        'sourceClass', 'registered', 'mandate', fields)
      || case when record_summary is null then '{}'::jsonb else jsonb_build_object('mandateRecord', record_summary) end);
  end loop;
  return result;
end;
$$;

revoke all on function private.provider_case_fit_owned_sources_v1(uuid, timestamptz) from public, anon, authenticated;

comment on function private.provider_case_fit_owned_sources_v1(uuid, timestamptz) is
  'Projects a financier''s own funds for case fit. A fund holding a provider_mandates record is answered by that record alone: confirmed and current becomes dated declared evidence, while draft, expired or withdrawn produces no observation and therefore never matches.';
