/** Synthetic SDK transport tests, not SQL authorization or production fixtures. */
import {createHash,randomUUID} from "node:crypto";
import {readFileSync} from "node:fs";
import {z} from "zod";
import {describe,it,expect,vi} from "vitest";
import type {SupabaseClient} from "@supabase/supabase-js";
import {originationSeniorReadoutSchema} from "@offroad/domain-contracts";
import {legacyGatewayFingerprint,prepareGatewayInput,retentionMatrixVersion} from "@offroad/model-gateway";
import {prepareCapitalPublicTaskRecipe,reconstructCapitalPublicTaskRequest,type CapitalPublicRecipeComponent} from "./capital-public-task-recipe";
import {capitalM07QualityFailureSchema} from "./capital-m07-protocol";
import {capitalM07FinalOutputFingerprint} from "./capital-m07-processing";
import {recoverCapitalM07Existing,type CapitalM07RecoveryTransform} from "./capital-m07-recovery";
import type {CapitalProjectAnalysisJob} from "./queue";
const transport=vi.hoisted(()=>({body:vi.fn(),source:vi.fn(),uploadBody:vi.fn()}));
vi.mock("./capital-body-read-client",()=>({readCapitalM07RecoveryBytes:transport.body,readCapitalM07RecoverySourceBytes:transport.source,readCapitalCaptureBytes:transport.uploadBody}));
type Shape={const?:unknown;enum?:unknown[];anyOf?:Shape[];type?:string;required?:string[];properties?:Record<string,Shape>;items?:Shape;minItems?:number;format?:string;pattern?:string;minLength?:number;minimum?:number};
function synthetic(shape:Shape):unknown{if(shape.const!==undefined)return shape.const;if(shape.enum)return shape.enum[0];if(shape.anyOf)return synthetic(shape.anyOf.find(s=>s.type!=="null")??shape.anyOf[0]!);if(shape.type==="object")return Object.fromEntries((shape.required??[]).map(k=>[k,synthetic(shape.properties![k]!)]));if(shape.type==="array")return Array.from({length:shape.minItems??0},()=>synthetic(shape.items!));if(shape.type==="string")return shape.format==="uri"?"https://example.test/source":shape.pattern?"assumption_1":"x".repeat(Math.max(1,shape.minLength??1));if(shape.type==="number"||shape.type==="integer")return shape.minimum??0;if(shape.type==="boolean")return true;if(shape.type==="null")return null;throw new Error("synthetic schema unsupported");}
function fixture(state:"commit"|"committed"|"transform"|"quality_failed"="commit"){
 const organizationId=randomUUID(),workId=randomUUID(),planId=randomUUID(),briefId=randomUUID(),sessionId=randomUUID(),recipeId=randomUUID(),originalJobId=randomUUID(),jobId=randomUUID(),taskRunId=randomUUID(),deliveryId=randomUUID(),depId=randomUUID();
 const context={project:{id:workId,organization_id:organizationId,project_name:"Synthetic",entry_job:"origination_thesis",access_basis:"public_information",current_phase:"understand"},session:{id:sessionId,locale:"pt-BR",company_profile:{name:"Synthetic company"},privacy_status:"public_information",representation_status:"not_claimed"},
  brief:{id:briefId,kind:"origination_thesis",version:1,content:{meetingContext:"Discuss capital alternatives"},content_fingerprint:"b".repeat(64)},plan:{id:planId,version:1,fingerprint:"a".repeat(64),compiler_version:"synthetic.v1",registry_version:"synthetic.v1"},tasks:[{id:"M07",ordinal:0,batch:0,dependencies:[],execution_class:"model",effect:"propose_state"}]};
 const source={provider:"source_pack" as const,topic:"identity" as const,title:"Synthetic source",url:"https://example.test/source",snippet:"R$ 650 milhões",publishedAt:null,retrievedAt:"2026-10-02T00:00:00Z",contentHash:"c".repeat(64)};
 const pin=(slot:CapitalPublicRecipeComponent["slot"],id:string,body:unknown)=>({slot,id,version:1,body,bodyFingerprint:legacyGatewayFingerprint(body)});
 const components=[pin("company",sessionId,{name:"Synthetic company",website:null}),pin("brief",briefId,context.brief.content),pin("institution",planId,null),pin("revision",originalJobId,null),pin("quality_retry",originalJobId,null),pin("research",recipeId,{status:"succeeded",sourceIds:[deliveryId]}),pin("source",deliveryId,source),pin("dependency",depId,{artifactFingerprint:"b".repeat(64)})];
 const system=readFileSync(new URL("./origination-thesis.ts",import.meta.url),"utf8").match(/const ORIGINATION_THESIS_SYSTEM = `([\s\S]*?)`;/)![1]!;
 const reconstruction=prepareCapitalPublicTaskRecipe({basis:{jobId:originalJobId,organizationId,workId,planId,planFingerprint:"a".repeat(64),locale:"pt-BR",asOfDate:"2026-10-02"},components,system});
 const prepared=prepareGatewayInput({...reconstruction.prepared.request,requireInputAttestation:true,outputMode:"structured",timeoutMs:360000,dataHandling:{classification:"confidential",purpose:"case_analysis",requiredPolicyVersion:retentionMatrixVersion}});
 const builds=["gpt-5.6-sol","gpt-5.6-terra"].map(model=>reconstructCapitalPublicTaskRequest({...reconstruction,prepared},{provider:"openai",model,effort:"high"},{maxOutputTokens:24000,timeoutMs:360000}));
 const parsed=originationSeniorReadoutSchema.parse(synthetic(z.toJSONSchema(originationSeniorReadoutSchema) as Shape));
 const accepted={acceptedInvocationId:randomUUID(),inputReceiptId:randomUUID(),invocationId:randomUUID(),outputFingerprint:legacyGatewayFingerprint(parsed),provider:"openai",reportedModel:"gpt-5.6-terra"};
 const finalProduct={...parsed,schemaVersion:"origination-senior-readout.v3",asOfDate:"2026-10-02",company:{name:"Synthetic company",website:null},sources:[{title:source.title,url:source.url,topic:source.topic,publishedAt:null,provider:source.provider}],researchStatus:"succeeded",scopeBoundary:"Synthetic unit financial work only",provenance:{provider:"openai",model:accepted.reportedModel,executorVersion:"2026.09.03-v6"}};
 const bytesByRetained=new Map<string,Buffer>();
 const scope=(body:unknown)=>{const allocationId=randomUUID(),retainedPayloadId=randomUUID(),bytes=Buffer.from(JSON.stringify(body));bytesByRetained.set(retainedPayloadId,bytes);return{schemaVersion:"capital-retained-body.v1",retentionState:"retained",allocationId,retainedPayloadId,bodyBasisId:randomUUID(),bucket:"capital-input-capture",path:`${organizationId}/${allocationId}/payload.json`,payloadFingerprint:createHash("sha256").update(bytes).digest("hex"),byteLength:bytes.length,storageObjectId:randomUUID(),storageVersion:"synthetic-version",retainedAt:"2026-10-02T00:00:00Z",uploadExpiresAt:"2026-10-02T12:30:00Z",expiresAt:"2026-10-03T00:00:00Z",purgeAt:"2026-10-02T23:00:00Z",replayed:true};};
 const contextScope=scope(context),parsedScope=scope(parsed),finalScope=scope(finalProduct),sourceScopeBase=scope({...source,publishedAt:undefined});const{schemaVersion:_,retentionState:_state,bodyBasisId:_basis,replayed:_replay,...sourceIdentity}=sourceScopeBase;
 const sourceScope={...sourceIdentity,schemaVersion:"capital-public-storage-scope.v1",state:"complete",deliveryId};
 const recipe={...reconstruction.recipe,schemaVersion:"capital-m07-recipe-receipt.v1",state:"ready",recipeId,taskRunId,rendererVersion:"capital-public-task-renderer.m07.v1",recipeFingerprint:"d".repeat(64),contextRetainedPayloadId:contextScope.retainedPayloadId,components:reconstruction.recipe.components,expiresAt:contextScope.expiresAt,
  operationalBudget:{schemaVersion:"capital-m07-operational-budget.v1",researchReservationVersion:"public-research-reservation.m07.v1",researchReservationMicroUsd:300000,maxExposureMicroUsd:1250000,maxDispatches:2}};
 const {taskId:_task,executorVersion:_executor,transformationVersion:_transformation,systemSha256:_system,gaps:_gaps,...readyRecipe}=recipe;
 const grant={schemaVersion:"capital-m07-recovery-grant.v1",mode:"recovery",state,recipeId,originalJobId,authorizedJobId:jobId,organizationId,workId,taskRunId,recipe:readyRecipe,
  reconstructionMetadata:{schemaVersion:"capital-m07-reconstruction-metadata.v1",originalAttempt:1,researchStatus:"succeeded",dependencies:[{id:depId,artifactFingerprint:"b".repeat(64)}]},requestPins:{schemaVersion:"capital-m07-reconstruction-pins.v1",promptFingerprint:builds[0]!.promptFingerprint,primaryRequestFingerprint:builds[0]!.requestFingerprintV1,fallbackRequestFingerprint:builds[1]!.requestFingerprintV1},accepted,qualityFailure:null as z.infer<typeof capitalM07QualityFailureSchema>|null,
  context:contextScope,sources:[{deliveryId,retainedPayloadId:sourceScope.retainedPayloadId}],parsed:parsedScope,final:state==="transform"?null:finalScope,revisionId:state==="committed"?randomUUID():null,capitalArtifactId:state==="committed"?randomUUID():null,expiresAt:contextScope.expiresAt,dispatchAllowed:false};
 const finalFingerprint=capitalM07FinalOutputFingerprint(accepted.outputFingerprint,readyRecipe.recipeFingerprint,finalProduct);const commit={schemaVersion:"capital-m07-commit-receipt.v1",recipeId,taskRunId,capitalArtifactId:grant.capitalArtifactId??randomUUID(),revisionId:grant.revisionId??randomUUID(),finalFingerprint,artifactFingerprint:"e".repeat(64),artifactVersion:1,replayed:state==="committed"};
 const graders=["schema","citation_allowlist","citation_coverage","uncertainty","forward_case_governance","unsupported_material_numbers","official_financial_coverage","debt_amount_units","scope_boundary"];
 if(state==="quality_failed")grant.qualityFailure=capitalM07QualityFailureSchema.parse({schemaVersion:"capital-m07-quality-failure.v1",acceptedInvocationId:accepted.acceptedInvocationId,parsedRetainedPayloadId:parsedScope.retainedPayloadId,finalRetainedPayloadId:finalScope.retainedPayloadId,finalFingerprint,qualityResults:graders.map(id=>({id,passed:id!=="unsupported_material_numbers"}))});
 const transform=vi.fn(async(_input:Parameters<CapitalM07RecoveryTransform>[0])=>({finalProduct,qualityResults:["schema","citation_allowlist","citation_coverage","uncertainty","forward_case_governance","unsupported_material_numbers","official_financial_coverage","debt_amount_units","scope_boundary"].map(id=>({id,passed:true}))}));
 transport.body.mockReset();transport.source.mockReset();transport.uploadBody.mockReset();
 transport.body.mockImplementation(async(_client:unknown,_authority:unknown,input:{retainedPayloadId:string},s:{storageObjectId:string;storageVersion:string})=>({bytes:bytesByRetained.get(input.retainedPayloadId),objectId:s.storageObjectId,version:s.storageVersion}));transport.source.mockImplementation(transport.body.getMockImplementation()!);
 transport.uploadBody.mockResolvedValue({bytes:bytesByRetained.get(finalScope.retainedPayloadId),objectId:finalScope.storageObjectId,version:finalScope.storageVersion});
 const upload=vi.fn(async()=>({error:null}));const rpc=vi.fn(async(name:string,input:Record<string,unknown>):Promise<{data:unknown;error:null|{code:string}}>=>{let data:unknown;
  if(name==="worker_find_capital_m07_recovery_v1")data={schemaVersion:"capital-m07-recovery-discovery.v1",state:"recovery",recipeId};
  else if(name==="worker_recover_capital_m07_result_v1")data=structuredClone(grant);
  else if(name==="worker_read_capital_m07_recovery_body_v1")data=[contextScope,parsedScope,finalScope].find(s=>s.retainedPayloadId===input.p_retained_payload_id);
  else if(name==="worker_read_capital_m07_recovery_source_v1")data=sourceScope;
  else if(name==="worker_prepare_capital_m07_recovered_output_v1")data={...finalScope,retentionState:"allocated",retainedPayloadId:null,storageObjectId:null,storageVersion:null,replayed:false,canonicalBody:JSON.stringify(finalProduct)};
  else if(name==="worker_commit_capital_m07_body_v1"){grant.final=finalScope;grant.state="commit";data=finalScope;}
  else if(name==="worker_record_capital_m07_quality_failure_v1"){
    const replayed=grant.qualityFailure!==null;
    grant.qualityFailure=capitalM07QualityFailureSchema.parse({schemaVersion:"capital-m07-quality-failure.v1",acceptedInvocationId:input.p_accepted_invocation_id,parsedRetainedPayloadId:input.p_parsed_retained_payload_id,finalRetainedPayloadId:input.p_final_retained_payload_id,finalFingerprint:input.p_final_fingerprint,qualityResults:input.p_quality_results});grant.state="quality_failed";
    data={schemaVersion:"capital-m07-quality-failure-receipt.v1",recipeId,taskRunId,qualityFailure:grant.qualityFailure,replayed};
  }
  else if(name==="worker_commit_capital_m07_recovered_result_v1")data=commit;
  else throw new Error(`unexpected unit RPC ${name}`);return{data,error:null};});
 const client={rpc,storage:{from:()=>({upload})}} as unknown as SupabaseClient;
 const job={job_id:jobId,organization_id:organizationId,capability_token:"synthetic",payload:{capital_project_id:workId,capital_project_plan_id:planId,capital_project_brief_id:briefId}} as CapitalProjectAnalysisJob;
 return{client,job,grant,rpc,upload,transform,bytesByRetained,sourceScope,finalScope,finalProduct,commit,run:()=>recoverCapitalM07Existing(client,job,transform,()=>Date.parse("2026-10-02T12:00:00Z"))};
}
describe("M07 successor recovery with synthetic SDK transport",()=>{
 it("replays a committed artifact through original bodies and receipts without model or upload",async()=>{const f=fixture("committed"),result=await f.run();expect(result?.commit).toEqual(f.commit);expect(f.transform.mock.calls[0]![0].accepted.reportedModel).toBe("gpt-5.6-terra");expect(f.upload).not.toHaveBeenCalled();expect(f.rpc.mock.calls.every(([name])=>!String(name).includes("authorize")&&!String(name).includes("input")&&!String(name).includes("attempt"))).toBe(true);});
 it("commits an already retained final body without rerunning the model",async()=>{const f=fixture(),result=await f.run();expect(result?.commit.replayed).toBe(false);expect(f.upload).not.toHaveBeenCalled();});
 it("transforms retained parsed bytes and physically retains final output before commit",async()=>{const f=fixture("transform"),result=await f.run();expect(result?.commit).toEqual(f.commit);expect(f.upload).toHaveBeenCalledOnce();expect(f.rpc.mock.calls.map(([name])=>name)).toContain("worker_prepare_capital_m07_recovered_output_v1");expect(f.rpc.mock.calls.map(([name])=>name)).toContain("worker_commit_capital_m07_body_v1");expect(f.transform).toHaveBeenCalledOnce();});
 it("records a failed fixed transformation as terminal with no artifact commit",async()=>{const f=fixture();const original=f.transform.getMockImplementation()!;f.transform.mockImplementation(async input=>{const result=await original(input);return{...result,qualityResults:result.qualityResults.map(value=>({...value,passed:value.id!=="unsupported_material_numbers"}))};});await expect(f.run()).rejects.toMatchObject({code:"quality_gate_m07_failed"});expect(f.grant.state).toBe("quality_failed");expect(f.rpc.mock.calls.map(([name])=>name)).not.toContain("worker_commit_capital_m07_recovered_result_v1");expect(f.rpc.mock.calls.map(([name])=>name)).toContain("worker_record_capital_m07_quality_failure_v1");});
 it("replays a terminal failed diagnostic without transformation, model or upload",async()=>{const f=fixture("quality_failed");await expect(f.run()).rejects.toMatchObject({code:"quality_gate_m07_failed"});expect(f.transform).not.toHaveBeenCalled();expect(f.upload).not.toHaveBeenCalled();expect(f.rpc.mock.calls.map(([name])=>name)).not.toContain("worker_commit_capital_m07_recovered_result_v1");});
 it("denies changed request pins before transformation",async()=>{const f=fixture();f.grant.requestPins.primaryRequestFingerprint="f".repeat(64);await expect(f.run()).rejects.toThrow("request_changed");expect(f.transform).not.toHaveBeenCalled();});
 it("returns none only from an explicit server discovery",async()=>{const f=fixture();f.rpc.mockResolvedValueOnce({data:{schemaVersion:"capital-m07-recovery-discovery.v1",state:"none",recipeId:null},error:null});expect(await f.run()).toBeNull();expect(f.rpc).toHaveBeenCalledOnce();expect(f.transform).not.toHaveBeenCalled();});
 it("turns historical missing source metadata into a gap rather than inventing provenance",async()=>{const f=fixture();f.bytesByRetained.set(f.sourceScope.retainedPayloadId,Buffer.from(JSON.stringify({title:"Synthetic",url:"https://example.test/source",snippet:"",contentHash:"c".repeat(64)})));const bytes=f.bytesByRetained.get(f.sourceScope.retainedPayloadId)!;f.sourceScope.payloadFingerprint=createHash("sha256").update(bytes).digest("hex");f.sourceScope.byteLength=bytes.length;await expect(f.run()).rejects.toMatchObject({code:"capital_m07_retained_recovery_required"});expect(f.transform).not.toHaveBeenCalled();});
 it("denies changed source bytes before transformation",async()=>{const f=fixture();transport.source.mockResolvedValue({bytes:Buffer.from("changed"),objectId:randomUUID(),version:"synthetic"});await expect(f.run()).rejects.toThrow("source_changed");expect(f.transform).not.toHaveBeenCalled();});
 it("denies a revocation observed on the next authority check",async()=>{const f=fixture();const original=f.rpc.getMockImplementation()!;let grants=0;f.rpc.mockImplementation(async(name,input)=>{if(name==="worker_recover_capital_m07_result_v1"&&++grants===2)return{data:null,error:{code:"42501"}};return original(name,input);});await expect(f.run()).rejects.toThrow("recovery_denied");expect(f.transform).not.toHaveBeenCalled();});
});
