/** Prospective native final product, distinct from parsed diagnostic and physical bytes. */
import {z} from 'zod';
import {companyDebtDiagnosticSchema} from '@offroad/domain-contracts';
import {researchSourceSchema} from '@offroad/public-research';
export const capitalCompanyDebtArtifactSchema=companyDebtDiagnosticSchema.extend({schemaVersion:z.literal('company-debt-diagnostic.v1'),asOfDate:z.iso.date(),company:z.strictObject({name:z.string().min(1),website:z.string().nullable()}),sources:z.array(researchSourceSchema.pick({title:true,url:true,topic:true,publishedAt:true,provider:true}).strict()).min(1),researchStatus:z.enum(['succeeded','partial']),scopeBoundary:z.string().min(20),provenance:z.strictObject({provider:z.enum(['anthropic','openai']),model:z.enum(['claude-sonnet-5','gpt-5.6-terra']),executorVersion:z.literal('2026.09.01-v1')})}).strict();

/** Pinned pure transformation shared by fresh execution and zero-model recovery. */
export function transformCapitalCompanyDebtFinalProduct(input:{parsed:z.infer<typeof companyDebtDiagnosticSchema>;company:{name:string;website:string|null};locale:'pt-BR'|'en-US';asOfDate:string;sources:z.infer<typeof researchSourceSchema>[];researchStatus:'succeeded'|'partial';accepted:{provider:'anthropic'|'openai';reportedModel:'claude-sonnet-5'|'gpt-5.6-terra'}}){
 return capitalCompanyDebtArtifactSchema.parse({schemaVersion:'company-debt-diagnostic.v1',asOfDate:input.asOfDate,company:input.company,...input.parsed,sources:input.sources.map(s=>({title:s.title,url:s.url,topic:s.topic,publishedAt:s.publishedAt,provider:s.provider})),researchStatus:input.researchStatus,scopeBoundary:input.locale==='pt-BR'?'Diagnóstico preliminar baseado em informações públicas. Não é underwriting, parecer de crédito, capacidade calculada ou recomendação de operação. Cálculos exigem documentos conciliados e confirmação do usuário.':'Preliminary diagnostic based on public information. It is not underwriting, a credit opinion, calculated capacity or a transaction recommendation. Calculations require reconciled documents and user confirmation.',provenance:{provider:input.accepted.provider,model:input.accepted.reportedModel,executorVersion:'2026.09.01-v1'}});
}
