import {executeCaseEngine,publicCaseState} from '@offroad/case-engine';
import {describe,it,expect,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {createCapitalMaterialSqlPorts,validateCapitalMaterialCompilerBundle} from './capital-material-production-adapter';
const u='a9300000-0000-4000-8000-000000000001';
describe('material SQL adapter (unit protocol, no SDK/SQL authority claim)',()=>{
 it('does not accept an absent physical transport',()=>{expect(()=>createCapitalMaterialSqlPorts({client:{} as SupabaseClient,jobId:u,capability:'lease',physical:undefined as never})).toThrow('physical_transport_required');});
 it('maps genuine context seal parameters without legacy names',async()=>{const rpc=vi.fn(async()=>({data:{server:true},error:null}));const ports=createCapitalMaterialSqlPorts({client:{rpc} as unknown as SupabaseClient,jobId:u,capability:'lease',physical:{retain:vi.fn(),read:vi.fn()}});await ports.sealContext(u,u);expect(rpc).toHaveBeenCalledWith('worker_seal_material_production_context_v1',{p_job_id:u,p_capability_token:'lease',p_recipe_id:u,p_context_retained_payload_id:u});});
 it('maps source seal actual delivery IDs and status',async()=>{const rpc=vi.fn(async()=>({data:{server:true},error:null}));const ports=createCapitalMaterialSqlPorts({client:{rpc} as unknown as SupabaseClient,jobId:u,capability:'lease',physical:{retain:vi.fn(),read:vi.fn()}});await ports.sealSources(u,{deliveryIds:[u],researchStatus:'partial'});expect(rpc).toHaveBeenCalledWith('worker_seal_material_production_sources_v1',{p_job_id:u,p_capability_token:'lease',p_recipe_id:u,p_delivery_ids:[u],p_research_status:'partial'});});
 it('propagates denied recovery without treating it as absent',async()=>{const rpc=vi.fn(async()=>({data:null,error:{message:'access denied'}}));const ports=createCapitalMaterialSqlPorts({client:{rpc} as unknown as SupabaseClient,jobId:u,capability:'lease',physical:{retain:vi.fn(),read:vi.fn()}});await expect(ports.recover()).rejects.toThrow('access denied');});
 it('accepts the typed diagnostic from the actual versioned compiler and rejects a changed semantic hash',async()=>{const result=await executeCaseEngine({runId:u,caseId:u,archetypeId:'other',locale:'pt',referenceDate:'2026-10-02',candidates:[],documents:[],roomDocuments:[],dealBrief:{},resolvedMandates:[],externalReleaseApproved:false});const bundle={calculationReport:result.report,caseState:publicCaseState(result.state),materialPackage:{materials:result.state.materials}};expect(validateCapitalMaterialCompilerBundle(bundle,{sessionId:u,runId:u}).calculationReport.status).toBe(result.report.status);expect(()=>validateCapitalMaterialCompilerBundle({...bundle,calculationReport:{...result.report,reportFingerprint:'f'.repeat(64)}},{sessionId:u,runId:u})).toThrow('compiler_report_denied');});
 it('rejects untyped or fabricated calculation reports',()=>{expect(()=>validateCapitalMaterialCompilerBundle({calculationReport:{status:'succeeded'},caseState:{},materialPackage:{}},{sessionId:u,runId:u})).toThrow();});
});
