/** Synthetic unit ports only. SQL and actual SDK gates prove authority/transport. */
import {createHash,randomUUID} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import {capitalPlanningMapSchema} from "@offroad/domain-contracts";
import {legacyGatewayFingerprint,prepareGatewayInput,retentionMatrixVersion} from "@offroad/model-gateway";
import {capitalPlanningContextSchema} from "./capital-planning";
import {assembleCapitalS11Components} from "./capital-s11-native-consumer";
import {prepareCapitalS11Recipe,reconstructCapitalS11Request} from "./capital-s11-recipe";
import {capitalS11RecipeReceiptSchema,capitalS11FinalOutputFingerprint} from "./capital-s11-processing";
import {transformCapitalS11FinalProduct} from "./capital-s11-final";
import {recoverCapitalS11,capitalS11RecoveryGrantSchema,type CapitalS11RecoveryPorts} from "./capital-s11-recovery";
import type {CapitalS11RetentionScope} from "./capital-s11-protocol";
function harness(){
 const originalJob=randomUUID(),currentJob=randomUUID(),org=randomUUID(),work=randomUUID(),recipeId=randomUUID(),producer=randomUUID();
 const context=capitalPlanningContextSchema.parse({project:{id:work,organization_id:org,project_name:"Synthetic",entry_job:"capital_planning",access_basis:"public_information",current_phase:"understand"},session:{id:randomUUID(),locale:"pt-BR",company_profile:{name:"Synthetic company"},privacy_status:"public_information",representation_status:"not_claimed"},brief:{id:randomUUID(),kind:"capital_planning",version:1,content:{capitalIntent:"Compare financing alternatives"},content_fingerprint:"a".repeat(64)},plan:{id:randomUUID(),version:1,fingerprint:"b".repeat(64),compiler_version:"fixture",registry_version:"fixture"},tasks:[{id:"M04",ordinal:3,batch:1,dependencies:["M01","M02"],execution_class:"model",effect:"propose_state"}],revision:null});
 const source={topic:"identity" as const,provider:"official" as const,retrievedAt:"2026-10-02T00:00:00Z",contentHash:"c".repeat(64),title:"Synthetic source",url:"https://example.invalid/source",snippet:"Licensed synthetic excerpt",publishedAt:null};
 const deliveryId=randomUUID(),sourceRetained=randomUUID(),prelude=["M01","M02"].map(taskId=>({schemaVersion:"capital-s11-task-projection-receipt.v1" as const,recipeId,taskId,taskRunId:randomUUID(),capitalArtifactId:randomUUID(),artifactFingerprint:"d".repeat(64),artifactVersion:1,retainedPayloadId:randomUUID(),replayed:false}));
 const research={status:"succeeded" as const,sources:[source],costExposureUsd:0,jurisdiction:"BR" as const,jurisdictionNeedsConfirmation:false,strategyFingerprint:"e".repeat(64)};
 const components=assembleCapitalS11Components({jobId:originalJob,recipeId,context,company:{name:"Synthetic company",website:null},research,delivered:[{deliveryId,source,retainedPayloadId:sourceRetained}],prelude});
 const basis={jobId:originalJob,organizationId:org,workId:work,planId:context.plan.id,planFingerprint:context.plan.fingerprint,locale:"pt-BR" as const,asOfDate:"2026-10-02"},pure=prepareCapitalS11Recipe({basis,components});
 const prepared=prepareGatewayInput({...pure.prepared.request,requireInputAttestation:true,outputMode:"structured",timeoutMs:240000,dataHandling:{classification:"confidential",purpose:"case_analysis",requiredPolicyVersion:retentionMatrixVersion}});
 const pins=reconstructCapitalS11Request({...pure,prepared},{provider:"anthropic",model:"claude-sonnet-5",effort:"medium"}).ordinalFingerprints(),fallback=reconstructCapitalS11Request({...pure,prepared},{provider:"openai",model:"gpt-5.6-terra",effort:"medium"}).ordinalFingerprints();
 const parsed=capitalPlanningMapSchema.parse({executiveRead:"A synthetic insufficient base asks for more verified information before comparing alternative financing structures.",understoodNeed:{objective:"Compare financing alternatives for growth",constraints:[],assumptionsToConfirm:["Confirm the historical statements"]},evidenceCoverage:{status:"insufficient",supported:[],notYetSupported:["Reconciled financial statements"]},alternatives:[],comparison:[],directionalRecommendation:{status:"not_ready",alternativeId:null,rationale:"The available inputs do not support a comparison of funding structures.",conditionsBeforeConfirmation:["Receive the financial statements"]},informationRequests:[{request:"Financial statements",whyItMatters:"Establish an evidenced historical operating base",decisionImpact:"Determine whether alternatives can be compared",acceptableEvidence:["Statements"]}],questions:[{question:"What is the planned use?",whyItMatters:"The purpose changes available structures",answerChanges:"Select a supported universe"},{question:"What is the funding timeline?",whyItMatters:"Timing affects feasible processes",answerChanges:"Compare practical execution routes"}],unknowns:["Funding timeline remains unconfirmed"]});
 const transformed=transformCapitalS11FinalProduct({parsed,company:{name:"Synthetic company",website:null},locale:"pt-BR",asOfDate:basis.asOfDate,sources:[source],researchStatus:"succeeded",accepted:{provider:"anthropic",reportedModel:"claude-sonnet-5"}});
 const physical=new Map<string,{bytes:Uint8Array;scope:CapitalS11RetentionScope}>();
 const retain=(body:unknown)=>{const allocation=randomUUID(),bytes=Buffer.from(JSON.stringify(body)),scope:CapitalS11RetentionScope={schemaVersion:"capital-retained-body.v1",retentionState:"retained",allocationId:allocation,retainedPayloadId:randomUUID(),bodyBasisId:randomUUID(),bucket:"capital-input-capture",path:`${org}/${allocation}/payload.json`,payloadFingerprint:createHash("sha256").update(bytes).digest("hex"),byteLength:bytes.length,storageObjectId:randomUUID(),storageVersion:"synthetic-unit",retainedAt:"2026-10-02T00:00:00Z",uploadExpiresAt:"2026-10-02T00:05:00Z",purgeAt:"2030-01-01T00:00:00Z",expiresAt:"2030-01-02T00:00:00Z",replayed:true};physical.set(scope.retainedPayloadId!,{bytes,scope});return scope;};
 const {publishedAt:_publishedAt,...licensedPayload}=source;
 const contextScope=retain(context),parsedScope=retain(parsed),finalScope=retain(transformed.finalProduct),sourcePhysical=retain(licensedPayload);
 const recipe=capitalS11RecipeReceiptSchema.parse({...basis,schemaVersion:"capital-s11-recipe-receipt.v1",state:"ready",recipeId,producerTaskRunId:producer,producerTaskId:"M04",finalTaskId:"S11",rendererVersion:"capital-public-task-renderer.s11.v1",recipeFingerprint:"f".repeat(64),reconstructionFingerprint:prepared.inputFingerprint,contextRetainedPayloadId:contextScope.retainedPayloadId,components:pure.recipe.components,expiresAt:"2030-01-02T00:00:00Z",operationalBudget:{schemaVersion:"capital-s11-operational-budget.v1",researchReservationVersion:"public-research-reservation.s11.v1",researchReservationMicroUsd:300000,maxExposureMicroUsd:650000,maxDispatches:2}});
 const grant=capitalS11RecoveryGrantSchema.parse({schemaVersion:"capital-s11-recovery-grant.v1",mode:"recovery",state:"committed",recipeId,originalJobId:originalJob,authorizedJobId:currentJob,organizationId:org,workId:work,taskRunId:producer,recipe,requestPins:{schemaVersion:"capital-s11-reconstruction-pins.v1",promptFingerprint:pins.promptFingerprint,primaryRequestFingerprint:pins.requestFingerprint,fallbackRequestFingerprint:fallback.requestFingerprint},reconstructionMetadata:{schemaVersion:"capital-s11-reconstruction-metadata.v1",originalAttempt:1,researchStatus:"succeeded",jurisdiction:"BR",jurisdictionNeedsConfirmation:false,strategyFingerprint:research.strategyFingerprint,dependencies:prelude.map(p=>({id:p.capitalArtifactId,artifactFingerprint:p.artifactFingerprint}))},qualityFailure:null,accepted:{acceptedInvocationId:randomUUID(),inputReceiptId:randomUUID(),invocationId:randomUUID(),outputFingerprint:legacyGatewayFingerprint(parsed),provider:"anthropic",reportedModel:"claude-sonnet-5"},context:contextScope,sources:[{deliveryId,retainedPayloadId:sourceRetained}],parsed:parsedScope,final:finalScope,revisionId:randomUUID(),capitalArtifactId:randomUUID(),expiresAt:"2030-01-02T00:00:00Z",dispatchAllowed:false});
 const receipt={schemaVersion:"capital-s11-commit-receipt.v1",recipeId,producerTaskRunId:producer,taskRunId:randomUUID(),capitalArtifactId:grant.capitalArtifactId!,revisionId:grant.revisionId!,finalFingerprint:capitalS11FinalOutputFingerprint(legacyGatewayFingerprint(parsed),recipe.recipeFingerprint,transformed.finalProduct),artifactFingerprint:"0".repeat(64),artifactVersion:1,replayed:true};
 const sourceScope={schemaVersion:"capital-public-storage-scope.v1",state:"complete",allocationId:sourcePhysical.allocationId,retainedPayloadId:sourceRetained,deliveryId,bucket:sourcePhysical.bucket,path:sourcePhysical.path,payloadFingerprint:sourcePhysical.payloadFingerprint,byteLength:sourcePhysical.byteLength,storageObjectId:sourcePhysical.storageObjectId,storageVersion:sourcePhysical.storageVersion,retainedAt:sourcePhysical.retainedAt,uploadExpiresAt:sourcePhysical.uploadExpiresAt,expiresAt:sourcePhysical.expiresAt,purgeAt:sourcePhysical.purgeAt};
 const ports:CapitalS11RecoveryPorts={discover:vi.fn(async()=>({schemaVersion:"capital-s11-recovery-discovery.v1",state:"recovery",recipeId})),grant:vi.fn(async()=>structuredClone(grant)),readBody:vi.fn(async scope=>physical.get(scope.retainedPayloadId!)!),readSource:vi.fn(async()=>({bytes:physical.get(sourcePhysical.retainedPayloadId!)!.bytes,scope:sourceScope})),retainFinal:vi.fn(async input=>retain(input.body)),deriveTasks:vi.fn(async()=>{}),commit:vi.fn(async()=>receipt),qualityFailure:vi.fn(async()=>{throw new Error("unexpected quality diagnostic");})};
 return{job:{jobId:currentJob,organizationId:org,workId:work},ports,grant,receipt,physical};
}
describe("S11 physical recovery, pure unit ports",()=>{
 it("replays a committed original product under a successor grant without any model/research/derive port",async()=>{
  const h=harness();expect(await recoverCapitalS11(h.job,h.ports,()=>Date.parse("2026-10-02T01:00:00Z"))).toMatchObject(h.receipt);
  expect(h.ports.deriveTasks).not.toHaveBeenCalled();expect(h.ports.retainFinal).not.toHaveBeenCalled();expect(h.ports.commit).toHaveBeenCalledOnce();
 });
 it.each(["wrong_job","changed_pin","changed_dependency","missing_bytes","source_tamper"])("denies %s before commit",async kind=>{
  const h=harness();if(kind==="wrong_job")h.grant.authorizedJobId=randomUUID();if(kind==="changed_pin")h.grant.requestPins.primaryRequestFingerprint="0".repeat(64);if(kind==="changed_dependency")h.grant.reconstructionMetadata.dependencies[0]!.artifactFingerprint="0".repeat(64);
  if(kind==="missing_bytes")h.ports.readBody=vi.fn(async()=>{throw new Error("Synthetic missing physical bytes");});
  if(kind==="source_tamper"){const original=h.ports.readSource;h.ports.readSource=vi.fn(async ref=>({...await original(ref),bytes:Buffer.from("tampered")}));}
  await expect(recoverCapitalS11(h.job,h.ports,()=>Date.parse("2026-10-02T01:00:00Z"))).rejects.toThrow();expect(h.ports.commit).not.toHaveBeenCalled();expect(h.ports.deriveTasks).not.toHaveBeenCalled();
 });
 it("returns no recipe only for actual server none, while unresolved never starts a model path",async()=>{
  const h=harness();h.ports.discover=vi.fn(async()=>({schemaVersion:"capital-s11-recovery-discovery.v1",state:"none",recipeId:null}));expect(await recoverCapitalS11(h.job,h.ports)).toBeNull();expect(h.ports.grant).not.toHaveBeenCalled();
  h.ports.discover=vi.fn(async()=>({schemaVersion:"capital-s11-recovery-discovery.v1",state:"unresolved",recipeId:h.grant.recipeId}));await expect(recoverCapitalS11(h.job,h.ports)).rejects.toThrow("capital_s11_retained_recovery_required");expect(h.ports.commit).not.toHaveBeenCalled();
 });
});
