import {createHash} from 'node:crypto';
import {describe,it,expect,vi} from 'vitest';
import {createCapitalMaterialProducer,type MaterialBodyScope,type MaterialCapture,type CapitalMaterialProductionPorts,type MaterialResearchInput} from './capital-material-production-native';
const u=(n:number)=>`a9300000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function setup(){
 let next=20;const bodies=new Map<string,string>();
 const scope=(kind:MaterialBodyScope['kind'],body:unknown):MaterialBodyScope=>{const allocationId=u(next++),canonical=JSON.stringify(body);bodies.set(allocationId,canonical);return {schemaVersion:'capital-material-body-scope.v1',organizationId:u(2),workId:u(3),recipeId:u(4),allocationId,retainedPayloadId:null,kind,payloadFingerprint:hash(canonical),byteLength:Buffer.byteLength(canonical),bucket:'capital-input-capture',path:`${u(2)}/${allocationId}/payload.json`,storageObjectId:null,storageVersion:null,expiresAt:'2026-10-03T00:00:00Z',purgeAt:'2026-10-02T23:50:00Z'};};
 const retain=(s:MaterialBodyScope)=>({...s,retainedPayloadId:u(next++),storageObjectId:u(next++),storageVersion:'physical-1'});
 let receipt:MaterialCapture={schemaVersion:'capital-material-capture.v1',state:'ready',recipeId:u(4),jobId:u(1),organizationId:u(2),workId:u(3),productionPlanId:u(5),productionPlanVersion:1,productionPlanFingerprint:hash('plan'),inputFingerprint:hash('input'),contextFingerprint:'',sourceClosureFingerprint:hash('sources'),calculationVersion:'test-version',rendererVersion:'capital-material-package.v1',context:scope('context',{actual:'server context'})};receipt.contextFingerprint=receipt.context.payloadFingerprint;
 const ports:CapitalMaterialProductionPorts={capture:vi.fn(async()=>({receipt:structuredClone(receipt),canonicalBody:bodies.get(receipt.context.allocationId)!})),retain:vi.fn(async(s:MaterialBodyScope)=>retain(s)),sealContext:vi.fn(async(_r:string,id:string)=>{receipt={...receipt,context:{...receipt.context,retainedPayloadId:id,storageObjectId:u(next-1),storageVersion:'physical-1'}};return structuredClone(receipt);}),sealSources:vi.fn(async(recipeId:string,research:MaterialResearchInput)=>({schemaVersion:'capital-material-source-seal.v1',recipeId,sourceFingerprint:hash('public-sources'),...research})),revalidate:vi.fn(async()=>structuredClone(receipt)),prepareOutput:vi.fn(async({kind,body}:Parameters<CapitalMaterialProductionPorts['prepareOutput']>[0])=>{const s=scope(kind,body);return {scope:s,canonicalBody:bodies.get(s.allocationId)!};}),commit:vi.fn(async({outputs}:Parameters<CapitalMaterialProductionPorts['commit']>[0])=>({schemaVersion:'capital-material-commit.v1',recipeId:u(4),workId:u(3),productionPlanId:u(5),materialObjectId:u(6),revisionId:u(7),reportRetainedPayloadId:outputs.find(s=>s.kind==='calculation_report')!.retainedPayloadId!,stateRetainedPayloadId:outputs.find(s=>s.kind==='case_state')!.retainedPayloadId!,packageRetainedPayloadId:outputs.find(s=>s.kind==='material_package')!.retainedPayloadId!,bundleFingerprint:hash('bundle'),replayed:false})),recordTerminal:vi.fn(async(recipeId:string,reportRetainedPayloadId:string)=>({schemaVersion:'capital-material-terminal.v1',recipeId,reportRetainedPayloadId,reportStatus:'blocked',reason:'compiler_blocked',caseStateRetainedPayloadId:null,replayed:false})),recover:vi.fn(async()=>null),read:vi.fn(async(s:MaterialBodyScope)=>({scope:s,bytes:Buffer.from(bodies.get(s.allocationId)!)}))};
 const compile=vi.fn(async(_context:Record<string,unknown>,_capture:MaterialCapture,sealResearch:(research:MaterialResearchInput)=>Promise<void>)=>{await sealResearch({deliveryIds:[],researchStatus:'abstained'});return {calculationReport:{version:'test-version',value:42},caseState:{decision:'private'},materialPackage:{materials:[{kind:'teaser'}]}};});
 return {ports,compile,receipt,scope,retain,producer:()=>createCapitalMaterialProducer({jobId:u(1),workId:u(3),ports,now:()=>Date.parse('2026-10-02T12:00:00Z')})};
}
describe('finite native material bundle port (unit protocol, no SQL/Storage proof)',()=>{
 it('retains context before actual compiler and commits three exact physical outputs',async()=>{const t=setup();const r=await t.producer().run(u(9),t.compile);expect(r.replayed).toBe(false);expect(t.compile).toHaveBeenCalledWith({actual:'server context'},expect.objectContaining({context:expect.objectContaining({retainedPayloadId:expect.any(String)})}),expect.any(Function));expect(t.ports.retain).toHaveBeenCalledTimes(4);expect(t.ports.commit).toHaveBeenCalledOnce();expect(vi.mocked(t.ports.sealContext).mock.invocationCallOrder[0]!).toBeLessThan(t.compile.mock.invocationCallOrder[0]!);});
 it('requires research seal before retaining outputs',async()=>{const t=setup();const compile=vi.fn(async()=>({calculationReport:{},caseState:{},materialPackage:{}}));await expect(t.producer().run(u(9),compile)).rejects.toThrow('source_seal_required');expect(t.ports.prepareOutput).not.toHaveBeenCalled();});
 it('denies source seal receipt substitution',async()=>{const t=setup();vi.mocked(t.ports.sealSources).mockResolvedValue({schemaVersion:'capital-material-source-seal.v1',recipeId:u(90),sourceFingerprint:hash('sources'),deliveryIds:[],researchStatus:'abstained'});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('source_seal_changed');expect(t.ports.prepareOutput).not.toHaveBeenCalled();});
 it('retains blocked report alone and records terminal without publishing materials',async()=>{const t=setup();const compile=vi.fn(async(_c:Record<string,unknown>,_r:MaterialCapture,seal:(r:MaterialResearchInput)=>Promise<void>)=>{await seal({deliveryIds:[],researchStatus:'abstained'});return {calculationReport:{status:'blocked'},caseState:{},materialPackage:{}};});const r=await t.producer().run(u(9),compile);expect(r.schemaVersion).toBe('capital-material-terminal.v1');expect(t.ports.prepareOutput).toHaveBeenCalledTimes(1);expect(t.ports.commit).not.toHaveBeenCalled();expect(t.ports.recordTerminal).toHaveBeenCalledOnce();});
 it('preserves succeeded report and retains blocked domain state without publishing package',async()=>{const t=setup();vi.mocked(t.ports.recordTerminal).mockImplementation(async(recipeId,reportRetainedPayloadId,caseStateRetainedPayloadId)=>({schemaVersion:'capital-material-terminal.v1',recipeId,reportRetainedPayloadId,caseStateRetainedPayloadId,reportStatus:'succeeded',reason:'domain_material_blocked',replayed:false}));const compile=async(_c:Record<string,unknown>,_r:MaterialCapture,seal:(r:MaterialResearchInput)=>Promise<void>)=>{await seal({deliveryIds:[],researchStatus:'abstained'});return {calculationReport:{status:'succeeded'},caseState:{materials:[],materialsBlockedBy:['brief_unavailable']},materialPackage:{materials:[]}};};const r=await t.producer().run(u(9),compile);expect(r).toMatchObject({schemaVersion:'capital-material-terminal.v1',reportStatus:'succeeded',reason:'domain_material_blocked',caseStateRetainedPayloadId:expect.any(String)});expect(t.ports.prepareOutput).toHaveBeenCalledTimes(2);expect(t.ports.commit).not.toHaveBeenCalled();});
 it('denies scope mismatch before compiler',async()=>{const t=setup();vi.mocked(t.ports.capture).mockResolvedValue({receipt:{...t.receipt,workId:u(90)},canonicalBody:'{}'});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('capture_denied');expect(t.compile).not.toHaveBeenCalled();});
 it('denies altered canonical context before retention',async()=>{const t=setup();vi.mocked(t.ports.capture).mockResolvedValue({receipt:t.receipt,canonicalBody:'{"other":true}'});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('bytes_changed');expect(t.ports.retain).not.toHaveBeenCalled();});
 it('denies missing physical receipt before compiler',async()=>{const t=setup();vi.mocked(t.ports.retain).mockImplementation(async(s:MaterialBodyScope)=>s);await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('physical_receipt_required');expect(t.compile).not.toHaveBeenCalled();});
 it('denies changed source/input pin before compiler',async()=>{const t=setup();vi.mocked(t.ports.revalidate).mockImplementation(async(r)=>({...r,sourceClosureFingerprint:hash('changed')}));await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('inputs_changed');expect(t.compile).not.toHaveBeenCalled();});
 it('denies output body changed by server preparation',async()=>{const t=setup();vi.mocked(t.ports.prepareOutput).mockImplementation(async({kind})=>{const s=t.scope(kind,{changed:true});return {scope:s,canonicalBody:'{"changed":true}'};});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('canonical_product_changed');expect(t.ports.commit).not.toHaveBeenCalled();});
 it('denies output retention extending inherited context',async()=>{const t=setup();vi.mocked(t.ports.prepareOutput).mockImplementation(async({kind,body}:Parameters<CapitalMaterialProductionPorts['prepareOutput']>[0])=>{const s=t.scope(kind,body);return {scope:{...s,expiresAt:'2026-10-04T00:00:00Z'},canonicalBody:JSON.stringify(body)};});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('retention_extended');expect(t.ports.commit).not.toHaveBeenCalled();});
 it('fails closed on expiry',async()=>{const t=setup();await expect(createCapitalMaterialProducer({jobId:u(1),workId:u(3),ports:t.ports,now:()=>Date.parse('2026-10-04T00:00:00Z')}).run(u(9),t.compile)).rejects.toThrow('scope_denied');expect(t.compile).not.toHaveBeenCalled();});
 it('does not rerender on accepted physical recovery',async()=>{const t=setup(),capture={...t.receipt,context:t.retain(t.receipt.context)};const outputs=[t.retain(t.scope('calculation_report',{v:42})),t.retain(t.scope('case_state',{a:true})),t.retain(t.scope('material_package',{b:true}))];vi.mocked(t.ports.recover).mockResolvedValue({schemaVersion:'capital-material-recovery.v1',state:'commit',authorizedJobId:u(1),capture,outputs,commit:null});vi.mocked(t.ports.revalidate).mockImplementation(async(r)=>r);await t.producer().run(u(9),t.compile);expect(t.compile).not.toHaveBeenCalled();expect(t.ports.capture).not.toHaveBeenCalled();expect(t.ports.retain).not.toHaveBeenCalled();expect(t.ports.read).toHaveBeenCalledTimes(4);expect(t.ports.commit).toHaveBeenCalledOnce();});
 it('does not generate when recovery is unresolved',async()=>{const t=setup();vi.mocked(t.ports.recover).mockResolvedValue({state:'unresolved'});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow();expect(t.compile).not.toHaveBeenCalled();expect(t.ports.capture).not.toHaveBeenCalled();});
 it('rejects recovery authorized for another job',async()=>{const t=setup();vi.mocked(t.ports.recover).mockResolvedValue({schemaVersion:'capital-material-recovery.v1',state:'commit',authorizedJobId:u(90),capture:t.receipt,outputs:[t.scope('case_state',{}),t.scope('case_state',{}),t.scope('case_state',{})],commit:null});await expect(t.producer().run(u(9),t.compile)).rejects.toThrow('recovery_job_denied');expect(t.compile).not.toHaveBeenCalled();});
 it('rejects accidental second execution in same factory',async()=>{const t=setup(),p=t.producer();await p.run(u(9),t.compile);await expect(p.run(u(10),t.compile)).rejects.toThrow('already_started');expect(t.compile).toHaveBeenCalledOnce();});
});
