/** Synthetic unit ports only. SQL and actual SDK gates prove authority/transport. */
import {createHash,randomUUID} from "node:crypto";
import {z} from "zod";
import {describe,expect,it,vi} from "vitest";
import {companyDebtDiagnosticSchema} from "@offroad/domain-contracts";
import {legacyGatewayFingerprint,prepareGatewayInput,retentionMatrixVersion} from "@offroad/model-gateway";
import {companyDebtContextSchema} from "./company-debt-view";
import {assembleCapitalCompanyDebtComponents} from "./capital-company-debt-native-consumer";
import {prepareCapitalCompanyDebtRecipe,reconstructCapitalCompanyDebtRequest} from "./capital-company-debt-recipe";
import {capitalCompanyDebtRecipeReceiptSchema,capitalCompanyDebtFinalOutputFingerprint} from "./capital-company-debt-processing";
import {transformCapitalCompanyDebtFinalProduct} from "./capital-company-debt-final";
import {recoverCapitalCompanyDebt,capitalCompanyDebtRecoveryGrantSchema,type CapitalCompanyDebtRecoveryPorts} from "./capital-company-debt-recovery";
import type {CapitalCompanyDebtRetentionScope} from "./capital-company-debt-protocol";
function harness(){
 const originalJob=randomUUID(),currentJob=randomUUID(),org=randomUUID(),work=randomUUID(),recipeId=randomUUID(),producer=randomUUID();
 const context=companyDebtContextSchema.parse({project:{id:work,organization_id:org,project_name:"Synthetic",entry_job:"company_debt_view",access_basis:"public_information",current_phase:"understand"},session:{id:randomUUID(),locale:"pt-BR",company_profile:{name:"Synthetic company"},privacy_status:"public_information",representation_status:"not_claimed"},brief:{id:randomUUID(),kind:"company_debt_view",version:1,content:{focus:"Understand public debt evidence"},content_fingerprint:"a".repeat(64)},plan:{id:randomUUID(),version:1,fingerprint:"b".repeat(64),compiler_version:"fixture",registry_version:"fixture"},tasks:[{id:"M06",ordinal:5,batch:1,dependencies:["M04","M05"],execution_class:"deterministic",effect:"propose_state"}],revision:null});
 const source={topic:"identity" as const,provider:"official" as const,retrievedAt:"2026-10-02T00:00:00Z",contentHash:"c".repeat(64),title:"Synthetic source",url:"https://example.invalid/source",snippet:"Licensed synthetic excerpt",publishedAt:null};
 const deliveryId=randomUUID(),sourceRetained=randomUUID(),executionPlan={recipeId,taskId:'M06',taskRunId:producer,capitalArtifactId:randomUUID(),artifactFingerprint:'d'.repeat(64),artifactVersion:1};
 const research={status:'succeeded' as const,sources:[source],researchRunId:recipeId,costExposureUsd:0};
 const components=assembleCapitalCompanyDebtComponents({jobId:originalJob,recipeId,context,company:{name:'Synthetic company',website:null},research,delivered:[{deliveryId,source}],executionPlan});
 const basis={jobId:originalJob,organizationId:org,workId:work,planId:context.plan.id,planFingerprint:context.plan.fingerprint,locale:"pt-BR" as const,asOfDate:"2026-10-02"},pure=prepareCapitalCompanyDebtRecipe({basis,components});
 const prepared=prepareGatewayInput({...pure.prepared.request,requireInputAttestation:true,outputMode:"structured",timeoutMs:240000,dataHandling:{classification:"confidential",purpose:"case_analysis",requiredPolicyVersion:retentionMatrixVersion}});
 const pins=reconstructCapitalCompanyDebtRequest({...pure,prepared},{provider:"anthropic",model:"claude-sonnet-5",effort:"medium"}).ordinalFingerprints(),fallback=reconstructCapitalCompanyDebtRequest({...pure,prepared},{provider:"openai",model:"gpt-5.6-terra",effort:"medium"}).ordinalFingerprints();
 const synthetic=(s:any):any=>s.const!==undefined?s.const:s.enum?s.enum[0]:s.anyOf?synthetic(s.anyOf.find((v:any)=>v.type!=='null')??s.anyOf[0]):s.type==='object'?Object.fromEntries((s.required??[]).map((k:string)=>[k,synthetic(s.properties[k])])):s.type==='array'?Array.from({length:s.minItems??0},()=>synthetic(s.items)):s.type==='string'?s.format==='uri'?source.url:s.pattern?'fixture':'x'.repeat(Math.max(1,s.minLength??1)):s.type==='number'||s.type==='integer'?s.minimum??0:s.type==='boolean'?true:null;
 const raw=synthetic(z.toJSONSchema(companyDebtDiagnosticSchema));raw.capacityAssessment.status='not_computable';raw.businessRiskProfile.sourceUrls=[source.url];
 for(const key of ['financialSignals','debtAndLiquiditySignals','workingCapitalSignals','risks','diagnosticHypotheses'])for(const item of raw[key])item.sourceUrls=[source.url];
 const parsed=companyDebtDiagnosticSchema.parse(raw),finalProduct=transformCapitalCompanyDebtFinalProduct({parsed,company:{name:'Synthetic company',website:null},locale:'pt-BR',asOfDate:basis.asOfDate,sources:[source],researchStatus:'succeeded',accepted:{provider:'anthropic',reportedModel:'claude-sonnet-5'}});
 const physical=new Map<string,{bytes:Uint8Array;scope:CapitalCompanyDebtRetentionScope}>();
 const retain=(body:unknown)=>{const allocation=randomUUID(),bytes=Buffer.from(JSON.stringify(body)),scope:CapitalCompanyDebtRetentionScope={schemaVersion:"capital-retained-body.v1",retentionState:"retained",allocationId:allocation,retainedPayloadId:randomUUID(),bodyBasisId:randomUUID(),bucket:"capital-input-capture",path:`${org}/${allocation}/payload.json`,payloadFingerprint:createHash("sha256").update(bytes).digest("hex"),byteLength:bytes.length,storageObjectId:randomUUID(),storageVersion:"synthetic-unit",retainedAt:"2026-10-02T00:00:00Z",uploadExpiresAt:"2026-10-02T00:05:00Z",purgeAt:"2030-01-01T00:00:00Z",expiresAt:"2030-01-02T00:00:00Z",replayed:true};physical.set(scope.retainedPayloadId!,{bytes,scope});return scope;};
 const {publishedAt:_publishedAt,...licensedPayload}=source;
 const contextScope=retain(context),parsedScope=retain(parsed),finalScope=retain(finalProduct),sourcePhysical=retain(licensedPayload);
 const recipe=capitalCompanyDebtRecipeReceiptSchema.parse({...basis,schemaVersion:"capital-debt-recipe-receipt.v1",state:"ready",recipeId,executionPlanTaskRunId:producer,executionPlanTaskId:"M06",finalTaskId:"C11",rendererVersion:"capital-public-task-renderer.company-debt.v1",recipeFingerprint:"f".repeat(64),reconstructionFingerprint:prepared.inputFingerprint,contextRetainedPayloadId:contextScope.retainedPayloadId,components:pure.recipe.components,expiresAt:"2030-01-02T00:00:00Z",operationalBudget:{schemaVersion:"capital-debt-operational-budget.v1",researchReservationVersion:"public-research-reservation.company-debt.v1",researchReservationMicroUsd:200000,maxExposureMicroUsd:750000,maxDispatches:2}});
 const grant=capitalCompanyDebtRecoveryGrantSchema.parse({schemaVersion:"capital-debt-recovery-grant.v1",mode:"recovery",state:"committed",recipeId,originalJobId:originalJob,authorizedJobId:currentJob,organizationId:org,workId:work,executionPlanTaskRunId:producer,recipe,requestPins:{schemaVersion:"capital-debt-reconstruction-pins.v1",promptFingerprint:pins.promptFingerprint,primaryRequestFingerprint:pins.requestFingerprint,fallbackRequestFingerprint:fallback.requestFingerprint},reconstructionMetadata:{schemaVersion:"capital-debt-reconstruction-metadata.v1",originalAttempt:1,researchStatus:"succeeded",dependencies:[{id:executionPlan.capitalArtifactId,artifactFingerprint:executionPlan.artifactFingerprint}]},qualityFailure:null,accepted:{acceptedInvocationId:randomUUID(),inputReceiptId:randomUUID(),invocationId:randomUUID(),outputFingerprint:legacyGatewayFingerprint(parsed),provider:"anthropic",reportedModel:"claude-sonnet-5"},context:contextScope,sources:[{deliveryId,retainedPayloadId:sourceRetained}],parsed:parsedScope,final:finalScope,revisionId:randomUUID(),capitalArtifactId:randomUUID(),expiresAt:"2030-01-02T00:00:00Z",dispatchAllowed:false});
 const receipt={schemaVersion:"capital-debt-commit-receipt.v1",recipeId,executionPlanTaskRunId:producer,taskRunId:randomUUID(),capitalArtifactId:grant.capitalArtifactId!,revisionId:grant.revisionId!,finalFingerprint:capitalCompanyDebtFinalOutputFingerprint(legacyGatewayFingerprint(parsed),recipe.recipeFingerprint,finalProduct),artifactFingerprint:"0".repeat(64),artifactVersion:1,replayed:true};
 const sourceScope={schemaVersion:"capital-public-storage-scope.v1",state:"complete",allocationId:sourcePhysical.allocationId,retainedPayloadId:sourceRetained,deliveryId,bucket:sourcePhysical.bucket,path:sourcePhysical.path,payloadFingerprint:sourcePhysical.payloadFingerprint,byteLength:sourcePhysical.byteLength,storageObjectId:sourcePhysical.storageObjectId,storageVersion:sourcePhysical.storageVersion,retainedAt:sourcePhysical.retainedAt,uploadExpiresAt:sourcePhysical.uploadExpiresAt,expiresAt:sourcePhysical.expiresAt,purgeAt:sourcePhysical.purgeAt};
 const ports:CapitalCompanyDebtRecoveryPorts={discover:vi.fn(async()=>({schemaVersion:"capital-debt-recovery-discovery.v1",state:"recovery",recipeId})),grant:vi.fn(async()=>structuredClone(grant)),readBody:vi.fn(async scope=>physical.get(scope.retainedPayloadId!)!),readSource:vi.fn(async()=>({bytes:physical.get(sourcePhysical.retainedPayloadId!)!.bytes,scope:sourceScope})),retainFinal:vi.fn(async input=>retain(input.body)),deriveTasks:vi.fn(async()=>{}),commit:vi.fn(async()=>receipt),qualityFailure:vi.fn(async()=>{throw new Error("unexpected quality diagnostic");})};
 return{job:{jobId:currentJob,organizationId:org,workId:work},ports,grant,receipt,physical};
}
describe("C11 physical recovery, pure unit ports",()=>{
 it("replays a committed original product under a successor grant without any model/research/derive port",async()=>{
  const h=harness();expect(await recoverCapitalCompanyDebt(h.job,h.ports,()=>Date.parse("2026-10-02T01:00:00Z"))).toMatchObject(h.receipt);
  expect(h.ports.deriveTasks).not.toHaveBeenCalled();expect(h.ports.retainFinal).not.toHaveBeenCalled();expect(h.ports.commit).toHaveBeenCalledOnce();
 });
 it.each(["wrong_job","changed_pin","changed_dependency","missing_bytes","source_tamper"])("denies %s before commit",async kind=>{
  const h=harness();if(kind==="wrong_job")h.grant.authorizedJobId=randomUUID();if(kind==="changed_pin")h.grant.requestPins.primaryRequestFingerprint="0".repeat(64);if(kind==="changed_dependency")h.grant.reconstructionMetadata.dependencies[0]!.artifactFingerprint="0".repeat(64);
  if(kind==="missing_bytes")h.ports.readBody=vi.fn(async()=>{throw new Error("Synthetic missing physical bytes");});
  if(kind==="source_tamper"){const original=h.ports.readSource;h.ports.readSource=vi.fn(async ref=>({...await original(ref),bytes:Buffer.from("tampered")}));}
  await expect(recoverCapitalCompanyDebt(h.job,h.ports,()=>Date.parse("2026-10-02T01:00:00Z"))).rejects.toThrow();expect(h.ports.commit).not.toHaveBeenCalled();expect(h.ports.deriveTasks).not.toHaveBeenCalled();
 });
 it("returns no recipe only for actual server none, while unresolved never starts a model path",async()=>{
  const h=harness();h.ports.discover=vi.fn(async()=>({schemaVersion:"capital-debt-recovery-discovery.v1",state:"none",recipeId:null}));expect(await recoverCapitalCompanyDebt(h.job,h.ports)).toBeNull();expect(h.ports.grant).not.toHaveBeenCalled();
  h.ports.discover=vi.fn(async()=>({schemaVersion:"capital-debt-recovery-discovery.v1",state:"unresolved",recipeId:h.grant.recipeId}));await expect(recoverCapitalCompanyDebt(h.job,h.ports)).rejects.toThrow("capital_debt_retained_recovery_required");expect(h.ports.commit).not.toHaveBeenCalled();
 });
});
