import {it,expect,vi} from "vitest";
import {createFairExecutionPoller} from "./execution-poll";
import type {ExecutionQueueClaim} from "./execution-queue";
import type {EvaluationQueueClaim} from "./evaluation-queue";
it("continuous execution RPC failure never starves legacy work",async()=>{const legacy=vi.fn(async()=>({id:"legacy"})),execution=vi.fn(async()=>{throw Error("binding unavailable");}),log=vi.fn();const poll=createFairExecutionPoller(legacy,execution,log);for(let n=0;n<6;n++)expect(await poll()).toEqual({kind:"legacy",job:{id:"legacy"}});expect(legacy).toHaveBeenCalledTimes(6);expect(execution).toHaveBeenCalledTimes(3);expect(log).toHaveBeenCalledTimes(3);});
it("alternates kinds under continuous load and claims at most one",async()=>{const legacy=vi.fn(async()=>({id:"legacy"})),execution=vi.fn(async()=>({executionId:"execution"} as ExecutionQueueClaim));const poll=createFairExecutionPoller(legacy,execution,()=>{});expect((await poll())?.kind).toBe("execution");expect((await poll())?.kind).toBe("legacy");expect((await poll())?.kind).toBe("execution");expect(legacy).toHaveBeenCalledTimes(1);expect(execution).toHaveBeenCalledTimes(2);});
it("falls through an empty legacy queue without double claim",async()=>{const legacy=vi.fn(async()=>null),execution=vi.fn(async()=>null);const poll=createFairExecutionPoller(legacy,execution,()=>{});expect(await poll()).toBeNull();expect(await poll()).toBeNull();expect(legacy).toHaveBeenCalledTimes(2);expect(execution).toHaveBeenCalledTimes(2);});
it("rotates pinned, legacy and governed evaluation claims under continuous load, one claim per poll",async()=>{const legacy=vi.fn(async()=>({id:"legacy"})),execution=vi.fn(async()=>({executionId:"execution"} as ExecutionQueueClaim)),evaluation=vi.fn(async()=>({executionId:"evaluation"} as EvaluationQueueClaim));const poll=createFairExecutionPoller(legacy,execution,()=>{},{claim:evaluation,onFailure:()=>{}});const kinds:Array<string|undefined>=[];for(let n=0;n<6;n++)kinds.push((await poll())?.kind);expect(kinds).toEqual(["execution","legacy","evaluation","execution","legacy","evaluation"]);expect(execution).toHaveBeenCalledTimes(2);expect(legacy).toHaveBeenCalledTimes(2);expect(evaluation).toHaveBeenCalledTimes(2);});
it("a failing evaluation transport never starves pinned or legacy work",async()=>{const legacy=vi.fn(async()=>null),execution=vi.fn(async()=>({executionId:"execution"} as ExecutionQueueClaim)),failure=vi.fn();const poll=createFairExecutionPoller(legacy,execution,()=>{},{claim:async()=>{throw Error("evaluation transport unavailable");},onFailure:failure});for(let n=0;n<3;n++)expect((await poll())?.kind).toBe("execution");expect(failure).toHaveBeenCalledTimes(2);});
