import {processAgentOperationBriefJob} from "./agent-operation-brief";
import type {QueueClient} from "./queue";
import type {ModelGateway} from "@offroad/model-gateway";
import {readFileSync} from "node:fs";
import {describe,it,expect,vi} from "vitest";
import {institutionalModelRuntimeContextSchema,renderApprovedInstitutionalFinancialWorkbook} from "@offroad/financial-model";
import {processInstitutionalModelResult,processInstitutionalModelSetup} from "./institutional-model-runtime";
import {agentOperationBriefJobSchema} from "./queue";
const id="90000000-0000-4000-8000-000000000881";
const job=agentOperationBriefJobSchema.parse({claimed:true,job_id:"80000000-0000-4000-8000-000000000881",capability_token:"x".repeat(64),lease_expires_at:"2026-09-10T04:10:00Z",attempt:1,kind:"agent_operation_brief",organization_id:"20000000-0000-4000-8000-000000000881",intake_session_id:"40000000-0000-4000-8000-000000000881",processing_run_id:"70000000-0000-4000-8000-000000000881",payload:{message_id:id,locale:"en-US"}});
function fixture(){
 const sql=readFileSync(new URL("../../../supabase/tests/support/institutional_setup_fixture.sql",import.meta.url),"utf8");const data=(name:string)=>JSON.parse(sql.match(new RegExp(`set_config\\('test.setup_${name}', '([^\\n]+)', true\\);`))![1]!.replaceAll("''","'"));const candidate=data("candidate");
 const facts=data("facts") as {accepted:Record<string,unknown>}[];
 const context=institutionalModelRuntimeContextSchema.parse({projectId:"30000000-0000-4000-8000-000000000881",sourceManifestFingerprint:"a".repeat(64),currentSources:data("sources").map((s:Record<string,unknown>)=>({...s,hashVerified:true})),candidates:facts.map(({accepted:a},i)=>({id:String(i),field_path:a.fieldPath,normalized_value:a.normalizedValue,value_type:a.valueType,source_document_id:a.sourceDocument,evidence_rank:a.evidenceRank,information_class:a.informationClass,confidence:a.confidence,anchor_verified:a.anchorVerified,entity_name:a.entityName,entity_scope:a.entityScope,period_start:a.periodStart,period_end:a.periodEnd,source_anchor:a.anchor,review_state:"accepted"})),approvedConfigurations:[{id:"60000000-0000-4000-8000-000000000881",revision:1,fingerprint:candidate.configurationFingerprint,configuration:candidate.configuration,reviewedBy:candidate.submission.actorId,reviewedAt:candidate.submission.submittedAt,sourceBindings:candidate.sourceBindings}],reviewedSources:candidate.sourceBindings,pendingSetup:null,modelResultRequest:{id,configurationId:"60000000-0000-4000-8000-000000000881",configurationFingerprint:candidate.configurationFingerprint,sourceManifestFingerprint:"a".repeat(64),status:"queued",artifact:null,blockers:[]}});
 return {context,candidate,configuration:data("configuration"),artifact:data("artifact")};
}
describe("real institutional setup and result worker adapter",()=>{
 it("persists a review proposal from source-bound fact rows without automatic approval",async()=>{const f=fixture();f.context.pendingSetup={submissionId:id,configuration:f.configuration,sourceReviews:f.candidate.sourceBindings,submittedBy:f.candidate.submission.actorId,submittedAt:f.candidate.submission.submittedAt,sourceManifestFingerprint:f.context.sourceManifestFingerprint};const save=vi.fn(async()=>({candidateId:"60000000-0000-4000-8000-000000000881",revision:1,replayed:false}));const result=await processInstitutionalModelSetup({job,locale:"en-US",queue:{loadInstitutionalModelContext:async()=>f.context,recordInitialInstitutionalConfigurationCandidate:save}});expect(result.status).toBe("review_required");expect(save.mock.calls).toHaveLength(1);});
 it("calculates and stores actual reproducible workbook bytes with no model gateway dependency",async()=>{const f=fixture();let saved:unknown;const result=await processInstitutionalModelResult({job,queue:{loadInstitutionalModelContext:async()=>f.context,recordInstitutionalModelResult:async (_job,value)=>{saved=value;if(value.status==="completed")expect(await renderApprovedInstitutionalFinancialWorkbook(value.artifact,"en")).not.toBeNull();return {id,status:"completed",replayed:false};}}});expect(result.status).toBe("completed");expect(saved).toBeDefined();});
 it("routes the persisted refresh before the generic advisor and makes zero model calls",async()=>{
  const f=fixture();const gateway={complete:vi.fn(async()=>{throw new Error("No model call authorized");}),spent:()=>({costUsd:0,calls:0})} as unknown as ModelGateway;
  const queue={loadAgentContext:async()=>({session_id:job.intake_session_id,message_id:id,locale:"en-US",message:"Calculate the approved model.",message_metadata:{kind:"institutional_model_refresh"},brief:{},snapshot_fingerprint:"a".repeat(64),projection_updated_at:"2026-09-10T04:00:00Z",manifest_id:null,company_profile:{},documents:[],tasks:[],artifacts:[],recent_messages:[]}),loadInstitutionalModelContext:async()=>f.context,recordInstitutionalModelResult:vi.fn(async()=>({id,status:"completed",replayed:false})),writeStage:vi.fn(async()=>{}),recordAgentResponse:vi.fn(async()=>({})),complete:vi.fn(async()=>{}),recordAgentFailure:vi.fn(async()=>{}),fail:vi.fn(async()=>{})} as unknown as QueueClient;
  expect(await processAgentOperationBriefJob(job,{queue,gateway,log:()=>{},shadowRouting:false})).toEqual({status:"succeeded"});
  expect(gateway.complete).not.toHaveBeenCalled();expect(queue.recordInstitutionalModelResult).toHaveBeenCalledOnce();expect(queue.complete).toHaveBeenCalledWith(job,expect.objectContaining({mode:"institutional_model_refresh",state:"completed",modelCalls:0}));
 });
 it("records a blocker for changed sources instead of reusing approved economics",async()=>{const f=fixture();f.context.sourceManifestFingerprint="b".repeat(64);const save=vi.fn(async(_job:unknown,payload:unknown)=>({id,status:"blocked",replayed:false,payload}));await processInstitutionalModelResult({job,queue:{loadInstitutionalModelContext:async()=>f.context,recordInstitutionalModelResult:save}});expect(save).toHaveBeenCalledWith(job,{status:"blocked",blockers:["institutional_result_approval_or_sources_changed"]});});
 it("replays completed requests without replacing their immutable output",async()=>{const f=fixture();f.context.modelResultRequest!.status="completed";f.context.modelResultRequest!.artifact=f.artifact;const save=vi.fn();expect(await processInstitutionalModelResult({job,queue:{loadInstitutionalModelContext:async()=>f.context,recordInstitutionalModelResult:save}})).toEqual({id,status:"completed",replayed:true});expect(save).not.toHaveBeenCalled();});
});
