/** Unit producer ports only. Publication, licensing and Storage require real CI. */
import {readFileSync}from"node:fs";
import {randomUUID,createHash}from"node:crypto";
import{describe,it,expect,vi}from"vitest";
import{case01,preview}from"@offroad/credit-playbook";
import{runFinitePreviewNative,type PreviewNativePipelinePorts}from"./integration-preview-native-pipeline";
import{integrationPreviewContextSchema}from"./integration-preview";
const corpusDir=new URL('../../../docs/product/gold-cases/runs/gc01/ai-review-corpus/',import.meta.url),corpus=JSON.parse(readFileSync(new URL('manifest.json',corpusDir),'utf8'));
function fixture(options:{badSource?:boolean;replay?:boolean}={}){
 const org=randomUUID(),runId=randomUUID(),jobId=randomUUID(),workId=randomUUID(),planId=randomUUID(),briefId=randomUUID(),hash='a'.repeat(64),composition='prepare_material'as const;
 const context=integrationPreviewContextSchema.parse({mode:'integration_preview',preview:{mode:'integration_preview',composition,caseId:case01.case01EvidenceManifest.caseId,workflow:preview.previewWorkflowIdentity(composition),premises:{}},project:{id:workId,organization_id:org,project_name:'Synthetic preview',entry_job:'origination_thesis',access_basis:'public',current_phase:'analysis'},session:{id:randomUUID(),locale:'pt-BR',company_profile:{}},brief:{id:briefId,kind:'synthetic',version:1,content:{request:{turn:1,composition,audience:null,form:'internal_briefing',pages:null,sponsorInstruction:null,undefinedAspects:[]}},content_fingerprint:hash},plan:{id:planId,version:1,fingerprint:hash},tasks:preview.previewStepsForComposition(composition).map((step,i)=>({id:step.taskId,ordinal:i,batch:i,label:step.taskId,dependencies:step.dependencies,execution_class:"analysis",effect:"artifact",maturity_at_compile:"implemented"}))});
 const base={schemaVersion:'capital-preview-base.v1',runId,jobId,organizationId:org,workId,planId,briefId,planFingerprint:hash,composition,workflowFingerprint:context.preview.workflow.fingerprint,contextFingerprint:hash,canonicalContext:JSON.stringify(context),expiresAt:'2026-10-03T00:00:00Z'};
 const order:string[]=[],bodies:{kind:string;body:unknown;taskId?:string}[]=[];const calls:string[]=[];
 const ports:PreviewNativePipelinePorts={begin:async()=>({base,context}),recover:vi.fn(async()=>options.replay?{capitalArtifactId:randomUUID(),artifactFingerprint:hash,modelCalls:3,costUsd:.03,unknownCostCalls:1}:null),extraction:vi.fn(async file=>options.badSource?Buffer.from('corrupt'):readFileSync(new URL(file,corpusDir))),
 retain:vi.fn(async input=>{order.push(`retain:${input.kind}`);bodies.push(input);const bytes=Buffer.from(JSON.stringify(input.body)),allocationId=randomUUID();return{schemaVersion:'capital-retained-body.v1'as const,retentionState:'retained'as const,allocationId,retainedPayloadId:randomUUID(),bodyBasisId:randomUUID(),bucket:'capital-input-capture'as const,path:`${org}/${allocationId}/payload.json`,payloadFingerprint:createHash('sha256').update(bytes).digest('hex'),byteLength:bytes.length,storageObjectId:randomUUID(),storageVersion:'unit',retainedAt:'2026-10-02T00:00:00Z',uploadExpiresAt:'2026-10-02T00:05:00Z',expiresAt:base.expiresAt,purgeAt:'2026-10-02T23:00:00Z',replayed:false};}),
 startTask:vi.fn(async input=>{order.push(`start:${input.taskId}`);return randomUUID();}),commit:vi.fn(async input=>{order.push(`commit:${input.taskId}:${input.role}`);return{capitalArtifactId:randomUUID(),artifactFingerprint:hash};}),finishTask:vi.fn(async()=>{}),finalize:vi.fn(async()=>{}),
 paid:vi.fn(async input=>{calls.push(input.preparation.boundary);order.push(`paid:${input.preparation.boundary}`);return{output:input.preparation.boundary==='questions'?{questions:[],abstain:true,abstainReason:'Synthetic abstention'}:{sections:[{id:'synthetic',title:'Synthetic',paragraphs:[{text:'Synthetic content',references:[]}]}],abstain:true,abstainReason:'Synthetic abstention'},execution:{model:'claude-sonnet-5',modelCalls:input.preparation.boundary==='questions'?2:1,costUsd:.01,unknownCostCalls:input.preparation.boundary==='questions'?1:0,latencyMs:10}};})};
 return{ports,run:()=>runFinitePreviewNative(ports,corpus,()=>Date.parse('2026-10-02T00:30:00Z')),order,bodies,calls};
}
describe('finite actual preview JSON producer / unit ports',()=>{
 it('captures all 17 real consumed extractions before any executor or paid boundary and stores 10 outputs plus contract',async()=>{const f=fixture(),result=await f.run();expect(f.bodies.filter(b=>b.kind==='source')).toHaveLength(17);expect(f.bodies.filter(b=>b.kind==='task_output')).toHaveLength(10);expect(f.bodies.filter(b=>b.kind==='decision_contract')).toHaveLength(1);expect(f.calls).toEqual(['questions','synthesis']);expect(result.modelCalls).toBe(3);expect(result.unknownCostCalls).toBe(1);expect(result.costUsd).toBe(.02);expect(f.order.lastIndexOf('retain:source')).toBeLessThan(f.order.findIndex(s=>s.startsWith('start:')));expect(f.order.indexOf('paid:questions')).toBeLessThan(f.order.indexOf('start:A01'));expect(f.order.indexOf('start:A02')).toBeLessThan(f.order.indexOf('paid:synthesis'));expect(f.ports.finalize).toHaveBeenCalledOnce();});
 it('physical completed replay restores recorded attempt counts and never executes, renders or calls a model',async()=>{const f=fixture({replay:true}),result=await f.run();expect(result.modelCalls).toBe(3);expect(result.replayed).toBe(true);expect(f.ports.paid).not.toHaveBeenCalled();expect(f.ports.startTask).not.toHaveBeenCalled();expect(f.ports.extraction).not.toHaveBeenCalled();});
 it('resumes physically restored task outputs reuses A02 physical output and reuses the questions gateway accepted-body port',async()=>{const f=fixture();await f.run();
  const bodies=f.bodies.filter(value=>value.kind==='task_output').map(value=>value as {body:{taskId:string;inputFingerprint:string;content:{output:unknown}}});
  const retainedRun=randomUUID();f.ports.restoreTask=vi.fn(async input=>{const stored=bodies.find(value=>value.body.taskId===input.taskId);expect(stored?.body.inputFingerprint).toBe(input.inputFingerprint);return stored?{output:stored.body.content.output as preview.PreviewStepOutput,taskRunId:retainedRun,capitalArtifactId:randomUUID(),artifactFingerprint:'a'.repeat(64),status:'succeeded' as const,...(input.taskId==='A02'?{execution:{modelCalls:1,costUsd:.01,unknownCostCalls:0}}:{})}:null;});
  vi.mocked(f.ports.startTask).mockClear();vi.mocked(f.ports.commit).mockClear();vi.mocked(f.ports.paid).mockClear();
  const result=await f.run();expect(f.ports.startTask).not.toHaveBeenCalled();expect(f.ports.paid).toHaveBeenCalledOnce();expect(vi.mocked(f.ports.paid).mock.calls[0]![0].preparation.boundary).toBe('questions');expect(result.modelCalls).toBe(3);expect(f.ports.commit).not.toHaveBeenCalled();
 });
 it('denies altered installed extraction before any executor and any paid cost',async()=>{const f=fixture({badSource:true});await expect(f.run()).rejects.toThrow();expect(f.ports.paid).not.toHaveBeenCalled();expect(f.ports.startTask).not.toHaveBeenCalled();});
});
