import {describe,it,expect} from "vitest";
import type {ModelGateway} from "@offroad/model-gateway";
import {preparePreviewNativeModelRecipe} from "./integration-preview-model-recipe";
import {generatePreviewQuestions,preparePreviewQuestionsGatewayRequest,type PreviewQuestionsInput} from "./preview-questions";
import {writePreviewSynthesis,preparePreviewSynthesisGatewayRequest,type PreviewSynthesisInput} from "./preview-synthesis";
const questions:PreviewQuestionsInput={gateway:null,locale:"pt-BR",gaps:[{id:"C05.gap",taskId:"C05",methodId:"build-debt-ledger",objectLabel:"Dívida",key:"incomplete_reasons",text:"Pagamento não conciliado"}],request:{desiredOutcome:null,audience:null,depth:null,form:null,undefinedAspects:[],sponsorInstruction:null},answered:[],documents:["ITR"],fixed:[]};
const synthesis:PreviewSynthesisInput={gateway:null,locale:"pt-BR",outputs:new Map(),request:{turn:1,composition:"prepare_material",audience:null,form:"internal_briefing",pages:null,sponsorInstruction:null,undefinedAspects:[]},objectFingerprints:{},previous:null,skeleton:{source:{kind:"skeleton",model:null,costUsd:0,latencyMs:0,reason:null}} as PreviewSynthesisInput["skeleton"]};
describe("preview native real model boundary preparation",()=>{
 it("keeps A01 questions and A02 synthesis distinct with actual published caps/routes",()=>{const q=preparePreviewNativeModelRecipe({boundary:"questions",input:questions}),s=preparePreviewNativeModelRecipe({boundary:"synthesis",input:synthesis});expect([q.taskId,q.maxOutputTokens,q.timeoutMs,q.pins.map(p=>p.effort)]).toEqual(["A01",2000,60000,["low","low"]]);expect([s.taskId,s.maxOutputTokens,s.timeoutMs,s.pins.map(p=>p.effort)]).toEqual(["A02",6000,120000,["medium","medium"]]);expect(q.state).toBe("unresolved");expect(q.gaps).toContain("server_boundary_receipt_required");expect(q.schemaFingerprint).not.toBe(s.schemaFingerprint);});
 it("uses the exact same runtime request constructors and common effective adapter builder",()=>{for(const [recipe,request] of [[preparePreviewNativeModelRecipe({boundary:"questions",input:questions}),preparePreviewQuestionsGatewayRequest(questions)],[preparePreviewNativeModelRecipe({boundary:"synthesis",input:synthesis}),preparePreviewSynthesisGatewayRequest(synthesis)]] as const){expect(recipe.prepared.input).toEqual(request.input);expect(recipe.prepared.request.system).toBe(request.system);for(const pin of recipe.pins)expect(recipe.reconstruct({provider:pin.provider,model:pin.model,effort:pin.effort}).requestFingerprintV1).toBe(pin.requestFingerprint);}});
 it("pins real question text and answers and refuses weakened routes",()=>{const q=preparePreviewNativeModelRecipe({boundary:"questions",input:questions}),changed=preparePreviewNativeModelRecipe({boundary:"questions",input:{...questions,answered:[{questionId:"q",answer:"Apenas refinanciamento"}]}});expect(q.inputFingerprint).not.toBe(changed.inputFingerprint);expect(q.pins[0]!.requestFingerprint).not.toBe(changed.pins[0]!.requestFingerprint);expect(()=>q.reconstruct({provider:"anthropic",model:"claude-sonnet-5",effort:"medium"})).toThrow();});
 it("failed paid questions remain charged when fixed questions are returned",async()=>{let calls=0;const gateway:ModelGateway={complete:async()=>{calls++;throw new Error("invalid output after paid call");},spent:()=>({calls,costUsd:calls*0.023,unknownCostCalls:0,budgetExposureUsd:calls*0.03})};const result=await generatePreviewQuestions({...questions,gateway,fixed:[{id:"q",text:"Qual a prioridade?",changesTheWork:"escopo",coverage:{searched:["ITR"],answeredBy:null,answer:null},priority:1}]});expect(result.source).toBe("fixed");expect(result.costUsd).toBe(0.023);expect(gateway.spent().calls).toBe(1);});
 it("failed paid synthesis remains charged when the deterministic skeleton is returned",async()=>{let calls=0;const gateway:ModelGateway={complete:async()=>{calls++;throw new Error("provider failure after paid call");},spent:()=>({calls,costUsd:calls*0.041,unknownCostCalls:0,budgetExposureUsd:calls*0.06})};const result=await writePreviewSynthesis({...synthesis,gateway});expect(result.source.kind).toBe("skeleton");expect(result.source.costUsd).toBe(0.041);expect(gateway.spent().calls).toBe(1);});
});
